# Full Non-TA and Paper-Aligned TA Experiment

This Stage 3 notebook adds the fixed paper-aligned TA pool while retaining the untuned Stage 2 model configurations. Run setup and data preparation first, then run each model independently.

In [1]:
import sys
from pathlib import Path

project_root = Path.cwd()
if not (project_root / "models").exists():
    project_root = project_root.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))
project_root

WindowsPath('d:/SET50_direction_prediction_paper')

## Prepare Full TA Data

Creates `data-folds-full-ta` and train-only MinMax-scaled `data-folds-full-ta-nn`. The added indicators are WMA, Stochastic, RSI, MACD, Williams %R, CCI, ADX, Plus DI, and Minus DI. Existing SMA and ROC features are retained without duplication.

In [2]:
from models.full_ta_feature_pool import create_full_ta_folds, create_scaled_full_ta_nn_folds

full_ta_data_dir = create_full_ta_folds()
full_ta_nn_data_dir = create_scaled_full_ta_nn_folds()
full_ta_data_dir, full_ta_nn_data_dir

(WindowsPath('D:/SET50_direction_prediction_paper/data-folds-full-ta'),
 WindowsPath('D:/SET50_direction_prediction_paper/data-folds-full-ta-nn'))

## Ridge Regression

Uses train-fold-only StandardScaler and the unchanged baseline model configuration.

In [3]:
from models.full_ta_experiments import run_ridge_full_ta

ridge_metrics = run_ridge_full_ta()
ridge_metrics

ridge_regression_full_ta:   0%|          | 0/4 [00:00<?, ?fold/s]

     fold  train_start_year  train_end_year  test_year  n_train  n_test  \
0  fold_1              2012            2021       2022     2359     241
1  fold_2              2012            2022       2023     2600     243
2  fold_3              2012            2023       2024     2843     244
3  fold_4              2012            2024       2025     3087     234

       rmse       mae      mape        r2  direction_accuracy
0  6.936808  5.371006  0.546238  0.902858            0.585062
1  7.804107  5.958480  0.644251  0.969236            0.547325
2  6.763733  5.026060  0.580785  0.976409            0.471311
3  9.952250  7.704858  0.977921  0.961765            0.465812
      train_start_year  train_end_year  test_year  n_train  n_test      rmse  \
mean            2012.0          2022.5     2023.5  2722.25   240.5  7.864224

           mae      mape        r2  direction_accuracy
mean  6.015101  0.687299  0.952567            0.517378

,fold,train_start_year,train_end_year,test_year,n_train,n_test,rmse,mae,mape,r2,direction_accuracy
0,fold_1,2012,2021,2022,2359,241,6.936808,5.371006,0.546238,0.902858,0.585062
1,fold_2,2012,2022,2023,2600,243,7.804107,5.958480,0.644251,0.969236,0.547325
2,fold_3,2012,2023,2024,2843,244,6.763733,5.026060,0.580785,0.976409,0.471311
3,fold_4,2012,2024,2025,3087,234,9.952250,7.704858,0.977921,0.961765,0.465812

## XGBoost

Uses the full feature pool without scaling or parameter search.

In [4]:
from models.full_ta_experiments import run_xgboost_full_ta

xgboost_metrics = run_xgboost_full_ta()
xgboost_metrics

xgboost_full_ta:   0%|          | 0/4 [00:00<?, ?fold/s]

     fold  train_start_year  train_end_year  test_year  n_train  n_test  \
0  fold_1              2012            2021       2022     2359     241
1  fold_2              2012            2022       2023     2600     243
2  fold_3              2012            2023       2024     2843     244
3  fold_4              2012            2024       2025     3087     234

        rmse        mae      mape        r2  direction_accuracy
0   7.577485   5.940885  0.604670  0.884085            0.506224
1   8.628898   6.704670  0.726190  0.962390            0.514403
2   8.547372   6.823927  0.793542  0.962327            0.467213
3  26.463390  19.478965  2.550055  0.729660            0.538462
      train_start_year  train_end_year  test_year  n_train  n_test       rmse  \
mean            2012.0          2022.5     2023.5  2722.25   240.5  12.804286

           mae      mape        r2  direction_accuracy
mean  9.737112  1.168614  0.884616            0.506576

,fold,train_start_year,train_end_year,test_year,n_train,n_test,rmse,mae,mape,r2,direction_accuracy
0,fold_1,2012,2021,2022,2359,241,7.577485,5.940885,0.604670,0.884085,0.506224
1,fold_2,2012,2022,2023,2600,243,8.628898,6.704670,0.726190,0.962390,0.514403
2,fold_3,2012,2023,2024,2843,244,8.547372,6.823927,0.793542,0.962327,0.467213
3,fold_4,2012,2024,2025,3087,234,26.463390,19.478965,2.550055,0.729660,0.538462

## LightGBM

Uses the full feature pool without scaling or parameter search.

In [5]:
from models.full_ta_experiments import run_lightgbm_full_ta

lightgbm_metrics = run_lightgbm_full_ta()
lightgbm_metrics

lightgbm_full_ta:   0%|          | 0/4 [00:00<?, ?fold/s]

     fold  train_start_year  train_end_year  test_year  n_train  n_test  \
0  fold_1              2012            2021       2022     2359     241
1  fold_2              2012            2022       2023     2600     243
2  fold_3              2012            2023       2024     2843     244
3  fold_4              2012            2024       2025     3087     234

        rmse        mae      mape        r2  direction_accuracy
0   7.337420   5.785724  0.588159  0.891313            0.485477
1   7.897610   6.022166  0.650517  0.968495            0.481481
2   7.573452   5.805515  0.672106  0.970423            0.520492
3  21.494575  15.462884  2.037905  0.821649            0.555556
      train_start_year  train_end_year  test_year  n_train  n_test       rmse  \
mean            2012.0          2022.5     2023.5  2722.25   240.5  11.075764

           mae      mape       r2  direction_accuracy
mean  8.269072  0.987172  0.91297            0.510752

,fold,train_start_year,train_end_year,test_year,n_train,n_test,rmse,mae,mape,r2,direction_accuracy
0,fold_1,2012,2021,2022,2359,241,7.337420,5.785724,0.588159,0.891313,0.485477
1,fold_2,2012,2022,2023,2600,243,7.897610,6.022166,0.650517,0.968495,0.481481
2,fold_3,2012,2023,2024,2843,244,7.573452,5.805515,0.672106,0.970423,0.520492
3,fold_4,2012,2024,2025,3087,234,21.494575,15.462884,2.037905,0.821649,0.555556

## AutoGluon

Uses medium_quality, 120 seconds per fold, default hyperparameters, and no parameter search.

In [6]:
from models.full_ta_experiments import run_autogluon_full_ta

autogluon_metrics = run_autogluon_full_ta()
autogluon_metrics

autogluon_full_ta:   0%|          | 0/4 [00:00<?, ?fold/s]

d:\conda_envs\my_env\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
d:\conda_envs\my_env\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
d:\conda_envs\my_env\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
d:\conda_envs\my_env\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(

     fold  train_start_year  train_end_year  test_year  n_train  n_test  \
0  fold_1              2012            2021       2022     2359     241
1  fold_2              2012            2022       2023     2600     243
2  fold_3              2012            2023       2024     2843     244
3  fold_4              2012            2024       2025     3087     234

        rmse        mae      mape        r2  direction_accuracy
0   6.860974   5.336294  0.542475  0.904970            0.543568
1   7.705789   5.847046  0.632587  0.970007            0.473251
2   6.983918   5.177044  0.598329  0.974848            0.540984
3  22.092279  16.366678  2.156902  0.811592            0.538462
      train_start_year  train_end_year  test_year  n_train  n_test      rmse  \
mean            2012.0          2022.5     2023.5  2722.25   240.5  10.91074

           mae      mape        r2  direction_accuracy
mean  8.181765  0.982573  0.915354            0.524066

,fold,train_start_year,train_end_year,test_year,n_train,n_test,rmse,mae,mape,r2,direction_accuracy
0,fold_1,2012,2021,2022,2359,241,6.860974,5.336294,0.542475,0.904970,0.543568
1,fold_2,2012,2022,2023,2600,243,7.705789,5.847046,0.632587,0.970007,0.473251
2,fold_3,2012,2023,2024,2843,244,6.983918,5.177044,0.598329,0.974848,0.540984
3,fold_4,2012,2024,2025,3087,234,22.092279,16.366678,2.156902,0.811592,0.538462

## LSTM

Uses train-fold-only MinMax scaling and the fixed sequence length of 20.

In [7]:
from models.full_ta_experiments import run_lstm_full_ta

lstm_metrics = run_lstm_full_ta()
lstm_metrics

lstm_full_ta:   0%|          | 0/4 [00:00<?, ?fold/s]

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
WARNING:tensorflow:5 out of the last 17 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001EFC3C82CA0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 17 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001EFB8AB36A0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

     fold  train_start_year  train_end_year  test_year  n_train  n_test  \
0  fold_1              2012            2021       2022     2359     241
1  fold_2              2012            2022       2023     2600     243
2  fold_3              2012            2023       2024     2843     244
3  fold_4              2012            2024       2025     3087     234

        rmse        mae      mape        r2  direction_accuracy
0  14.312324  11.055849  1.122358  0.586468            0.535270
1  16.397659  13.405587  1.453795  0.864183            0.522634
2  13.213970  10.744083  1.253991  0.909960            0.471311
3  19.547923  15.645646  1.991374  0.852491            0.478632
      train_start_year  train_end_year  test_year  n_train  n_test       rmse  \
mean            2012.0          2022.5     2023.5  2722.25   240.5  15.867969

            mae     mape        r2  direction_accuracy
mean  12.712791  1.45538  0.803275            0.501962

,fold,train_start_year,train_end_year,test_year,n_train,n_test,rmse,mae,mape,r2,direction_accuracy
0,fold_1,2012,2021,2022,2359,241,14.312324,11.055849,1.122358,0.586468,0.535270
1,fold_2,2012,2022,2023,2600,243,16.397659,13.405587,1.453795,0.864183,0.522634
2,fold_3,2012,2023,2024,2843,244,13.213970,10.744083,1.253991,0.909960,0.471311
3,fold_4,2012,2024,2025,3087,234,19.547923,15.645646,1.991374,0.852491,0.478632

## 1D CNN

Uses the complete Full TA feature pool with train-fold-only MinMax scaling, a fixed 20-day window, and causal Conv1D padding.

In [ ]:
from models.full_ta_experiments import run_cnn_full_ta

cnn_metrics = run_cnn_full_ta()
cnn_metrics

## LSTM-CNN

Uses the complete Full TA feature pool with train-fold-only MinMax scaling and a fixed 20-day LSTM-to-causal-Conv1D architecture.

In [ ]:
from models.full_ta_experiments import run_lstm_cnn_full_ta

lstm_cnn_metrics = run_lstm_cnn_full_ta()
lstm_cnn_metrics

## Attention-LSTM

Uses the complete Full TA feature pool with train-fold-only MinMax scaling, a fixed 20-day window, and causal self-attention over the LSTM sequence.

In [ ]:
from models.full_ta_experiments import run_attention_lstm_full_ta

attention_lstm_metrics = run_attention_lstm_full_ta()
attention_lstm_metrics

## Attention-LSTM-CNN

Extends Attention-LSTM with a causal Conv1D layer before temporal pooling.

In [ ]:
from models.full_ta_experiments import run_attention_lstm_cnn_full_ta

attention_lstm_cnn_metrics = run_attention_lstm_cnn_full_ta()
attention_lstm_cnn_metrics

## Chronos T5 Tiny Reference

The original Chronos T5 Tiny remains a Close_D-only zero-shot reference because it cannot consume the tabular covariates.

In [8]:
from models.full_ta_experiments import run_chronos_full_ta_reference

chronos_reference_metrics = run_chronos_full_ta_reference()
chronos_reference_metrics

chronos_t5_tiny_zero_shot_greedy_full_ta_reference:   0%|          | 0/4 [00:00<?, ?fold/s]

`torch_dtype` is deprecated! Use `dtype` instead!

     fold  train_start_year  train_end_year  test_year  n_train  n_test  \
0  fold_1              2012            2021       2022     2419     241
1  fold_2              2012            2022       2023     2660     243
2  fold_3              2012            2023       2024     2903     244
3  fold_4              2012            2024       2025     3147     234

       rmse       mae      mape        r2  direction_accuracy
0  7.143991  5.415079  0.551044  0.896968            0.526971
1  7.869250  6.046880  0.653793  0.968721            0.460905
2  7.061215  5.463106  0.629777  0.974288            0.442623
3  9.424079  7.324703  0.926338  0.965716            0.529915
      train_start_year  train_end_year  test_year  n_train  n_test      rmse  \
mean            2012.0          2022.5     2023.5  2782.25   240.5  7.874634

           mae      mape        r2  direction_accuracy
mean  6.062442  0.690238  0.951423            0.490103

,fold,train_start_year,train_end_year,test_year,n_train,n_test,rmse,mae,mape,r2,direction_accuracy
0,fold_1,2012,2021,2022,2419,241,7.143991,5.415079,0.551044,0.896968,0.526971
1,fold_2,2012,2022,2023,2660,243,7.869250,6.046880,0.653793,0.968721,0.460905
2,fold_3,2012,2023,2024,2903,244,7.061215,5.463106,0.629777,0.974288,0.442623
3,fold_4,2012,2024,2025,3147,234,9.424079,7.324703,0.926338,0.965716,0.529915

## Load Saved Metrics

Loads only the current Stage 3 experiment outputs.

In [9]:
import pandas as pd

output_root = project_root / "outputs" / "full_ta_feature_pool"
current_runs = [
    "ridge_regression_full_ta",
    "xgboost_full_ta",
    "lightgbm_full_ta",
    "autogluon_full_ta",
    "lstm_full_ta",
    "cnn_full_ta",
    "lstm_cnn_full_ta",
    "attention_lstm_full_ta",
    "attention_lstm_cnn_full_ta",
    "chronos_t5_tiny_zero_shot_greedy_full_ta_reference",
]
saved_metrics = {}
for run_name in current_runs:
    metrics_path = output_root / run_name / "metrics_by_fold.csv"
    if metrics_path.exists():
        saved_metrics[run_name] = pd.read_csv(metrics_path)
saved_metrics

{'ridge_regression_full_ta':      fold  train_start_year  train_end_year  test_year  n_train  n_test  \
 0  fold_1              2012            2021       2022     2359     241
 1  fold_2              2012            2022       2023     2600     243
 2  fold_3              2012            2023       2024     2843     244
 3  fold_4              2012            2024       2025     3087     234

        rmse       mae      mape        r2  direction_accuracy
 0  6.936808  5.371006  0.546238  0.902858            0.585062
 1  7.804107  5.958480  0.644251  0.969236            0.547325
 2  6.763733  5.026060  0.580785  0.976409            0.471311
 3  9.952250  7.704858  0.977921  0.961765            0.465812  ,
 'xgboost_full_ta':      fold  train_start_year  train_end_year  test_year  n_train  n_test  \
 0  fold_1              2012            2021       2022     2359     241
 1  fold_2              2012            2022       2023     2600     243
 2  fold_3              2012            2023       2024     2843     244
 3  fold_4              2012            2024       2025     3087     234

         rmse        mae      mape        r2  direction_accuracy
 0   7.577485   5.940885  0.604670  0.884085            0.506224
 1   8.628898   6.704670  0.726190  0.962390            0.514403
 2   8.547372   6.823927  0.793542  0.962327            0.467213
 3  26.463390  19.478965  2.550055  0.729660            0.538462  ,
 'lightgbm_full_ta':      fold  train_start_year  train_end_year  test_year  n_train  n_test  \
 0  fold_1              2012            2021       2022     2359     241
 1  fold_2              2012            2022       2023     2600     243
 2  fold_3              2012            2023       2024     2843     244
 3  fold_4              2012            2024       2025     3087     234

         rmse        mae      mape        r2  direction_accuracy
 0   7.337420   5.785724  0.588159  0.891313            0.485477
 1   7.897610   6.022166  0.650517  0.968495            0.481481
 2   7.573452   5.805515  0.672106  0.970423            0.520492
 3  21.494575  15.462884  2.037905  0.821649            0.555556  ,
 'autogluon_full_ta':      fold  train_start_year  train_end_year  test_year  n_train  n_test  \
 0  fold_1              2012            2021       2022     2359     241
 1  fold_2              2012            2022       2023     2600     243
 2  fold_3              2012            2023       2024     2843     244
 3  fold_4              2012            2024       2025     3087     234

         rmse        mae      mape        r2  direction_accuracy
 0   6.860974   5.336294  0.542475  0.904970            0.543568
 1   7.705789   5.847046  0.632587  0.970007            0.473251
 2   6.983918   5.177044  0.598329  0.974848            0.540984
 3  22.092279  16.366678  2.156902  0.811592            0.538462  ,
 'lstm_full_ta':      fold  train_start_year  train_end_year  test_year  n_train  n_test  \
 0  fold_1              2012            2021       2022     2359     241
 1  fold_2              2012            2022       2023     2600     243
 2  fold_3              2012            2023       2024     2843     244
 3  fold_4              2012            2024       2025     3087     234

         rmse        mae      mape        r2  direction_accuracy
 0  14.312324  11.055849  1.122358  0.586468            0.535270
 1  16.397659  13.405587  1.453795  0.864183            0.522634
 2  13.213970  10.744083  1.253991  0.909960            0.471311
 3  19.547923  15.645646  1.991374  0.852491            0.478632  ,
 'chronos_t5_tiny_zero_shot_greedy_full_ta_reference':      fold  train_start_year  train_end_year  test_year  n_train  n_test  \
 0  fold_1              2012            2021       2022     2419     241
 1  fold_2              2012            2022       2023     2660     243
 2  fold_3              2012            2023       2024     2903     244
 3  fold_4              2012            2024       2025     3147     234

        rmse       mae      mape        r2  direction_accuracy
 0  7.143991  5.415079  0.551044  0.896968            0.526971
 1  7.869250  6.046880  0.653793  0.968721            0.460905
 2  7.061215  5.463106  0.629777  0.974288            0.442623
 3  9.424079  7.324703  0.926338  0.965716            0.529915  }