# Full Non-TA Feature Pool Experiment

This notebook reuses the fixed Naive Baseline model configurations without hyperparameter tuning. Run the setup and data preparation cells first, then run each model cell independently.

In [1]:
import sys
from pathlib import Path

project_root = Path.cwd()
if not (project_root / "models").exists():
    project_root = project_root.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

project_root

WindowsPath('d:/SET50_direction_prediction_paper')

## Prepare Full Non-TA Data

Tabular models use `data-folds-full-non-ta`. LSTM uses the equivalent train-only MinMax-scaled folds in `data-folds-full-non-ta-nn`.

In [2]:
from models.full_non_ta_feature_pool import create_full_non_ta_folds, create_scaled_full_non_ta_nn_folds

full_non_ta_data_dir = create_full_non_ta_folds()
full_non_ta_nn_data_dir = create_scaled_full_non_ta_nn_folds()
full_non_ta_data_dir, full_non_ta_nn_data_dir

(WindowsPath('D:/SET50_direction_prediction_paper/data-folds-full-non-ta'),
 WindowsPath('D:/SET50_direction_prediction_paper/data-folds-full-non-ta-nn'))

## Ridge Regression

Uses the Full Non-TA feature pool and a train-fold-only StandardScaler. Model parameters are unchanged from the Naive Baseline.

In [3]:
from models.full_non_ta_experiments import run_ridge_full_non_ta

ridge_metrics = run_ridge_full_non_ta()
ridge_metrics

ridge_regression_full_non_ta:   0%|          | 0/4 [00:00<?, ?fold/s]

     fold  train_start_year  train_end_year  test_year  n_train  n_test  \
0  fold_1              2012            2021       2022     2359     241
1  fold_2              2012            2022       2023     2600     243
2  fold_3              2012            2023       2024     2843     244
3  fold_4              2012            2024       2025     3087     234

       rmse       mae      mape        r2  direction_accuracy
0  6.884047  5.344987  0.543589  0.904330            0.547718
1  7.799806  5.956496  0.644483  0.969270            0.497942
2  6.745523  5.023984  0.580344  0.976536            0.487705
3  9.891580  7.623480  0.967712  0.962230            0.482906
      train_start_year  train_end_year  test_year  n_train  n_test      rmse  \
mean            2012.0          2022.5     2023.5  2722.25   240.5  7.830239

           mae      mape        r2  direction_accuracy
mean  5.987237  0.684032  0.953091            0.504068

,fold,train_start_year,train_end_year,test_year,n_train,n_test,rmse,mae,mape,r2,direction_accuracy
0,fold_1,2012,2021,2022,2359,241,6.884047,5.344987,0.543589,0.904330,0.547718
1,fold_2,2012,2022,2023,2600,243,7.799806,5.956496,0.644483,0.969270,0.497942
2,fold_3,2012,2023,2024,2843,244,6.745523,5.023984,0.580344,0.976536,0.487705
3,fold_4,2012,2024,2025,3087,234,9.891580,7.623480,0.967712,0.962230,0.482906

## XGBoost

Uses the Full Non-TA feature pool without scaling or hyperparameter tuning.

In [4]:
from models.full_non_ta_experiments import run_xgboost_full_non_ta

xgboost_metrics = run_xgboost_full_non_ta()
xgboost_metrics

xgboost_full_non_ta:   0%|          | 0/4 [00:00<?, ?fold/s]

     fold  train_start_year  train_end_year  test_year  n_train  n_test  \
0  fold_1              2012            2021       2022     2359     241
1  fold_2              2012            2022       2023     2600     243
2  fold_3              2012            2023       2024     2843     244
3  fold_4              2012            2024       2025     3087     234

        rmse        mae      mape        r2  direction_accuracy
0   7.549196   6.032759  0.613009  0.884949            0.502075
1   8.933645   6.712013  0.727370  0.959687            0.506173
2   7.665231   5.911271  0.684777  0.969702            0.495902
3  23.172003  17.526795  2.285146  0.792726            0.534188
      train_start_year  train_end_year  test_year  n_train  n_test       rmse  \
mean            2012.0          2022.5     2023.5  2722.25   240.5  11.830019

           mae      mape        r2  direction_accuracy
mean  9.045709  1.077575  0.901766            0.509584

,fold,train_start_year,train_end_year,test_year,n_train,n_test,rmse,mae,mape,r2,direction_accuracy
0,fold_1,2012,2021,2022,2359,241,7.549196,6.032759,0.613009,0.884949,0.502075
1,fold_2,2012,2022,2023,2600,243,8.933645,6.712013,0.727370,0.959687,0.506173
2,fold_3,2012,2023,2024,2843,244,7.665231,5.911271,0.684777,0.969702,0.495902
3,fold_4,2012,2024,2025,3087,234,23.172003,17.526795,2.285146,0.792726,0.534188

## LightGBM

Uses the Full Non-TA feature pool without scaling or hyperparameter tuning.

In [5]:
from models.full_non_ta_experiments import run_lightgbm_full_non_ta

lightgbm_metrics = run_lightgbm_full_non_ta()
lightgbm_metrics

lightgbm_full_non_ta:   0%|          | 0/4 [00:00<?, ?fold/s]

     fold  train_start_year  train_end_year  test_year  n_train  n_test  \
0  fold_1              2012            2021       2022     2359     241
1  fold_2              2012            2022       2023     2600     243
2  fold_3              2012            2023       2024     2843     244
3  fold_4              2012            2024       2025     3087     234

        rmse        mae      mape        r2  direction_accuracy
0   7.379906   5.778727  0.587323  0.890051            0.448133
1   7.829585   5.999921  0.648625  0.969035            0.547325
2   7.678436   5.809720  0.672284  0.969597            0.463115
3  20.940886  15.183146  1.998019  0.830719            0.559829
      train_start_year  train_end_year  test_year  n_train  n_test       rmse  \
mean            2012.0          2022.5     2023.5  2722.25   240.5  10.957203

           mae      mape        r2  direction_accuracy
mean  8.192878  0.976563  0.914851              0.5046

,fold,train_start_year,train_end_year,test_year,n_train,n_test,rmse,mae,mape,r2,direction_accuracy
0,fold_1,2012,2021,2022,2359,241,7.379906,5.778727,0.587323,0.890051,0.448133
1,fold_2,2012,2022,2023,2600,243,7.829585,5.999921,0.648625,0.969035,0.547325
2,fold_3,2012,2023,2024,2843,244,7.678436,5.809720,0.672284,0.969597,0.463115
3,fold_4,2012,2024,2025,3087,234,20.940886,15.183146,1.998019,0.830719,0.559829

## AutoGluon

Uses the Full Non-TA feature pool with `medium_quality`, 120 seconds per fold, default hyperparameters, and no hyperparameter tuning.

In [6]:
from models.full_non_ta_experiments import run_autogluon_full_non_ta

autogluon_metrics = run_autogluon_full_non_ta()
autogluon_metrics

autogluon_full_non_ta:   0%|          | 0/4 [00:00<?, ?fold/s]

d:\conda_envs\my_env\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
d:\conda_envs\my_env\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
d:\conda_envs\my_env\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
d:\conda_envs\my_env\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(

     fold  train_start_year  train_end_year  test_year  n_train  n_test  \
0  fold_1              2012            2021       2022     2359     241
1  fold_2              2012            2022       2023     2600     243
2  fold_3              2012            2023       2024     2843     244
3  fold_4              2012            2024       2025     3087     234

        rmse        mae      mape        r2  direction_accuracy
0   7.028640   5.558251  0.564612  0.900269            0.506224
1   7.672723   5.790279  0.626492  0.970264            0.506173
2   7.126497   5.342636  0.617601  0.973811            0.504098
3  17.291621  13.289794  1.737050  0.884578            0.542735
      train_start_year  train_end_year  test_year  n_train  n_test      rmse  \
mean            2012.0          2022.5     2023.5  2722.25   240.5  9.779871

          mae      mape       r2  direction_accuracy
mean  7.49524  0.886439  0.93223            0.514808

,fold,train_start_year,train_end_year,test_year,n_train,n_test,rmse,mae,mape,r2,direction_accuracy
0,fold_1,2012,2021,2022,2359,241,7.028640,5.558251,0.564612,0.900269,0.506224
1,fold_2,2012,2022,2023,2600,243,7.672723,5.790279,0.626492,0.970264,0.506173
2,fold_3,2012,2023,2024,2843,244,7.126497,5.342636,0.617601,0.973811,0.504098
3,fold_4,2012,2024,2025,3087,234,17.291621,13.289794,1.737050,0.884578,0.542735

## LSTM

Uses all Full Non-TA features with train-fold-only MinMax scaling and the fixed Naive Baseline sequence length of 20. No window search is performed.

In [7]:
from models.full_non_ta_experiments import run_lstm_full_non_ta

lstm_metrics = run_lstm_full_non_ta()
lstm_metrics

lstm_full_non_ta:   0%|          | 0/4 [00:00<?, ?fold/s]

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
WARNING:tensorflow:5 out of the last 17 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001F898D5B9C0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 17 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001F89A728180> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

     fold  train_start_year  train_end_year  test_year  n_train  n_test  \
0  fold_1              2012            2021       2022     2359     241
1  fold_2              2012            2022       2023     2600     243
2  fold_3              2012            2023       2024     2843     244
3  fold_4              2012            2024       2025     3087     234

        rmse        mae      mape        r2  direction_accuracy
0  11.808770   9.333192  0.948093  0.718487            0.560166
1  16.099081  12.661344  1.377218  0.869084            0.551440
2  13.020176  10.751984  1.255885  0.912581            0.483607
3  26.598926  22.987880  2.925480  0.726884            0.508547
      train_start_year  train_end_year  test_year  n_train  n_test       rmse  \
mean            2012.0          2022.5     2023.5  2722.25   240.5  16.881738

          mae      mape        r2  direction_accuracy
mean  13.9336  1.626669  0.806759             0.52594

,fold,train_start_year,train_end_year,test_year,n_train,n_test,rmse,mae,mape,r2,direction_accuracy
0,fold_1,2012,2021,2022,2359,241,11.808770,9.333192,0.948093,0.718487,0.560166
1,fold_2,2012,2022,2023,2600,243,16.099081,12.661344,1.377218,0.869084,0.551440
2,fold_3,2012,2023,2024,2843,244,13.020176,10.751984,1.255885,0.912581,0.483607
3,fold_4,2012,2024,2025,3087,234,26.598926,22.987880,2.925480,0.726884,0.508547

## 1D CNN

Uses all Full Non-TA features with train-fold-only MinMax scaling, a fixed 20-day window, and causal Conv1D padding.

In [ ]:
from models.full_non_ta_experiments import run_cnn_full_non_ta

cnn_metrics = run_cnn_full_non_ta()
cnn_metrics

## LSTM-CNN

Uses all Full Non-TA features with train-fold-only MinMax scaling and a fixed 20-day LSTM-to-causal-Conv1D architecture.

In [ ]:
from models.full_non_ta_experiments import run_lstm_cnn_full_non_ta

lstm_cnn_metrics = run_lstm_cnn_full_non_ta()
lstm_cnn_metrics

## Attention-LSTM

Uses all Full Non-TA features with train-fold-only MinMax scaling, a fixed 20-day window, and causal self-attention over the LSTM sequence.

In [ ]:
from models.full_non_ta_experiments import run_attention_lstm_full_non_ta

attention_lstm_metrics = run_attention_lstm_full_non_ta()
attention_lstm_metrics

## Attention-LSTM-CNN

Extends Attention-LSTM with a causal Conv1D layer before temporal pooling.

In [ ]:
from models.full_non_ta_experiments import run_attention_lstm_cnn_full_non_ta

attention_lstm_cnn_metrics = run_attention_lstm_cnn_full_non_ta()
attention_lstm_cnn_metrics

## Chronos T5 Tiny Reference

The original Chronos T5 Tiny interface is univariate and cannot consume the Full Non-TA covariates. This cell reuses the exact Naive Baseline zero-shot, greedy, `Close_D`-only configuration and reports it as a model-native reference rather than a Full Non-TA model.

In [8]:
from models.full_non_ta_experiments import run_chronos_full_non_ta_reference

chronos_reference_metrics = run_chronos_full_non_ta_reference()
chronos_reference_metrics

chronos_t5_tiny_zero_shot_greedy_reference:   0%|          | 0/4 [00:00<?, ?fold/s]

`torch_dtype` is deprecated! Use `dtype` instead!

     fold  train_start_year  train_end_year  test_year  n_train  n_test  \
0  fold_1              2012            2021       2022     2419     241
1  fold_2              2012            2022       2023     2660     243
2  fold_3              2012            2023       2024     2903     244
3  fold_4              2012            2024       2025     3147     234

       rmse       mae      mape        r2  direction_accuracy
0  7.143991  5.415079  0.551044  0.896968            0.526971
1  7.869250  6.046880  0.653793  0.968721            0.460905
2  7.061215  5.463106  0.629777  0.974288            0.442623
3  9.424079  7.324703  0.926338  0.965716            0.529915
      train_start_year  train_end_year  test_year  n_train  n_test      rmse  \
mean            2012.0          2022.5     2023.5  2782.25   240.5  7.874634

           mae      mape        r2  direction_accuracy
mean  6.062442  0.690238  0.951423            0.490103

,fold,train_start_year,train_end_year,test_year,n_train,n_test,rmse,mae,mape,r2,direction_accuracy
0,fold_1,2012,2021,2022,2419,241,7.143991,5.415079,0.551044,0.896968,0.526971
1,fold_2,2012,2022,2023,2660,243,7.869250,6.046880,0.653793,0.968721,0.460905
2,fold_3,2012,2023,2024,2903,244,7.061215,5.463106,0.629777,0.974288,0.442623
3,fold_4,2012,2024,2025,3147,234,9.424079,7.324703,0.926338,0.965716,0.529915

## Load Saved Metrics

Loads all completed model results from `outputs/full_non_ta_feature_pool`.

In [9]:
import pandas as pd

output_root = project_root / "outputs" / "full_non_ta_feature_pool"
current_runs = [
    "ridge_regression_full_non_ta",
    "xgboost_full_non_ta",
    "lightgbm_full_non_ta",
    "autogluon_full_non_ta",
    "lstm_full_non_ta",
    "cnn_full_non_ta",
    "lstm_cnn_full_non_ta",
    "attention_lstm_full_non_ta",
    "attention_lstm_cnn_full_non_ta",
    "chronos_t5_tiny_zero_shot_greedy_reference",
]
saved_metrics = {}
for run_name in current_runs:
    metrics_path = output_root / run_name / "metrics_by_fold.csv"
    if metrics_path.exists():
        saved_metrics[run_name] = pd.read_csv(metrics_path)
saved_metrics

{'ridge_regression_full_non_ta':      fold  train_start_year  train_end_year  test_year  n_train  n_test  \
 0  fold_1              2012            2021       2022     2359     241
 1  fold_2              2012            2022       2023     2600     243
 2  fold_3              2012            2023       2024     2843     244
 3  fold_4              2012            2024       2025     3087     234

        rmse       mae      mape        r2  direction_accuracy
 0  6.884047  5.344987  0.543589  0.904330            0.547718
 1  7.799806  5.956496  0.644483  0.969270            0.497942
 2  6.745523  5.023984  0.580344  0.976536            0.487705
 3  9.891580  7.623480  0.967712  0.962230            0.482906  ,
 'xgboost_full_non_ta':      fold  train_start_year  train_end_year  test_year  n_train  n_test  \
 0  fold_1              2012            2021       2022     2359     241
 1  fold_2              2012            2022       2023     2600     243
 2  fold_3              2012            2023       2024     2843     244
 3  fold_4              2012            2024       2025     3087     234

         rmse        mae      mape        r2  direction_accuracy
 0   7.549196   6.032759  0.613009  0.884949            0.502075
 1   8.933645   6.712013  0.727370  0.959687            0.506173
 2   7.665231   5.911271  0.684777  0.969702            0.495902
 3  23.172003  17.526795  2.285146  0.792726            0.534188  ,
 'lightgbm_full_non_ta':      fold  train_start_year  train_end_year  test_year  n_train  n_test  \
 0  fold_1              2012            2021       2022     2359     241
 1  fold_2              2012            2022       2023     2600     243
 2  fold_3              2012            2023       2024     2843     244
 3  fold_4              2012            2024       2025     3087     234

         rmse        mae      mape        r2  direction_accuracy
 0   7.379906   5.778727  0.587323  0.890051            0.448133
 1   7.829585   5.999921  0.648625  0.969035            0.547325
 2   7.678436   5.809720  0.672284  0.969597            0.463115
 3  20.940886  15.183146  1.998019  0.830719            0.559829  ,
 'autogluon_full_non_ta':      fold  train_start_year  train_end_year  test_year  n_train  n_test  \
 0  fold_1              2012            2021       2022     2359     241
 1  fold_2              2012            2022       2023     2600     243
 2  fold_3              2012            2023       2024     2843     244
 3  fold_4              2012            2024       2025     3087     234

         rmse        mae      mape        r2  direction_accuracy
 0   7.028640   5.558251  0.564612  0.900269            0.506224
 1   7.672723   5.790279  0.626492  0.970264            0.506173
 2   7.126497   5.342636  0.617601  0.973811            0.504098
 3  17.291621  13.289794  1.737050  0.884578            0.542735  ,
 'lstm_full_non_ta':      fold  train_start_year  train_end_year  test_year  n_train  n_test  \
 0  fold_1              2012            2021       2022     2359     241
 1  fold_2              2012            2022       2023     2600     243
 2  fold_3              2012            2023       2024     2843     244
 3  fold_4              2012            2024       2025     3087     234

         rmse        mae      mape        r2  direction_accuracy
 0  11.808770   9.333192  0.948093  0.718487            0.560166
 1  16.099081  12.661344  1.377218  0.869084            0.551440
 2  13.020176  10.751984  1.255885  0.912581            0.483607
 3  26.598926  22.987880  2.925480  0.726884            0.508547  ,
 'chronos_t5_tiny_zero_shot_greedy_reference':      fold  train_start_year  train_end_year  test_year  n_train  n_test  \
 0  fold_1              2012            2021       2022     2419     241
 1  fold_2              2012            2022       2023     2660     243
 2  fold_3              2012            2023       2024     2903     244
 3  fold_4              2012            2024       2025     3147     234

        rmse       mae      mape        r2  direction_accuracy
 0  7.143991  5.415079  0.551044  0.896968            0.526971
 1  7.869250  6.046880  0.653793  0.968721            0.460905
 2  7.061215  5.463106  0.629777  0.974288            0.442623
 3  9.424079  7.324703  0.926338  0.965716            0.529915  }