## Inspect Optuna Progress and Best Parameters

In [4]:
from models.tuned_strong_models import tuning_status

optuna_status = tuning_status()
optuna_status

[I 2026-07-08 19:53:27,104] Using an existing study with name 'ridge_optuna_full_ta_fold_1' instead of creating a new one.
[I 2026-07-08 19:53:27,210] Using an existing study with name 'ridge_optuna_full_ta_fold_2' instead of creating a new one.
[I 2026-07-08 19:53:27,296] Using an existing study with name 'ridge_optuna_full_ta_fold_3' instead of creating a new one.
[I 2026-07-08 19:53:27,386] Using an existing study with name 'ridge_optuna_full_ta_fold_4' instead of creating a new one.
[I 2026-07-08 19:53:27,478] Using an existing study with name 'xgboost_optuna_full_ta_fold_1' instead of creating a new one.
[I 2026-07-08 19:53:27,801] Using an existing study with name 'xgboost_optuna_full_ta_fold_2' instead of creating a new one.
[I 2026-07-08 19:53:27,924] Using an existing study with name 'xgboost_optuna_full_ta_fold_3' instead of creating a new one.
[I 2026-07-08 19:53:28,122] Using an existing study with name 'xgboost_optuna_full_ta_fold_4' instead of creating a new one.
[I 2026-07-08 19:53:28,244] Using an existing study with name 'lightgbm_optuna_full_ta_fold_1' instead of creating a new one.
[I 2026-07-08 19:53:28,444] Using an existing study with name 'lightgbm_optuna_full_ta_fold_2' instead of creating a new one.
[I 2026-07-08 19:53:28,761] Using an existing study with name 'lightgbm_optuna_full_ta_fold_3' instead of creating a new one.
[I 2026-07-08 19:53:28,935] Using an existing study with name 'lightgbm_optuna_full_ta_fold_4' instead of creating a new one.
[I 2026-07-08 19:53:29,126] Using an existing study with name 'lstm_optuna_full_ta_fold_1' instead of creating a new one.
[I 2026-07-08 19:53:29,227] Using an existing study with name 'lstm_optuna_full_ta_fold_2' instead of creating a new one.
[I 2026-07-08 19:53:29,333] Using an existing study with name 'lstm_optuna_full_ta_fold_3' instead of creating a new one.
[I 2026-07-08 19:53:29,449] Using an existing study with name 'lstm_optuna_full_ta_fold_4' instead of creating a new one.

,model,fold,completed_trials,target_trials,best_validation_rmse,best_params
0,ridge,fold_1,25,25,8.609983,{'alpha': 1413.9610114371485}
1,ridge,fold_2,25,25,6.799190,{'alpha': 297.81178047841695}
2,ridge,fold_3,25,25,7.430376,{'alpha': 208.90047049266641}
3,ridge,fold_4,25,25,6.728367,{'alpha': 12.401260870167759}
4,xgboost,fold_1,75,75,8.398640,"{'n_estimators': 428, 'max_depth': 5, 'learnin..."
5,xgboost,fold_2,75,75,6.751968,"{'n_estimators': 992, 'max_depth': 2, 'learnin..."
6,xgboost,fold_3,75,75,7.516914,"{'n_estimators': 823, 'max_depth': 4, 'learnin..."
7,xgboost,fold_4,75,75,6.902459,"{'n_estimators': 539, 'max_depth': 4, 'learnin..."
8,lightgbm,fold_1,75,75,8.511047,"{'n_estimators': 480, 'learning_rate': 0.00664..."
9,lightgbm,fold_2,75,75,6.842195,"{'n_estimators': 1086, 'learning_rate': 0.0094..."
10,lightgbm,fold_3,75,75,7.567988,"{'n_estimators': 735, 'learning_rate': 0.01895..."
11,lightgbm,fold_4,75,75,6.850011,"{'n_estimators': 260, 'learning_rate': 0.04217..."
12,lstm,fold_1,40,40,0.019291,"{'sequence_length': 5, 'batch_size': 16, 'lstm..."
13,lstm,fold_2,40,40,0.014507,"{'sequence_length': 40, 'batch_size': 16, 'lst..."
14,lstm,fold_3,40,40,0.016370,"{'sequence_length': 5, 'batch_size': 16, 'lstm..."
15,lstm,fold_4,40,40,0.014328,"{'sequence_length': 20, 'batch_size': 32, 'lst..."

# Tuned and Strong Model Experiments

Optuna minimizes validation RMSE independently inside each outer fold. After selection, each model is retrained on the complete outer training period and evaluated once on the untouched outer test year.

In [1]:
import sys
from pathlib import Path

project_root = Path.cwd()
if not (project_root / "models").exists():
    project_root = project_root.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))
project_root

WindowsPath('d:/SET50_direction_prediction_paper')

## Environment Check

Required packages are listed in `requirements-tuning.txt`. Install them in the notebook kernel environment before starting long-running cells.

In [2]:
from importlib.metadata import PackageNotFoundError, version

required_packages = [
    "optuna",
    "xgboost",
    "lightgbm",
    "tensorflow",
    "autogluon.tabular",
    "autogluon.timeseries",
    "chronos-forecasting",
    "torch",
]
package_status = {}
for package in required_packages:
    try:
        package_status[package] = version(package)
    except PackageNotFoundError:
        package_status[package] = "NOT INSTALLED"
package_status

{'optuna': '4.9.0',
 'xgboost': '3.1.3',
 'lightgbm': '4.6.0',
 'tensorflow': '2.21.0',
 'autogluon.tabular': '1.5.0',
 'autogluon.timeseries': '1.5.0',
 'chronos-forecasting': '2.2.2',
 'torch': '2.9.1'}

In [3]:
import subprocess

gpu_status = subprocess.run(
    ["nvidia-smi", "--query-gpu=name,memory.total,driver_version", "--format=csv,noheader"],
    capture_output=True,
    text=True,
    check=False,
)
print(gpu_status.stdout.strip() or gpu_status.stderr.strip())

NVIDIA-SMI has failed because you do not have sufficient permissions. Please try running as an administrator.

## Ridge Optuna Tuning

25 trials per fold. Search parameter: regularization strength `alpha`.

In [4]:
from models.tuned_strong_models import run_ridge_optuna

ridge_tuned_metrics = run_ridge_optuna()
ridge_tuned_metrics

ridge_optuna_full_ta:   0%|          | 0/4 [00:00<?, ?fold/s]

[I 2026-07-01 19:32:50,464] A new study created in RDB with name: ridge_optuna_full_ta_fold_1

  0%|          | 0/25 [00:00<?, ?it/s]

[I 2026-07-01 19:32:50,645] Trial 0 finished with value: 8.731962719460768 and parameters: {'alpha': 0.05564180225431373}. Best is trial 0 with value: 8.731962719460768.
[I 2026-07-01 19:32:50,772] Trial 1 finished with value: 12.920415105935652 and parameters: {'alpha': 32147.193482816965}. Best is trial 0 with value: 8.731962719460768.
[I 2026-07-01 19:32:50,878] Trial 2 finished with value: 8.664123544325586 and parameters: {'alpha': 208.90047049266641}. Best is trial 2 with value: 8.664123544325586.
[I 2026-07-01 19:32:50,988] Trial 3 finished with value: 8.720052703857585 and parameters: {'alpha': 9.695826644515218}. Best is trial 2 with value: 8.664123544325586.
[I 2026-07-01 19:32:51,182] Trial 4 finished with value: 8.775210393928218 and parameters: {'alpha': 0.0003632339256943143}. Best is trial 2 with value: 8.664123544325586.
[I 2026-07-01 19:32:51,270] Trial 5 finished with value: 8.775210356898299 and parameters: {'alpha': 0.0003630322466779861}. Best is trial 2 with value: 8.664123544325586.
[I 2026-07-01 19:32:51,356] Trial 6 finished with value: 8.775077043535351 and parameters: {'alpha': 3.809220577048033e-05}. Best is trial 2 with value: 8.664123544325586.
[I 2026-07-01 19:32:51,449] Trial 7 finished with value: 8.747531186291615 and parameters: {'alpha': 4589.458612326462}. Best is trial 2 with value: 8.664123544325586.
[I 2026-07-01 19:32:51,540] Trial 8 finished with value: 8.72043632288443 and parameters: {'alpha': 10.260065124896771}. Best is trial 2 with value: 8.664123544325586.
[I 2026-07-01 19:32:51,637] Trial 9 finished with value: 8.685120434765784 and parameters: {'alpha': 120.4275297251682}. Best is trial 2 with value: 8.664123544325586.
[I 2026-07-01 19:32:51,744] Trial 10 finished with value: 8.734224405519116 and parameters: {'alpha': 0.04806406218089304}. Best is trial 2 with value: 8.664123544325586.
[I 2026-07-01 19:32:51,844] Trial 11 finished with value: 8.65223798232852 and parameters: {'alpha': 291.2122460901281}. Best is trial 11 with value: 8.65223798232852.
[I 2026-07-01 19:32:51,932] Trial 12 finished with value: 8.695387782566058 and parameters: {'alpha': 91.4488047562377}. Best is trial 11 with value: 8.65223798232852.
[I 2026-07-01 19:32:52,034] Trial 13 finished with value: 8.61889775441083 and parameters: {'alpha': 838.1223962756644}. Best is trial 13 with value: 8.61889775441083.
[I 2026-07-01 19:32:52,122] Trial 14 finished with value: 8.690552332969583 and parameters: {'alpha': 3766.8362870314063}. Best is trial 13 with value: 8.61889775441083.
[I 2026-07-01 19:32:52,243] Trial 15 finished with value: 8.725525130135024 and parameters: {'alpha': 0.09180489802364734}. Best is trial 13 with value: 8.61889775441083.
[I 2026-07-01 19:32:52,345] Trial 16 finished with value: 16.221964222132886 and parameters: {'alpha': 55888.192835198366}. Best is trial 13 with value: 8.61889775441083.
[I 2026-07-01 19:32:52,438] Trial 17 finished with value: 8.713228686538748 and parameters: {'alpha': 2.5260803108643115}. Best is trial 13 with value: 8.61889775441083.
[I 2026-07-01 19:32:52,540] Trial 18 finished with value: 8.609982916526663 and parameters: {'alpha': 1413.9610114371485}. Best is trial 18 with value: 8.609982916526663.
[I 2026-07-01 19:32:52,638] Trial 19 finished with value: 8.712835035905295 and parameters: {'alpha': 1.84467793897455}. Best is trial 18 with value: 8.609982916526663.
[I 2026-07-01 19:32:52,736] Trial 20 finished with value: 8.620405728702504 and parameters: {'alpha': 2214.0415250621245}. Best is trial 18 with value: 8.609982916526663.
[I 2026-07-01 19:32:52,825] Trial 21 finished with value: 8.61016964045263 and parameters: {'alpha': 1557.8594975751546}. Best is trial 18 with value: 8.609982916526663.
[I 2026-07-01 19:32:52,960] Trial 22 finished with value: 8.610910575881087 and parameters: {'alpha': 1241.681082282494}. Best is trial 18 with value: 8.609982916526663.
[I 2026-07-01 19:32:53,052] Trial 23 finished with value: 11.830147677503554 and parameters: {'alpha': 25455.888920185782}. Best is trial 18 with value: 8.609982916526663.
[I 2026-07-01 19:32:53,156] Trial 24 finished with value: 9.29664470371805 and parameters: {'alpha': 9653.343850205076}. Best is trial 18 with value: 8.609982916526663.

[I 2026-07-01 19:32:53,687] A new study created in RDB with name: ridge_optuna_full_ta_fold_2

  0%|          | 0/25 [00:00<?, ?it/s]

[I 2026-07-01 19:32:53,827] Trial 0 finished with value: 7.027655539909449 and parameters: {'alpha': 0.05564180225431373}. Best is trial 0 with value: 7.027655539909449.
[I 2026-07-01 19:32:53,920] Trial 1 finished with value: 9.215099356938417 and parameters: {'alpha': 32147.193482816965}. Best is trial 0 with value: 7.027655539909449.
[I 2026-07-01 19:32:54,010] Trial 2 finished with value: 6.8050640530262125 and parameters: {'alpha': 208.90047049266641}. Best is trial 2 with value: 6.8050640530262125.
[I 2026-07-01 19:32:54,116] Trial 3 finished with value: 6.858849687986347 and parameters: {'alpha': 9.695826644515218}. Best is trial 2 with value: 6.8050640530262125.
[I 2026-07-01 19:32:54,204] Trial 4 finished with value: 7.09227815025611 and parameters: {'alpha': 0.0003632339256943143}. Best is trial 2 with value: 6.8050640530262125.
[I 2026-07-01 19:32:54,328] Trial 5 finished with value: 7.092279663539956 and parameters: {'alpha': 0.0003630322466779861}. Best is trial 2 with value: 6.8050640530262125.
[I 2026-07-01 19:32:54,423] Trial 6 finished with value: 7.094870225351175 and parameters: {'alpha': 3.809220577048033e-05}. Best is trial 2 with value: 6.8050640530262125.
[I 2026-07-01 19:32:54,517] Trial 7 finished with value: 6.954573434177402 and parameters: {'alpha': 4589.458612326462}. Best is trial 2 with value: 6.8050640530262125.
[I 2026-07-01 19:32:54,612] Trial 8 finished with value: 6.857644446963666 and parameters: {'alpha': 10.260065124896771}. Best is trial 2 with value: 6.8050640530262125.
[I 2026-07-01 19:32:54,701] Trial 9 finished with value: 6.817801091460519 and parameters: {'alpha': 120.4275297251682}. Best is trial 2 with value: 6.8050640530262125.
[I 2026-07-01 19:32:54,795] Trial 10 finished with value: 7.030907632965837 and parameters: {'alpha': 0.04806406218089304}. Best is trial 2 with value: 6.8050640530262125.
[I 2026-07-01 19:32:54,888] Trial 11 finished with value: 6.799469789921075 and parameters: {'alpha': 291.2122460901281}. Best is trial 11 with value: 6.799469789921075.
[I 2026-07-01 19:32:54,984] Trial 12 finished with value: 6.824416527853307 and parameters: {'alpha': 91.4488047562377}. Best is trial 11 with value: 6.799469789921075.
[I 2026-07-01 19:32:55,078] Trial 13 finished with value: 6.807676286537353 and parameters: {'alpha': 838.1223962756644}. Best is trial 11 with value: 6.799469789921075.
[I 2026-07-01 19:32:55,182] Trial 14 finished with value: 6.954770841935883 and parameters: {'alpha': 0.582022338311495}. Best is trial 11 with value: 6.799469789921075.
[I 2026-07-01 19:32:55,289] Trial 15 finished with value: 7.356728612794218 and parameters: {'alpha': 11930.206277066374}. Best is trial 11 with value: 6.799469789921075.
[I 2026-07-01 19:32:55,414] Trial 16 finished with value: 6.8018450941860635 and parameters: {'alpha': 676.4858339725733}. Best is trial 11 with value: 6.799469789921075.
[I 2026-07-01 19:32:55,508] Trial 17 finished with value: 6.911102354191328 and parameters: {'alpha': 2.1443213503668637}. Best is trial 11 with value: 6.799469789921075.
[I 2026-07-01 19:32:55,597] Trial 18 finished with value: 6.873725362326899 and parameters: {'alpha': 2425.418106082782}. Best is trial 11 with value: 6.799469789921075.
[I 2026-07-01 19:32:55,696] Trial 19 finished with value: 13.392509836549916 and parameters: {'alpha': 88847.54001426269}. Best is trial 11 with value: 6.799469789921075.
[I 2026-07-01 19:32:55,802] Trial 20 finished with value: 6.8476820607688715 and parameters: {'alpha': 20.579333853189702}. Best is trial 11 with value: 6.799469789921075.
[I 2026-07-01 19:32:55,907] Trial 21 finished with value: 6.799190080170967 and parameters: {'alpha': 297.81178047841695}. Best is trial 21 with value: 6.799190080170967.
[I 2026-07-01 19:32:56,006] Trial 22 finished with value: 6.79984321971653 and parameters: {'alpha': 608.9135992561912}. Best is trial 21 with value: 6.799190080170967.
[I 2026-07-01 19:32:56,096] Trial 23 finished with value: 6.833187188141216 and parameters: {'alpha': 60.793807708773464}. Best is trial 21 with value: 6.799190080170967.
[I 2026-07-01 19:32:56,197] Trial 24 finished with value: 6.800520629327509 and parameters: {'alpha': 633.1294807579376}. Best is trial 21 with value: 6.799190080170967.

[I 2026-07-01 19:32:56,742] A new study created in RDB with name: ridge_optuna_full_ta_fold_3

  0%|          | 0/25 [00:00<?, ?it/s]

[I 2026-07-01 19:32:56,866] Trial 0 finished with value: 7.927392774220243 and parameters: {'alpha': 0.05564180225431373}. Best is trial 0 with value: 7.927392774220243.
[I 2026-07-01 19:32:56,961] Trial 1 finished with value: 21.065797386008608 and parameters: {'alpha': 32147.193482816965}. Best is trial 0 with value: 7.927392774220243.
[I 2026-07-01 19:32:57,052] Trial 2 finished with value: 7.430375547602571 and parameters: {'alpha': 208.90047049266641}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:57,148] Trial 3 finished with value: 7.561295182308447 and parameters: {'alpha': 9.695826644515218}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:57,236] Trial 4 finished with value: 7.970574839197893 and parameters: {'alpha': 0.0003632339256943143}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:57,339] Trial 5 finished with value: 7.970576505991779 and parameters: {'alpha': 0.0003630322466779861}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:57,433] Trial 6 finished with value: 7.973447353128274 and parameters: {'alpha': 3.809220577048033e-05}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:57,523] Trial 7 finished with value: 8.619478935350312 and parameters: {'alpha': 4589.458612326462}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:57,611] Trial 8 finished with value: 7.555502472134284 and parameters: {'alpha': 10.260065124896771}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:57,709] Trial 9 finished with value: 7.430988572473669 and parameters: {'alpha': 120.4275297251682}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:57,805] Trial 10 finished with value: 7.92890819829108 and parameters: {'alpha': 0.04806406218089304}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:57,906] Trial 11 finished with value: 7.436616487318709 and parameters: {'alpha': 291.2122460901281}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:58,002] Trial 12 finished with value: 7.435076521733261 and parameters: {'alpha': 91.4488047562377}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:58,103] Trial 13 finished with value: 7.8511861907619105 and parameters: {'alpha': 0.5495199822865302}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:58,195] Trial 14 finished with value: 7.5881984650098815 and parameters: {'alpha': 1222.973946815166}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:58,307] Trial 15 finished with value: 7.540497947029557 and parameters: {'alpha': 11.950757124971531}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:58,407] Trial 16 finished with value: 24.733621201132806 and parameters: {'alpha': 42392.52375238047}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:58,496] Trial 17 finished with value: 7.852250247598403 and parameters: {'alpha': 0.5410713265729158}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:58,582] Trial 18 finished with value: 7.82997364806465 and parameters: {'alpha': 2239.6111095438723}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:58,678] Trial 19 finished with value: 7.441629196553663 and parameters: {'alpha': 68.20548483477297}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:58,774] Trial 20 finished with value: 7.901615798916021 and parameters: {'alpha': 0.20549453383586616}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:58,881] Trial 21 finished with value: 7.434639135092808 and parameters: {'alpha': 93.661041634441}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:58,981] Trial 22 finished with value: 7.4593541396151934 and parameters: {'alpha': 478.2189218675946}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:59,089] Trial 23 finished with value: 7.677766782653288 and parameters: {'alpha': 3.4517959680165347}. Best is trial 2 with value: 7.430375547602571.
[I 2026-07-01 19:32:59,192] Trial 24 finished with value: 7.452372370087111 and parameters: {'alpha': 48.04083862933049}. Best is trial 2 with value: 7.430375547602571.

[I 2026-07-01 19:32:59,772] A new study created in RDB with name: ridge_optuna_full_ta_fold_4

  0%|          | 0/25 [00:00<?, ?it/s]

[I 2026-07-01 19:32:59,884] Trial 0 finished with value: 6.8184472357392885 and parameters: {'alpha': 0.05564180225431373}. Best is trial 0 with value: 6.8184472357392885.
[I 2026-07-01 19:32:59,977] Trial 1 finished with value: 35.9457349763996 and parameters: {'alpha': 32147.193482816965}. Best is trial 0 with value: 6.8184472357392885.
[I 2026-07-01 19:33:00,223] Trial 2 finished with value: 6.822246984385129 and parameters: {'alpha': 208.90047049266641}. Best is trial 0 with value: 6.8184472357392885.
[I 2026-07-01 19:33:00,325] Trial 3 finished with value: 6.729059191313902 and parameters: {'alpha': 9.695826644515218}. Best is trial 3 with value: 6.729059191313902.
[I 2026-07-01 19:33:00,426] Trial 4 finished with value: 6.824796564119174 and parameters: {'alpha': 0.0003632339256943143}. Best is trial 3 with value: 6.729059191313902.
[I 2026-07-01 19:33:00,519] Trial 5 finished with value: 6.8247960639741025 and parameters: {'alpha': 0.0003630322466779861}. Best is trial 3 with value: 6.729059191313902.
[I 2026-07-01 19:33:00,617] Trial 6 finished with value: 6.823960013238752 and parameters: {'alpha': 3.809220577048033e-05}. Best is trial 3 with value: 6.729059191313902.
[I 2026-07-01 19:33:00,706] Trial 7 finished with value: 10.574592160325585 and parameters: {'alpha': 4589.458612326462}. Best is trial 3 with value: 6.729059191313902.
[I 2026-07-01 19:33:00,805] Trial 8 finished with value: 6.7288023768245075 and parameters: {'alpha': 10.260065124896771}. Best is trial 8 with value: 6.7288023768245075.
[I 2026-07-01 19:33:00,896] Trial 9 finished with value: 6.785612613067628 and parameters: {'alpha': 120.4275297251682}. Best is trial 8 with value: 6.7288023768245075.
[I 2026-07-01 19:33:00,990] Trial 10 finished with value: 6.7748262428077055 and parameters: {'alpha': 0.5722733938719496}. Best is trial 8 with value: 6.7288023768245075.
[I 2026-07-01 19:33:01,082] Trial 11 finished with value: 6.7634527108577664 and parameters: {'alpha': 1.014219735042056}. Best is trial 8 with value: 6.7288023768245075.
[I 2026-07-01 19:33:01,175] Trial 12 finished with value: 6.730268676029931 and parameters: {'alpha': 8.052447908601415}. Best is trial 8 with value: 6.7288023768245075.
[I 2026-07-01 19:33:01,266] Trial 13 finished with value: 6.82709236771445 and parameters: {'alpha': 0.02941094060248024}. Best is trial 8 with value: 6.7288023768245075.
[I 2026-07-01 19:33:01,390] Trial 14 finished with value: 6.753740770488144 and parameters: {'alpha': 56.5222593796093}. Best is trial 8 with value: 6.7288023768245075.
[I 2026-07-01 19:33:01,484] Trial 15 finished with value: 7.266649080695655 and parameters: {'alpha': 1051.9586808463719}. Best is trial 8 with value: 6.7288023768245075.
[I 2026-07-01 19:33:01,573] Trial 16 finished with value: 6.743374614099429 and parameters: {'alpha': 2.9694656866629208}. Best is trial 8 with value: 6.7288023768245075.
[I 2026-07-01 19:33:01,666] Trial 17 finished with value: 6.815227122935569 and parameters: {'alpha': 0.06760632817056818}. Best is trial 8 with value: 6.7288023768245075.
[I 2026-07-01 19:33:01,763] Trial 18 finished with value: 6.729927020835852 and parameters: {'alpha': 18.57104956337619}. Best is trial 8 with value: 6.7288023768245075.
[I 2026-07-01 19:33:01,862] Trial 19 finished with value: 57.2021661558311 and parameters: {'alpha': 72277.25501637236}. Best is trial 8 with value: 6.7288023768245075.
[I 2026-07-01 19:33:01,968] Trial 20 finished with value: 6.832150663376266 and parameters: {'alpha': 0.006421101609733929}. Best is trial 8 with value: 6.7288023768245075.
[I 2026-07-01 19:33:02,062] Trial 21 finished with value: 6.728761688220658 and parameters: {'alpha': 15.427571276761356}. Best is trial 21 with value: 6.728761688220658.
[I 2026-07-01 19:33:02,153] Trial 22 finished with value: 7.208172089116573 and parameters: {'alpha': 960.9859992137536}. Best is trial 21 with value: 6.728761688220658.
[I 2026-07-01 19:33:02,240] Trial 23 finished with value: 6.782690047265013 and parameters: {'alpha': 0.3833159492299753}. Best is trial 21 with value: 6.728761688220658.
[I 2026-07-01 19:33:02,340] Trial 24 finished with value: 6.7283667810424035 and parameters: {'alpha': 12.401260870167759}. Best is trial 24 with value: 6.7283667810424035.
     fold  train_start_year  train_end_year  test_year  n_train  n_test  \
0  fold_1              2012            2021       2022     2359     241
1  fold_2              2012            2022       2023     2600     243
2  fold_3              2012            2023       2024     2843     244
3  fold_4              2012            2024       2025     3087     234

       rmse       mae      mape        r2  direction_accuracy
0  6.832267  5.154153  0.524746  0.905764            0.531120
1  7.437263  5.682989  0.613615  0.972061            0.539095
2  6.822247  5.168111  0.597694  0.975999            0.487705
3  9.949317  7.710557  0.977834  0.961788            0.452991
      train_start_year  train_end_year  test_year  n_train  n_test      rmse  \
mean            2012.0          2022.5     2023.5  2722.25   240.5  7.760273

           mae      mape        r2  direction_accuracy
mean  5.928952  0.678472  0.953903            0.502728

,fold,train_start_year,train_end_year,test_year,n_train,n_test,rmse,mae,mape,r2,direction_accuracy
0,fold_1,2012,2021,2022,2359,241,6.832267,5.154153,0.524746,0.905764,0.531120
1,fold_2,2012,2022,2023,2600,243,7.437263,5.682989,0.613615,0.972061,0.539095
2,fold_3,2012,2023,2024,2843,244,6.822247,5.168111,0.597694,0.975999,0.487705
3,fold_4,2012,2024,2025,3087,234,9.949317,7.710557,0.977834,0.961788,0.452991

## XGBoost Optuna Tuning

75 trials per fold. CUDA is used when available.

In [5]:
from models.tuned_strong_models import run_xgboost_optuna

xgboost_tuned_metrics = run_xgboost_optuna()
xgboost_tuned_metrics

xgboost_optuna_full_ta:   0%|          | 0/4 [00:00<?, ?fold/s]

[I 2026-07-01 19:33:44,697] A new study created in RDB with name: xgboost_optuna_full_ta_fold_1

  0%|          | 0/75 [00:00<?, ?it/s]

d:\conda_envs\my_env\Lib\site-packages\xgboost\core.py:774: UserWarning: [19:33:49] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\common\error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

[I 2026-07-01 19:33:49,791] Trial 0 finished with value: 9.380061063127517 and parameters: {'n_estimators': 574, 'max_depth': 10, 'learning_rate': 0.1001303991139125, 'min_child_weight': 4.550475813202184, 'subsample': 0.5780093202212182, 'colsample_bytree': 0.5779972601681014, 'gamma': 0.2904180608409973, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 1.0129197956845732}. Best is trial 0 with value: 9.380061063127517.
[I 2026-07-01 19:33:51,931] Trial 1 finished with value: 12.343358950335153 and parameters: {'n_estimators': 908, 'max_depth': 2, 'learning_rate': 0.2652261985899886, 'min_child_weight': 10.779361932748845, 'subsample': 0.6061695553391381, 'colsample_bytree': 0.5909124836035503, 'gamma': 0.9170225492671691, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.4205156450913872}. Best is trial 0 with value: 9.380061063127517.
[I 2026-07-01 19:33:54,293] Trial 2 finished with value: 9.523171969499666 and parameters: {'n_estimators': 632, 'max_depth': 4, 'learning_rate': 0.061226156060280326, 'min_child_weight': 0.8364645453054501, 'subsample': 0.6460723242676091, 'colsample_bytree': 0.6831809216468459, 'gamma': 2.28034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 0.009962513222055111}. Best is trial 0 with value: 9.380061063127517.
[I 2026-07-01 19:33:58,847] Trial 3 finished with value: 9.101497247525261 and parameters: {'n_estimators': 714, 'max_depth': 7, 'learning_rate': 0.006047360568422396, 'min_child_weight': 4.702115628087815, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.5325257964926398, 'gamma': 4.7444276862666666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 11.015056790269638}. Best is trial 3 with value: 9.101497247525261.
[I 2026-07-01 19:34:00,211] Trial 4 finished with value: 9.728302840363376 and parameters: {'n_estimators': 504, 'max_depth': 2, 'learning_rate': 0.08234548958371457, 'min_child_weight': 2.5358333235759627, 'subsample': 0.5610191174223894, 'colsample_bytree': 0.7475884550556351, 'gamma': 0.17194260557609198, 'reg_alpha': 1.527156759251193, 'reg_lambda': 0.01967432802530612}. Best is trial 3 with value: 9.101497247525261.
[I 2026-07-01 19:34:04,140] Trial 5 finished with value: 10.72053614559233 and parameters: {'n_estimators': 863, 'max_depth': 4, 'learning_rate': 0.04204647637909148, 'min_child_weight': 3.7569262495760847, 'subsample': 0.5924272277627636, 'colsample_bytree': 0.9847923138822793, 'gamma': 3.8756641168055728, 'reg_alpha': 2.854239907497756, 'reg_lambda': 29.79454462591363}. Best is trial 3 with value: 9.101497247525261.
[I 2026-07-01 19:34:14,816] Trial 6 finished with value: 9.117629780768574 and parameters: {'n_estimators': 798, 'max_depth': 10, 'learning_rate': 0.007183284336890004, 'min_child_weight': 1.0302587393796305, 'subsample': 0.522613644455269, 'colsample_bytree': 0.6626651653816322, 'gamma': 1.9433864484474102, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 13.921548533046511}. Best is trial 3 with value: 9.101497247525261.
[I 2026-07-01 19:34:17,160] Trial 7 finished with value: 9.322441837178804 and parameters: {'n_estimators': 557, 'max_depth': 4, 'learning_rate': 0.04612811663739071, 'min_child_weight': 0.8408897660399112, 'subsample': 0.9010984903770198, 'colsample_bytree': 0.5372753218398854, 'gamma': 4.9344346830025865, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 0.009853225172032555}. Best is trial 3 with value: 9.101497247525261.
[I 2026-07-01 19:34:19,152] Trial 8 finished with value: 10.664752696539635 and parameters: {'n_estimators': 205, 'max_depth': 9, 'learning_rate': 0.09033775094656361, 'min_child_weight': 7.360091638366141, 'subsample': 0.8856351733429728, 'colsample_bytree': 0.5370223258670452, 'gamma': 1.7923286427213632, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 20.67840939783948}. Best is trial 3 with value: 9.101497247525261.
[I 2026-07-01 19:34:23,070] Trial 9 finished with value: 8.671440420705032 and parameters: {'n_estimators': 823, 'max_depth': 4, 'learning_rate': 0.006486140685631152, 'min_child_weight': 1.5746438450976663, 'subsample': 0.6625916610133735, 'colsample_bytree': 0.864803089169032, 'gamma': 3.1877873567760657, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.22965432344634354}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:34:31,270] Trial 10 finished with value: 9.288112509001792 and parameters: {'n_estimators': 1164, 'max_depth': 7, 'learning_rate': 0.015830790224020345, 'min_child_weight': 15.579555455108666, 'subsample': 0.7512656088373982, 'colsample_bytree': 0.9538323976412588, 'gamma': 3.2718826138537653, 'reg_alpha': 0.0024423918600740835, 'reg_lambda': 0.1656695387324379}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:34:40,707] Trial 11 finished with value: 8.960031968956244 and parameters: {'n_estimators': 1045, 'max_depth': 7, 'learning_rate': 0.005109880845334098, 'min_child_weight': 1.9159660348114993, 'subsample': 0.7171781358782057, 'colsample_bytree': 0.8579328744354449, 'gamma': 4.777833521699495, 'reg_alpha': 0.0029151336209232823, 'reg_lambda': 2.357862873220599}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:34:48,056] Trial 12 finished with value: 9.023077327394871 and parameters: {'n_estimators': 1087, 'max_depth': 6, 'learning_rate': 0.01195712441236456, 'min_child_weight': 1.789748976993378, 'subsample': 0.7343526094439211, 'colsample_bytree': 0.8608706114175635, 'gamma': 3.5058129769688, 'reg_alpha': 0.0018527674778937963, 'reg_lambda': 1.6725318583125008}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:34:55,448] Trial 13 finished with value: 8.752145543513283 and parameters: {'n_estimators': 1045, 'max_depth': 6, 'learning_rate': 0.005039406273871471, 'min_child_weight': 1.5549380477823986, 'subsample': 0.7208113026588052, 'colsample_bytree': 0.8557430599301392, 'gamma': 4.216638442959629, 'reg_alpha': 0.0036809798722255076, 'reg_lambda': 0.05371562810295912}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:35:00,557] Trial 14 finished with value: 9.072725501294917 and parameters: {'n_estimators': 980, 'max_depth': 5, 'learning_rate': 0.013222518847259147, 'min_child_weight': 0.5113971621640844, 'subsample': 0.8155421717694825, 'colsample_bytree': 0.8396779355177069, 'gamma': 2.7939929152165717, 'reg_alpha': 0.00010780599423065493, 'reg_lambda': 0.09365590826992008}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:35:06,941] Trial 15 finished with value: 8.982512946005405 and parameters: {'n_estimators': 1167, 'max_depth': 5, 'learning_rate': 0.009717986515245663, 'min_child_weight': 1.3350766334879278, 'subsample': 0.675760829066606, 'colsample_bytree': 0.7848922692513441, 'gamma': 4.004492247562731, 'reg_alpha': 0.027885209248099938, 'reg_lambda': 0.05112401734783215}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:35:09,852] Trial 16 finished with value: 9.1839906326993 and parameters: {'n_estimators': 765, 'max_depth': 3, 'learning_rate': 0.020522771581775935, 'min_child_weight': 2.607468899533685, 'subsample': 0.8146643330149077, 'colsample_bytree': 0.9155722000942043, 'gamma': 4.0245873297506085, 'reg_alpha': 0.0002960787945196745, 'reg_lambda': 0.0011638474835594268}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:35:12,750] Trial 17 finished with value: 9.047532102090411 and parameters: {'n_estimators': 413, 'max_depth': 6, 'learning_rate': 0.02336359525718101, 'min_child_weight': 1.4234390521300333, 'subsample': 0.809476885510991, 'colsample_bytree': 0.7700475100567968, 'gamma': 2.8568899027550896, 'reg_alpha': 0.019739460482056076, 'reg_lambda': 0.0021524630470829303}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:35:24,566] Trial 18 finished with value: 9.081272935188673 and parameters: {'n_estimators': 930, 'max_depth': 8, 'learning_rate': 0.008786372215463998, 'min_child_weight': 0.5014567831254724, 'subsample': 0.6571436469988812, 'colsample_bytree': 0.908508076347945, 'gamma': 4.394633076826618, 'reg_alpha': 0.00014021547203370562, 'reg_lambda': 0.3762091556844333}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:35:29,689] Trial 19 finished with value: 8.703824237536729 and parameters: {'n_estimators': 1018, 'max_depth': 5, 'learning_rate': 0.005281673048638902, 'min_child_weight': 2.5899314255453576, 'subsample': 0.779358645516251, 'colsample_bytree': 0.8117021488717808, 'gamma': 3.200379619741564, 'reg_alpha': 0.36193325705675233, 'reg_lambda': 0.03825680925171312}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:35:32,404] Trial 20 finished with value: 9.60499309505178 and parameters: {'n_estimators': 828, 'max_depth': 3, 'learning_rate': 0.024767056563560336, 'min_child_weight': 3.0662324621506376, 'subsample': 0.9958198527952287, 'colsample_bytree': 0.7141009015079719, 'gamma': 2.5723267048285834, 'reg_alpha': 0.16599332831551902, 'reg_lambda': 93.15666345772182}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:35:37,881] Trial 21 finished with value: 8.673176510415567 and parameters: {'n_estimators': 1012, 'max_depth': 5, 'learning_rate': 0.005132812842851337, 'min_child_weight': 1.9780906062234958, 'subsample': 0.771824172562406, 'colsample_bytree': 0.8311929291734549, 'gamma': 3.313085136372165, 'reg_alpha': 0.5744749898150787, 'reg_lambda': 0.03000267128620192}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:35:43,088] Trial 22 finished with value: 8.798025046857402 and parameters: {'n_estimators': 1003, 'max_depth': 5, 'learning_rate': 0.007865026168414542, 'min_child_weight': 2.1987263285607006, 'subsample': 0.7771588090549383, 'colsample_bytree': 0.8039454079283234, 'gamma': 3.337115151370236, 'reg_alpha': 9.489175007246127, 'reg_lambda': 0.0045797459343696525}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:35:46,453] Trial 23 finished with value: 8.76451810700512 and parameters: {'n_estimators': 928, 'max_depth': 3, 'learning_rate': 0.007657622991715856, 'min_child_weight': 6.065364613240845, 'subsample': 0.8789363275533767, 'colsample_bytree': 0.9032177566214208, 'gamma': 3.5912253743535523, 'reg_alpha': 0.46942301193546454, 'reg_lambda': 0.025022216968297678}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:35:50,335] Trial 24 finished with value: 8.93342777325051 and parameters: {'n_estimators': 735, 'max_depth': 5, 'learning_rate': 0.010612697121504774, 'min_child_weight': 3.3164522169393433, 'subsample': 0.6845443828375603, 'colsample_bytree': 0.8211338116630438, 'gamma': 3.0616687768107425, 'reg_alpha': 0.025960892340613263, 'reg_lambda': 0.1810609599187398}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:35:54,724] Trial 25 finished with value: 8.824648701995272 and parameters: {'n_estimators': 1101, 'max_depth': 4, 'learning_rate': 0.006211409149876071, 'min_child_weight': 1.0736921212576156, 'subsample': 0.8424238972424427, 'colsample_bytree': 0.7390135402481219, 'gamma': 2.390310897251647, 'reg_alpha': 0.5880160832453654, 'reg_lambda': 0.02939590346464855}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:35:59,465] Trial 26 finished with value: 9.17638325183014 and parameters: {'n_estimators': 664, 'max_depth': 6, 'learning_rate': 0.0160085461767639, 'min_child_weight': 2.003872724563707, 'subsample': 0.9644934500307779, 'colsample_bytree': 0.8918741570519853, 'gamma': 1.5038640789792566, 'reg_alpha': 1.1345212524980195, 'reg_lambda': 0.5073959367246588}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:36:02,303] Trial 27 finished with value: 8.741854304461862 and parameters: {'n_estimators': 873, 'max_depth': 3, 'learning_rate': 0.005067652131975515, 'min_child_weight': 1.1985748148269306, 'subsample': 0.7677142813206916, 'colsample_bytree': 0.9437616144357179, 'gamma': 3.6983874430868697, 'reg_alpha': 0.1871975571600339, 'reg_lambda': 3.8266240132474336}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:36:08,444] Trial 28 finished with value: 8.914899125664213 and parameters: {'n_estimators': 1186, 'max_depth': 5, 'learning_rate': 0.0093295388105825, 'min_child_weight': 0.6462094309622604, 'subsample': 0.6317102760420492, 'colsample_bytree': 0.8005772391942022, 'gamma': 3.0183007131937405, 'reg_alpha': 0.016241956073132516, 'reg_lambda': 0.12414430559090116}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:36:11,577] Trial 29 finished with value: 10.268759661441747 and parameters: {'n_estimators': 1019, 'max_depth': 4, 'learning_rate': 0.13993290849369094, 'min_child_weight': 4.419366231494832, 'subsample': 0.6946077127898997, 'colsample_bytree': 0.619720671481651, 'gamma': 1.1932109890671132, 'reg_alpha': 1.2391844377699314e-08, 'reg_lambda': 0.0067950900811704065}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:36:22,348] Trial 30 finished with value: 9.173755192551024 and parameters: {'n_estimators': 967, 'max_depth': 8, 'learning_rate': 0.006749685468952947, 'min_child_weight': 5.4783091640336945, 'subsample': 0.9268782005699934, 'colsample_bytree': 0.8801557098136691, 'gamma': 0.6155467087603381, 'reg_alpha': 0.5585510784849872, 'reg_lambda': 0.6667540717085929}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:36:25,195] Trial 31 finished with value: 8.76707450420021 and parameters: {'n_estimators': 873, 'max_depth': 3, 'learning_rate': 0.005346993288916206, 'min_child_weight': 1.1255847207977776, 'subsample': 0.7705302411901308, 'colsample_bytree': 0.938448633926205, 'gamma': 3.777605757008194, 'reg_alpha': 0.1182947216679962, 'reg_lambda': 4.391101384218202}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:36:27,504] Trial 32 finished with value: 9.074795146363666 and parameters: {'n_estimators': 848, 'max_depth': 2, 'learning_rate': 0.007044246395279517, 'min_child_weight': 1.5282748447684806, 'subsample': 0.7763241769856039, 'colsample_bytree': 0.9990512033561189, 'gamma': 3.1563673093501787, 'reg_alpha': 0.3458129430437799, 'reg_lambda': 0.2965402265203235}. Best is trial 9 with value: 8.671440420705032.
[I 2026-07-01 19:36:31,941] Trial 33 finished with value: 8.651901952875795 and parameters: {'n_estimators': 914, 'max_depth': 4, 'learning_rate': 0.005175022293605179, 'min_child_weight': 2.5652827646574208, 'subsample': 0.7970335114556181, 'colsample_bytree': 0.9529518526060405, 'gamma': 3.5661754960695444, 'reg_alpha': 2.7028237190592455, 'reg_lambda': 1.1241365046126996}. Best is trial 33 with value: 8.651901952875795.
[I 2026-07-01 19:36:36,985] Trial 34 finished with value: 9.184308159054389 and parameters: {'n_estimators': 1109, 'max_depth': 4, 'learning_rate': 0.012270073728898353, 'min_child_weight': 2.6115335289184167, 'subsample': 0.8466743730518109, 'colsample_bytree': 0.9661230074006846, 'gamma': 2.598514535253359, 'reg_alpha': 3.4506320595269075, 'reg_lambda': 1.1086541419250342}. Best is trial 33 with value: 8.651901952875795.
[I 2026-07-01 19:36:41,822] Trial 35 finished with value: 8.870820453844688 and parameters: {'n_estimators': 908, 'max_depth': 5, 'learning_rate': 0.008765845056763371, 'min_child_weight': 3.3290082256725206, 'subsample': 0.8479434027188816, 'colsample_bytree': 0.8326776197738572, 'gamma': 4.392182564389242, 'reg_alpha': 8.042984858026857, 'reg_lambda': 0.06305788293017378}. Best is trial 33 with value: 8.651901952875795.
[I 2026-07-01 19:36:44,323] Trial 36 finished with value: 10.231417774441434 and parameters: {'n_estimators': 781, 'max_depth': 4, 'learning_rate': 0.27623779509575347, 'min_child_weight': 2.3538728723878584, 'subsample': 0.543258470309539, 'colsample_bytree': 0.7472845590813537, 'gamma': 2.087124905867131, 'reg_alpha': 1.8807674959612053, 'reg_lambda': 0.015507858646441657}. Best is trial 33 with value: 8.651901952875795.
[I 2026-07-01 19:36:46,104] Trial 37 finished with value: 8.823895536124867 and parameters: {'n_estimators': 648, 'max_depth': 2, 'learning_rate': 0.006162284091557856, 'min_child_weight': 8.48416523235812, 'subsample': 0.625796303597987, 'colsample_bytree': 0.9261216792331299, 'gamma': 3.3564455652604512, 'reg_alpha': 0.05887348284933271, 'reg_lambda': 0.28749493140451704}. Best is trial 33 with value: 8.651901952875795.
[I 2026-07-01 19:36:48,920] Trial 38 finished with value: 9.584390191157741 and parameters: {'n_estimators': 951, 'max_depth': 6, 'learning_rate': 0.19283326176665574, 'min_child_weight': 3.9967840468035507, 'subsample': 0.7972829453773929, 'colsample_bytree': 0.8716154513313225, 'gamma': 2.85124803408521, 'reg_alpha': 1.330575526915595, 'reg_lambda': 1.0006952720081062}. Best is trial 33 with value: 8.651901952875795.
[I 2026-07-01 19:36:51,990] Trial 39 finished with value: 8.564975689531556 and parameters: {'n_estimators': 705, 'max_depth': 4, 'learning_rate': 0.006455891937745624, 'min_child_weight': 0.8476046927651357, 'subsample': 0.7115054012333606, 'colsample_bytree': 0.6954989472812381, 'gamma': 2.4366150394143156, 'reg_alpha': 2.883068566778499, 'reg_lambda': 0.03743503473662536}. Best is trial 39 with value: 8.564975689531556.
[I 2026-07-01 19:36:54,799] Trial 40 finished with value: 8.88342183629908 and parameters: {'n_estimators': 571, 'max_depth': 4, 'learning_rate': 0.016059429195728645, 'min_child_weight': 0.9093892597034287, 'subsample': 0.7384730851755565, 'colsample_bytree': 0.6546122837461907, 'gamma': 2.2365207119178425, 'reg_alpha': 3.4213566994277635, 'reg_lambda': 0.013243093356054097}. Best is trial 39 with value: 8.564975689531556.
[I 2026-07-01 19:36:58,491] Trial 41 finished with value: 8.678795186603567 and parameters: {'n_estimators': 720, 'max_depth': 5, 'learning_rate': 0.006407593825507013, 'min_child_weight': 1.748267492386709, 'subsample': 0.7068259749229441, 'colsample_bytree': 0.5985192986714627, 'gamma': 2.5442568939973627, 'reg_alpha': 1.251184825448983, 'reg_lambda': 0.034585230751577586}. Best is trial 39 with value: 8.564975689531556.
[I 2026-07-01 19:37:01,560] Trial 42 finished with value: 8.59278217946631 and parameters: {'n_estimators': 716, 'max_depth': 4, 'learning_rate': 0.006572716703650363, 'min_child_weight': 0.6841023015962611, 'subsample': 0.7095431692108982, 'colsample_bytree': 0.575353495523956, 'gamma': 1.7681943521341423, 'reg_alpha': 1.4953731333950397, 'reg_lambda': 0.004359580539660202}. Best is trial 39 with value: 8.564975689531556.
[I 2026-07-01 19:37:03,954] Trial 43 finished with value: 8.521748653673919 and parameters: {'n_estimators': 503, 'max_depth': 4, 'learning_rate': 0.008154612102256965, 'min_child_weight': 0.6927453842542848, 'subsample': 0.6564041059172372, 'colsample_bytree': 0.6959905515223715, 'gamma': 1.7611464660919993, 'reg_alpha': 4.688014491215473, 'reg_lambda': 0.0038326332554407035}. Best is trial 43 with value: 8.521748653673919.
[I 2026-07-01 19:37:05,790] Trial 44 finished with value: 8.823779720841397 and parameters: {'n_estimators': 447, 'max_depth': 3, 'learning_rate': 0.010467127635351316, 'min_child_weight': 0.6710189034653284, 'subsample': 0.6127799345467737, 'colsample_bytree': 0.5110933638525751, 'gamma': 1.7735611462980398, 'reg_alpha': 5.055335864009125, 'reg_lambda': 0.0038168557905976248}. Best is trial 43 with value: 8.521748653673919.
[I 2026-07-01 19:37:07,325] Trial 45 finished with value: 9.088561209053074 and parameters: {'n_estimators': 256, 'max_depth': 4, 'learning_rate': 0.00801487806726567, 'min_child_weight': 0.7019343403661823, 'subsample': 0.6627383328643943, 'colsample_bytree': 0.5785305452661514, 'gamma': 1.4193145072489832, 'reg_alpha': 2.4085187823730227, 'reg_lambda': 0.0011192874120960733}. Best is trial 43 with value: 8.521748653673919.

[I 2026-07-01 19:38:15,823] A new study created in RDB with name: xgboost_optuna_full_ta_fold_2

  0%|          | 0/75 [00:00<?, ?it/s]

[I 2026-07-01 19:38:20,555] Trial 0 finished with value: 7.80916392014646 and parameters: {'n_estimators': 574, 'max_depth': 10, 'learning_rate': 0.1001303991139125, 'min_child_weight': 4.550475813202184, 'subsample': 0.5780093202212182, 'colsample_bytree': 0.5779972601681014, 'gamma': 0.2904180608409973, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 1.0129197956845732}. Best is trial 0 with value: 7.80916392014646.
[I 2026-07-01 19:38:22,997] Trial 1 finished with value: 9.29062462894715 and parameters: {'n_estimators': 908, 'max_depth': 2, 'learning_rate': 0.2652261985899886, 'min_child_weight': 10.779361932748845, 'subsample': 0.6061695553391381, 'colsample_bytree': 0.5909124836035503, 'gamma': 0.9170225492671691, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.4205156450913872}. Best is trial 0 with value: 7.80916392014646.
[I 2026-07-01 19:38:26,172] Trial 2 finished with value: 7.201456214034448 and parameters: {'n_estimators': 632, 'max_depth': 4, 'learning_rate': 0.061226156060280326, 'min_child_weight': 0.8364645453054501, 'subsample': 0.6460723242676091, 'colsample_bytree': 0.6831809216468459, 'gamma': 2.28034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 0.009962513222055111}. Best is trial 2 with value: 7.201456214034448.
[I 2026-07-01 19:38:31,092] Trial 3 finished with value: 6.950486002524245 and parameters: {'n_estimators': 714, 'max_depth': 7, 'learning_rate': 0.006047360568422396, 'min_child_weight': 4.702115628087815, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.5325257964926398, 'gamma': 4.7444276862666666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 11.015056790269638}. Best is trial 3 with value: 6.950486002524245.
[I 2026-07-01 19:38:32,425] Trial 4 finished with value: 7.268595280757307 and parameters: {'n_estimators': 504, 'max_depth': 2, 'learning_rate': 0.08234548958371457, 'min_child_weight': 2.5358333235759627, 'subsample': 0.5610191174223894, 'colsample_bytree': 0.7475884550556351, 'gamma': 0.17194260557609198, 'reg_alpha': 1.527156759251193, 'reg_lambda': 0.01967432802530612}. Best is trial 3 with value: 6.950486002524245.
[I 2026-07-01 19:38:36,319] Trial 5 finished with value: 7.167764715443702 and parameters: {'n_estimators': 863, 'max_depth': 4, 'learning_rate': 0.04204647637909148, 'min_child_weight': 3.7569262495760847, 'subsample': 0.5924272277627636, 'colsample_bytree': 0.9847923138822793, 'gamma': 3.8756641168055728, 'reg_alpha': 2.854239907497756, 'reg_lambda': 29.79454462591363}. Best is trial 3 with value: 6.950486002524245.
[I 2026-07-01 19:38:47,476] Trial 6 finished with value: 7.342862178542207 and parameters: {'n_estimators': 798, 'max_depth': 10, 'learning_rate': 0.007183284336890004, 'min_child_weight': 1.0302587393796305, 'subsample': 0.522613644455269, 'colsample_bytree': 0.6626651653816322, 'gamma': 1.9433864484474102, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 13.921548533046511}. Best is trial 3 with value: 6.950486002524245.
[I 2026-07-01 19:38:49,793] Trial 7 finished with value: 6.95383703586226 and parameters: {'n_estimators': 557, 'max_depth': 4, 'learning_rate': 0.04612811663739071, 'min_child_weight': 0.8408897660399112, 'subsample': 0.9010984903770198, 'colsample_bytree': 0.5372753218398854, 'gamma': 4.9344346830025865, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 0.009853225172032555}. Best is trial 3 with value: 6.950486002524245.
[I 2026-07-01 19:38:51,978] Trial 8 finished with value: 7.5124746707100325 and parameters: {'n_estimators': 205, 'max_depth': 9, 'learning_rate': 0.09033775094656361, 'min_child_weight': 7.360091638366141, 'subsample': 0.8856351733429728, 'colsample_bytree': 0.5370223258670452, 'gamma': 1.7923286427213632, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 20.67840939783948}. Best is trial 3 with value: 6.950486002524245.
[I 2026-07-01 19:38:55,486] Trial 9 finished with value: 6.849295871090419 and parameters: {'n_estimators': 823, 'max_depth': 4, 'learning_rate': 0.006486140685631152, 'min_child_weight': 1.5746438450976663, 'subsample': 0.6625916610133735, 'colsample_bytree': 0.864803089169032, 'gamma': 3.1877873567760657, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.22965432344634354}. Best is trial 9 with value: 6.849295871090419.
[I 2026-07-01 19:39:03,725] Trial 10 finished with value: 7.359150921331861 and parameters: {'n_estimators': 1164, 'max_depth': 7, 'learning_rate': 0.015830790224020345, 'min_child_weight': 15.579555455108666, 'subsample': 0.7512656088373982, 'colsample_bytree': 0.9538323976412588, 'gamma': 3.2718826138537653, 'reg_alpha': 0.0024423918600740835, 'reg_lambda': 0.1656695387324379}. Best is trial 9 with value: 6.849295871090419.
[I 2026-07-01 19:39:12,998] Trial 11 finished with value: 7.023050030908704 and parameters: {'n_estimators': 1045, 'max_depth': 7, 'learning_rate': 0.005109880845334098, 'min_child_weight': 1.9159660348114993, 'subsample': 0.7171781358782057, 'colsample_bytree': 0.8579328744354449, 'gamma': 4.777833521699495, 'reg_alpha': 0.0029151336209232823, 'reg_lambda': 2.357862873220599}. Best is trial 9 with value: 6.849295871090419.
[I 2026-07-01 19:39:18,811] Trial 12 finished with value: 6.948685271998018 and parameters: {'n_estimators': 762, 'max_depth': 6, 'learning_rate': 0.011578825348262623, 'min_child_weight': 1.65908199198501, 'subsample': 0.7085862143808441, 'colsample_bytree': 0.8263406001124904, 'gamma': 3.6232964864289046, 'reg_alpha': 8.570867787439136, 'reg_lambda': 0.0012347885628072172}. Best is trial 9 with value: 6.849295871090419.
[I 2026-07-01 19:39:21,356] Trial 13 finished with value: 6.877451228686499 and parameters: {'n_estimators': 412, 'max_depth': 5, 'learning_rate': 0.013680134642940392, 'min_child_weight': 1.5223544787198957, 'subsample': 0.7824059188742476, 'colsample_bytree': 0.8557430599301392, 'gamma': 3.2608015042635263, 'reg_alpha': 0.01361891713383861, 'reg_lambda': 0.001461018509412001}. Best is trial 9 with value: 6.849295871090419.
[I 2026-07-01 19:39:23,584] Trial 14 finished with value: 7.003698466786376 and parameters: {'n_estimators': 357, 'max_depth': 5, 'learning_rate': 0.020128924894668044, 'min_child_weight': 0.5110348446891627, 'subsample': 0.8155421717694825, 'colsample_bytree': 0.8758067124078944, 'gamma': 2.7939929152165717, 'reg_alpha': 0.003379218926814622, 'reg_lambda': 0.0437011490614267}. Best is trial 9 with value: 6.849295871090419.
[I 2026-07-01 19:39:25,090] Trial 15 finished with value: 6.8399760074956175 and parameters: {'n_estimators': 388, 'max_depth': 3, 'learning_rate': 0.010567528926355714, 'min_child_weight': 1.3350766334879278, 'subsample': 0.8080498086746908, 'colsample_bytree': 0.7848922692513441, 'gamma': 4.013981822643023, 'reg_alpha': 0.00014939716674071141, 'reg_lambda': 0.002236636502758031}. Best is trial 15 with value: 6.8399760074956175.
[I 2026-07-01 19:39:26,100] Trial 16 finished with value: 6.888576061728561 and parameters: {'n_estimators': 204, 'max_depth': 3, 'learning_rate': 0.028604120257364567, 'min_child_weight': 0.5136345441926301, 'subsample': 0.830299622914229, 'colsample_bytree': 0.7782250877058381, 'gamma': 4.0245873297506085, 'reg_alpha': 0.00011439427584479787, 'reg_lambda': 0.12506540320219348}. Best is trial 15 with value: 6.8399760074956175.
[I 2026-07-01 19:39:27,483] Trial 17 finished with value: 7.079136511642985 and parameters: {'n_estimators': 337, 'max_depth': 3, 'learning_rate': 0.009452974541135192, 'min_child_weight': 2.6192662048461823, 'subsample': 0.6625401611346179, 'colsample_bytree': 0.9098854674455102, 'gamma': 2.7078510499787285, 'reg_alpha': 2.1219899323605756e-08, 'reg_lambda': 91.12671657530495}. Best is trial 15 with value: 6.8399760074956175.
[I 2026-07-01 19:39:31,093] Trial 18 finished with value: 6.825646203062278 and parameters: {'n_estimators': 996, 'max_depth': 3, 'learning_rate': 0.008786372215463998, 'min_child_weight': 1.0469717335131967, 'subsample': 0.852326249565989, 'colsample_bytree': 0.7655199095862766, 'gamma': 4.394633076826618, 'reg_alpha': 0.00014021547203370562, 'reg_lambda': 0.0032651946145554984}. Best is trial 18 with value: 6.825646203062278.
[I 2026-07-01 19:39:34,119] Trial 19 finished with value: 6.832050754671171 and parameters: {'n_estimators': 998, 'max_depth': 2, 'learning_rate': 0.024867798068911377, 'min_child_weight': 1.110125844340376, 'subsample': 0.9823003333934415, 'colsample_bytree': 0.7362817909111177, 'gamma': 4.309573595699013, 'reg_alpha': 0.000121044433366855, 'reg_lambda': 0.002675165321563707}. Best is trial 18 with value: 6.825646203062278.
[I 2026-07-01 19:39:37,287] Trial 20 finished with value: 6.751968384947134 and parameters: {'n_estimators': 992, 'max_depth': 2, 'learning_rate': 0.02103786318880531, 'min_child_weight': 0.7317790707101471, 'subsample': 0.9994443703759086, 'colsample_bytree': 0.6988401057436651, 'gamma': 4.338476509485872, 'reg_alpha': 6.63122810339199e-05, 'reg_lambda': 0.004322342827260152}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:39:40,497] Trial 21 finished with value: 6.8262208748704545 and parameters: {'n_estimators': 982, 'max_depth': 2, 'learning_rate': 0.023454015448043177, 'min_child_weight': 0.7998752508091396, 'subsample': 0.9958695625574902, 'colsample_bytree': 0.7208542774078666, 'gamma': 4.470290873755807, 'reg_alpha': 0.0001151505340164026, 'reg_lambda': 0.004398721369075085}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:39:44,517] Trial 22 finished with value: 6.874201893258546 and parameters: {'n_estimators': 1163, 'max_depth': 2, 'learning_rate': 0.029739936589605987, 'min_child_weight': 0.7020219134119152, 'subsample': 0.996840477950915, 'colsample_bytree': 0.6744646778782661, 'gamma': 4.5215959983285, 'reg_alpha': 9.267142102833255e-06, 'reg_lambda': 0.006610487300237312}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:39:48,467] Trial 23 finished with value: 6.824694616059612 and parameters: {'n_estimators': 991, 'max_depth': 3, 'learning_rate': 0.017371140492072844, 'min_child_weight': 0.6867441630509907, 'subsample': 0.9400131173613441, 'colsample_bytree': 0.7097105480736383, 'gamma': 4.381864421156704, 'reg_alpha': 0.0004117763870363463, 'reg_lambda': 0.04502914730151981}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:39:52,537] Trial 24 finished with value: 6.8645127551764205 and parameters: {'n_estimators': 1075, 'max_depth': 3, 'learning_rate': 0.01898195475501924, 'min_child_weight': 0.6895572434551204, 'subsample': 0.9307664006830646, 'colsample_bytree': 0.6346618383372634, 'gamma': 4.2294952342675876, 'reg_alpha': 4.946749478501033e-07, 'reg_lambda': 0.030957451508585462}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:39:57,493] Trial 25 finished with value: 6.964079591218539 and parameters: {'n_estimators': 957, 'max_depth': 5, 'learning_rate': 0.00860261787896508, 'min_child_weight': 1.0666238112917978, 'subsample': 0.9436366288341814, 'colsample_bytree': 0.7791785412186412, 'gamma': 3.647886954692309, 'reg_alpha': 0.0005897599579050948, 'reg_lambda': 0.051398624386615764}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:40:01,141] Trial 26 finished with value: 6.8300598895830005 and parameters: {'n_estimators': 1092, 'max_depth': 3, 'learning_rate': 0.013498971112282371, 'min_child_weight': 0.6140669684419113, 'subsample': 0.8654999282136744, 'colsample_bytree': 0.702814959146628, 'gamma': 4.93985787478735, 'reg_alpha': 1.4168932241859845e-05, 'reg_lambda': 0.016509296346682894}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:40:04,820] Trial 27 finished with value: 6.864582503112111 and parameters: {'n_estimators': 910, 'max_depth': 3, 'learning_rate': 0.03786934558599156, 'min_child_weight': 1.1574742589059503, 'subsample': 0.9483963288195918, 'colsample_bytree': 0.6231250484039309, 'gamma': 3.7089763014865795, 'reg_alpha': 3.309954293465795e-05, 'reg_lambda': 0.004029388069497717}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:40:09,846] Trial 28 finished with value: 6.945104521263567 and parameters: {'n_estimators': 1115, 'max_depth': 4, 'learning_rate': 0.018435589584377278, 'min_child_weight': 1.9294996331760281, 'subsample': 0.8565122554129694, 'colsample_bytree': 0.6323585999023397, 'gamma': 4.490343708786116, 'reg_alpha': 0.0006648812999028932, 'reg_lambda': 0.07345886784747464}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:40:12,804] Trial 29 finished with value: 7.449838385956665 and parameters: {'n_estimators': 1030, 'max_depth': 2, 'learning_rate': 0.13993290849369094, 'min_child_weight': 0.8830914629493141, 'subsample': 0.9242510089925007, 'colsample_bytree': 0.8177790854932094, 'gamma': 4.125312679262653, 'reg_alpha': 1.1614088660604218e-06, 'reg_lambda': 1.0027803698862348}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:40:16,790] Trial 30 finished with value: 6.983053660413029 and parameters: {'n_estimators': 702, 'max_depth': 5, 'learning_rate': 0.008408393546913794, 'min_child_weight': 0.6053000283913198, 'subsample': 0.9635334654231834, 'colsample_bytree': 0.5859368086055616, 'gamma': 0.6155467087603381, 'reg_alpha': 0.01866040548045072, 'reg_lambda': 0.02019397384696253}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:40:19,281] Trial 31 finished with value: 6.874959532038822 and parameters: {'n_estimators': 964, 'max_depth': 2, 'learning_rate': 0.024727758374776164, 'min_child_weight': 0.7787894618392073, 'subsample': 0.9946113828352804, 'colsample_bytree': 0.7384038821436233, 'gamma': 4.545898778870417, 'reg_alpha': 4.075536717711234e-05, 'reg_lambda': 0.004921288015145745}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:40:22,115] Trial 32 finished with value: 6.840387385952659 and parameters: {'n_estimators': 904, 'max_depth': 2, 'learning_rate': 0.03347079261135325, 'min_child_weight': 0.9603774625978775, 'subsample': 0.9057882136980698, 'colsample_bytree': 0.7122309235479091, 'gamma': 4.402251938580057, 'reg_alpha': 0.000547554798549327, 'reg_lambda': 0.0010133393473702125}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:40:26,090] Trial 33 finished with value: 6.931378092809146 and parameters: {'n_estimators': 964, 'max_depth': 3, 'learning_rate': 0.0599037579493992, 'min_child_weight': 1.2849251819737562, 'subsample': 0.9524732696067093, 'colsample_bytree': 0.7084069699940844, 'gamma': 4.69660303893741, 'reg_alpha': 4.091018664256667e-05, 'reg_lambda': 0.00708945850460345}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:40:28,812] Trial 34 finished with value: 6.820930859524097 and parameters: {'n_estimators': 875, 'max_depth': 2, 'learning_rate': 0.021824048963976914, 'min_child_weight': 0.6007839866910206, 'subsample': 0.9731894083507298, 'colsample_bytree': 0.7569145831385664, 'gamma': 3.523365642808515, 'reg_alpha': 0.0002699260774200968, 'reg_lambda': 0.0022975858961124876}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:40:33,126] Trial 35 finished with value: 6.830349749564087 and parameters: {'n_estimators': 872, 'max_depth': 4, 'learning_rate': 0.01470141775358836, 'min_child_weight': 0.6033393788641194, 'subsample': 0.8612160490814855, 'colsample_bytree': 0.7635822849573741, 'gamma': 3.39018081828511, 'reg_alpha': 0.0004335705152868118, 'reg_lambda': 0.0025733417513674585}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:40:35,330] Trial 36 finished with value: 8.03895238152296 and parameters: {'n_estimators': 660, 'max_depth': 3, 'learning_rate': 0.27623779509575347, 'min_child_weight': 0.6659429979248948, 'subsample': 0.9645782881206384, 'colsample_bytree': 0.8092445640713686, 'gamma': 3.0140511353553903, 'reg_alpha': 0.0071588448755818745, 'reg_lambda': 0.013854735001296272}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:40:38,936] Trial 37 finished with value: 6.962977767503376 and parameters: {'n_estimators': 1198, 'max_depth': 2, 'learning_rate': 0.04809108894971861, 'min_child_weight': 0.507552992528453, 'subsample': 0.9126066121793108, 'colsample_bytree': 0.6825545569415622, 'gamma': 3.685899151161478, 'reg_alpha': 4.575440155018308e-06, 'reg_lambda': 0.7739580465363548}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:40:42,390] Trial 38 finished with value: 7.8227187681384525 and parameters: {'n_estimators': 806, 'max_depth': 3, 'learning_rate': 0.19283326176665574, 'min_child_weight': 2.6274126083359213, 'subsample': 0.8916109497907683, 'colsample_bytree': 0.6597400480534246, 'gamma': 2.492046954135241, 'reg_alpha': 1.584346557706682e-05, 'reg_lambda': 0.009195493223331455}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:40:54,538] Trial 39 finished with value: 7.516596485618038 and parameters: {'n_estimators': 912, 'max_depth': 9, 'learning_rate': 0.012370176129111043, 'min_child_weight': 0.9260119818394454, 'subsample': 0.9683694397619776, 'colsample_bytree': 0.7477073149900386, 'gamma': 3.937250568776587, 'reg_alpha': 0.12951830341020376, 'reg_lambda': 3.151934470212685}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:40:58,419] Trial 40 finished with value: 6.884218747297357 and parameters: {'n_estimators': 1041, 'max_depth': 4, 'learning_rate': 0.018702555130485347, 'min_child_weight': 3.6156434516886136, 'subsample': 0.8410579164052963, 'colsample_bytree': 0.6095434443566702, 'gamma': 1.2112164780579597, 'reg_alpha': 0.0016849742328378771, 'reg_lambda': 0.3908573837705129}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:41:00,940] Trial 41 finished with value: 6.832916005717915 and parameters: {'n_estimators': 865, 'max_depth': 2, 'learning_rate': 0.023026893995674324, 'min_child_weight': 0.7808555412175631, 'subsample': 0.9985512203206109, 'colsample_bytree': 0.7166687096611501, 'gamma': 4.71689757492779, 'reg_alpha': 0.00023570517159856734, 'reg_lambda': 0.004051281110390363}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:41:04,001] Trial 42 finished with value: 6.766408884714214 and parameters: {'n_estimators': 989, 'max_depth': 2, 'learning_rate': 0.016242720450039005, 'min_child_weight': 0.8113815600256414, 'subsample': 0.9312827635469247, 'colsample_bytree': 0.650968850183454, 'gamma': 4.234862807761023, 'reg_alpha': 6.16018069407828e-05, 'reg_lambda': 0.0018916631328999628}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:41:07,365] Trial 43 finished with value: 6.871132732716801 and parameters: {'n_estimators': 1128, 'max_depth': 2, 'learning_rate': 0.007318202512487408, 'min_child_weight': 1.3275417563955612, 'subsample': 0.8823120491714104, 'colsample_bytree': 0.6521036528482818, 'gamma': 4.221638512195947, 'reg_alpha': 3.911828342222877e-05, 'reg_lambda': 0.0022657517981075413}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:41:10,923] Trial 44 finished with value: 6.8394949859782885 and parameters: {'n_estimators': 749, 'max_depth': 4, 'learning_rate': 0.016200779198192607, 'min_child_weight': 0.9962127933310465, 'subsample': 0.9270173893687419, 'colsample_bytree': 0.5667782698699653, 'gamma': 3.4855542869179907, 'reg_alpha': 2.5856588808963447e-06, 'reg_lambda': 0.0017194666278286571}. Best is trial 20 with value: 6.751968384947134.
[I 2026-07-01 19:41:14,785] Trial 45 finished with value: 6.787185324187276 and parameters: {'n_estimators': 1016, 'max_depth': 3, 'learning_rate': 0.010493136851728244, 'min_child_weight': 6.418995279013664, 'subsample': 0.9388304429745294, 'colsample_bytree': 0.7994305963581719, 'gamma': 3.844505199708305, 'reg_alpha': 0.0011556386185610104, 'reg_lambda': 0.028675295600411887}. Best is trial 20 with value: 6.751968384947134.

[I 2026-07-01 19:43:01,333] A new study created in RDB with name: xgboost_optuna_full_ta_fold_3

  0%|          | 0/75 [00:00<?, ?it/s]

[I 2026-07-01 19:43:05,543] Trial 0 finished with value: 8.450830976580518 and parameters: {'n_estimators': 574, 'max_depth': 10, 'learning_rate': 0.1001303991139125, 'min_child_weight': 4.550475813202184, 'subsample': 0.5780093202212182, 'colsample_bytree': 0.5779972601681014, 'gamma': 0.2904180608409973, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 1.0129197956845732}. Best is trial 0 with value: 8.450830976580518.
[I 2026-07-01 19:43:07,728] Trial 1 finished with value: 10.005590560900973 and parameters: {'n_estimators': 908, 'max_depth': 2, 'learning_rate': 0.2652261985899886, 'min_child_weight': 10.779361932748845, 'subsample': 0.6061695553391381, 'colsample_bytree': 0.5909124836035503, 'gamma': 0.9170225492671691, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.4205156450913872}. Best is trial 0 with value: 8.450830976580518.
[I 2026-07-01 19:43:10,569] Trial 2 finished with value: 8.226150791080585 and parameters: {'n_estimators': 632, 'max_depth': 4, 'learning_rate': 0.061226156060280326, 'min_child_weight': 0.8364645453054501, 'subsample': 0.6460723242676091, 'colsample_bytree': 0.6831809216468459, 'gamma': 2.28034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 0.009962513222055111}. Best is trial 2 with value: 8.226150791080585.
[I 2026-07-01 19:43:15,245] Trial 3 finished with value: 7.813492175349312 and parameters: {'n_estimators': 714, 'max_depth': 7, 'learning_rate': 0.006047360568422396, 'min_child_weight': 4.702115628087815, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.5325257964926398, 'gamma': 4.7444276862666666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 11.015056790269638}. Best is trial 3 with value: 7.813492175349312.
[I 2026-07-01 19:43:16,606] Trial 4 finished with value: 8.237816358605384 and parameters: {'n_estimators': 504, 'max_depth': 2, 'learning_rate': 0.08234548958371457, 'min_child_weight': 2.5358333235759627, 'subsample': 0.5610191174223894, 'colsample_bytree': 0.7475884550556351, 'gamma': 0.17194260557609198, 'reg_alpha': 1.527156759251193, 'reg_lambda': 0.01967432802530612}. Best is trial 3 with value: 7.813492175349312.
[I 2026-07-01 19:43:20,781] Trial 5 finished with value: 8.341322868691279 and parameters: {'n_estimators': 863, 'max_depth': 4, 'learning_rate': 0.04204647637909148, 'min_child_weight': 3.7569262495760847, 'subsample': 0.5924272277627636, 'colsample_bytree': 0.9847923138822793, 'gamma': 3.8756641168055728, 'reg_alpha': 2.854239907497756, 'reg_lambda': 29.79454462591363}. Best is trial 3 with value: 7.813492175349312.
[I 2026-07-01 19:43:31,911] Trial 6 finished with value: 8.107397272343443 and parameters: {'n_estimators': 798, 'max_depth': 10, 'learning_rate': 0.007183284336890004, 'min_child_weight': 1.0302587393796305, 'subsample': 0.522613644455269, 'colsample_bytree': 0.6626651653816322, 'gamma': 1.9433864484474102, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 13.921548533046511}. Best is trial 3 with value: 7.813492175349312.
[I 2026-07-01 19:43:34,060] Trial 7 finished with value: 7.903768325094071 and parameters: {'n_estimators': 557, 'max_depth': 4, 'learning_rate': 0.04612811663739071, 'min_child_weight': 0.8408897660399112, 'subsample': 0.9010984903770198, 'colsample_bytree': 0.5372753218398854, 'gamma': 4.9344346830025865, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 0.009853225172032555}. Best is trial 3 with value: 7.813492175349312.
[I 2026-07-01 19:43:36,137] Trial 8 finished with value: 8.35476395536698 and parameters: {'n_estimators': 205, 'max_depth': 9, 'learning_rate': 0.09033775094656361, 'min_child_weight': 7.360091638366141, 'subsample': 0.8856351733429728, 'colsample_bytree': 0.5370223258670452, 'gamma': 1.7923286427213632, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 20.67840939783948}. Best is trial 3 with value: 7.813492175349312.
[I 2026-07-01 19:43:39,784] Trial 9 finished with value: 7.516914197387735 and parameters: {'n_estimators': 823, 'max_depth': 4, 'learning_rate': 0.006486140685631152, 'min_child_weight': 1.5746438450976663, 'subsample': 0.6625916610133735, 'colsample_bytree': 0.864803089169032, 'gamma': 3.1877873567760657, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.22965432344634354}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:43:47,436] Trial 10 finished with value: 7.946736498982705 and parameters: {'n_estimators': 1164, 'max_depth': 7, 'learning_rate': 0.015830790224020345, 'min_child_weight': 15.579555455108666, 'subsample': 0.7512656088373982, 'colsample_bytree': 0.9538323976412588, 'gamma': 3.2718826138537653, 'reg_alpha': 0.0024423918600740835, 'reg_lambda': 0.1656695387324379}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:43:56,997] Trial 11 finished with value: 7.926097941482431 and parameters: {'n_estimators': 1045, 'max_depth': 7, 'learning_rate': 0.005109880845334098, 'min_child_weight': 1.9159660348114993, 'subsample': 0.7171781358782057, 'colsample_bytree': 0.8579328744354449, 'gamma': 4.777833521699495, 'reg_alpha': 0.0029151336209232823, 'reg_lambda': 2.357862873220599}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:44:02,381] Trial 12 finished with value: 7.9457663375856304 and parameters: {'n_estimators': 762, 'max_depth': 6, 'learning_rate': 0.011578825348262623, 'min_child_weight': 1.65908199198501, 'subsample': 0.7085862143808441, 'colsample_bytree': 0.8263406001124904, 'gamma': 3.6232964864289046, 'reg_alpha': 8.570867787439136, 'reg_lambda': 0.0012347885628072172}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:44:04,720] Trial 13 finished with value: 7.643926577142443 and parameters: {'n_estimators': 369, 'max_depth': 6, 'learning_rate': 0.016093687227246554, 'min_child_weight': 0.511537267554957, 'subsample': 0.7766688519794932, 'colsample_bytree': 0.8518658389033098, 'gamma': 2.8718022439661643, 'reg_alpha': 0.005741747046262285, 'reg_lambda': 91.12528527804946}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:44:06,699] Trial 14 finished with value: 7.79439626690596 and parameters: {'n_estimators': 357, 'max_depth': 5, 'learning_rate': 0.020128924894668044, 'min_child_weight': 0.503754859190744, 'subsample': 0.8155421717694825, 'colsample_bytree': 0.8758067124078944, 'gamma': 2.7939929152165717, 'reg_alpha': 0.003379218926814622, 'reg_lambda': 0.07531715625397115}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:44:08,787] Trial 15 finished with value: 7.858380600739837 and parameters: {'n_estimators': 385, 'max_depth': 5, 'learning_rate': 0.024465501052124243, 'min_child_weight': 0.5206853334788994, 'subsample': 0.8032489509434714, 'colsample_bytree': 0.7848922692513441, 'gamma': 2.7700391358623784, 'reg_alpha': 7.208888843674043e-05, 'reg_lambda': 76.97192144784917}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:44:09,749] Trial 16 finished with value: 10.867100055966256 and parameters: {'n_estimators': 204, 'max_depth': 3, 'learning_rate': 0.010591574671315652, 'min_child_weight': 1.1710058722136056, 'subsample': 0.6639926607342311, 'colsample_bytree': 0.9134303245024302, 'gamma': 4.0245873297506085, 'reg_alpha': 0.0348885376241305, 'reg_lambda': 4.054640243849923}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:44:12,636] Trial 17 finished with value: 8.094268120624488 and parameters: {'n_estimators': 410, 'max_depth': 6, 'learning_rate': 0.02913257772277018, 'min_child_weight': 1.5212490735021937, 'subsample': 0.8246904111944696, 'colsample_bytree': 0.7700475100567968, 'gamma': 1.2463851220732023, 'reg_alpha': 0.0003656967947521845, 'reg_lambda': 93.02106464786851}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:44:25,536] Trial 18 finished with value: 7.979546830486613 and parameters: {'n_estimators': 1002, 'max_depth': 8, 'learning_rate': 0.009460410287175982, 'min_child_weight': 2.728321253331494, 'subsample': 0.7652613300574083, 'colsample_bytree': 0.9134336554829187, 'gamma': 2.9760206718909297, 'reg_alpha': 0.026804688557122612, 'reg_lambda': 0.05655799475544226}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:44:31,412] Trial 19 finished with value: 8.017878590266884 and parameters: {'n_estimators': 1167, 'max_depth': 5, 'learning_rate': 0.014828763974618249, 'min_child_weight': 0.7106572041063226, 'subsample': 0.9611944497701141, 'colsample_bytree': 0.7231610042250181, 'gamma': 2.2959439814427505, 'reg_alpha': 0.000121044433366855, 'reg_lambda': 0.0016473484803774426}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:44:33,996] Trial 20 finished with value: 7.625325081177134 and parameters: {'n_estimators': 684, 'max_depth': 3, 'learning_rate': 0.008412114647331227, 'min_child_weight': 1.2972875947807778, 'subsample': 0.6654974298347499, 'colsample_bytree': 0.8199212859905153, 'gamma': 4.222568597552449, 'reg_alpha': 1.2722974438529106e-08, 'reg_lambda': 0.6918401513892531}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:44:36,674] Trial 21 finished with value: 7.640020380795125 and parameters: {'n_estimators': 684, 'max_depth': 3, 'learning_rate': 0.007807088520505956, 'min_child_weight': 1.2605524822884708, 'subsample': 0.6683739834077089, 'colsample_bytree': 0.8279171893877562, 'gamma': 4.413262167519133, 'reg_alpha': 1.4329321655479917e-08, 'reg_lambda': 0.651859753690966}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:44:39,368] Trial 22 finished with value: 7.592732810255439 and parameters: {'n_estimators': 670, 'max_depth': 3, 'learning_rate': 0.007924929322953864, 'min_child_weight': 1.2676788129654784, 'subsample': 0.6556193407120199, 'colsample_bytree': 0.8010053431898321, 'gamma': 4.2180055469705104, 'reg_alpha': 1.307532380729938e-08, 'reg_lambda': 0.4984008854789464}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:44:42,485] Trial 23 finished with value: 7.645724062448409 and parameters: {'n_estimators': 854, 'max_depth': 3, 'learning_rate': 0.005338228668284715, 'min_child_weight': 2.236845908838548, 'subsample': 0.7008588245279068, 'colsample_bytree': 0.8036385082964127, 'gamma': 4.299216353608927, 'reg_alpha': 1.0967320843655432e-08, 'reg_lambda': 0.24125120267074374}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:44:44,517] Trial 24 finished with value: 7.742075928540346 and parameters: {'n_estimators': 659, 'max_depth': 2, 'learning_rate': 0.008103106681876266, 'min_child_weight': 3.0119173935451085, 'subsample': 0.633005086052498, 'colsample_bytree': 0.706126381006446, 'gamma': 3.6080382920807597, 'reg_alpha': 1.9455477600332433e-07, 'reg_lambda': 1.8237654881012266}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:44:48,377] Trial 25 finished with value: 7.706838604952815 and parameters: {'n_estimators': 970, 'max_depth': 3, 'learning_rate': 0.011427799786488016, 'min_child_weight': 1.4426251072874507, 'subsample': 0.682405674558216, 'colsample_bytree': 0.9145942595193252, 'gamma': 4.409960815203558, 'reg_alpha': 2.7792377752018086e-07, 'reg_lambda': 0.0871048298454036}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:44:51,978] Trial 26 finished with value: 7.584675918145013 and parameters: {'n_estimators': 764, 'max_depth': 4, 'learning_rate': 0.006905347760152589, 'min_child_weight': 1.826850519068709, 'subsample': 0.6289687295950217, 'colsample_bytree': 0.8812829080304143, 'gamma': 3.5467233731775596, 'reg_alpha': 1.4553771641533966e-06, 'reg_lambda': 4.498684155633987}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:44:55,580] Trial 27 finished with value: 7.60723154289368 and parameters: {'n_estimators': 800, 'max_depth': 4, 'learning_rate': 0.006244095787973371, 'min_child_weight': 1.9352874489127603, 'subsample': 0.5006637414916141, 'colsample_bytree': 0.8884006002163152, 'gamma': 3.333605323324786, 'reg_alpha': 2.997518219536567e-06, 'reg_lambda': 3.8266240132474336}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:45:00,412] Trial 28 finished with value: 7.7437459089538425 and parameters: {'n_estimators': 912, 'max_depth': 5, 'learning_rate': 0.005015844640180852, 'min_child_weight': 3.514348090730483, 'subsample': 0.5392781153041017, 'colsample_bytree': 0.9466547727214727, 'gamma': 3.706320998323467, 'reg_alpha': 1.712538715175332e-05, 'reg_lambda': 7.318784564204365}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:45:02,857] Trial 29 finished with value: 7.59211709960686 and parameters: {'n_estimators': 560, 'max_depth': 4, 'learning_rate': 0.01304526910231753, 'min_child_weight': 4.661751877715331, 'subsample': 0.6170628253638976, 'colsample_bytree': 0.619720671481651, 'gamma': 3.2668230562767953, 'reg_alpha': 6.035562303707736e-08, 'reg_lambda': 1.4681322325993995}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:45:05,150] Trial 30 finished with value: 7.573402063526971 and parameters: {'n_estimators': 488, 'max_depth': 4, 'learning_rate': 0.012893207066941519, 'min_child_weight': 5.4783091640336945, 'subsample': 0.612674319238395, 'colsample_bytree': 0.5859368086055616, 'gamma': 3.2890290606384047, 'reg_alpha': 6.69452803548679e-07, 'reg_lambda': 1.233364705147805}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:45:07,516] Trial 31 finished with value: 7.560651674370526 and parameters: {'n_estimators': 482, 'max_depth': 4, 'learning_rate': 0.01265110205968065, 'min_child_weight': 6.344481212366147, 'subsample': 0.6244826810214156, 'colsample_bytree': 0.624239561162127, 'gamma': 3.3153788566833233, 'reg_alpha': 5.90946779262432e-07, 'reg_lambda': 1.0133753227983493}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:45:09,719] Trial 32 finished with value: 9.223838947352458 and parameters: {'n_estimators': 490, 'max_depth': 5, 'learning_rate': 0.22699486142340916, 'min_child_weight': 6.696132393680257, 'subsample': 0.5689494437170763, 'colsample_bytree': 0.6095521688236006, 'gamma': 3.1563673093501787, 'reg_alpha': 4.0591395567760927e-07, 'reg_lambda': 0.26866011558438724}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:45:11,390] Trial 33 finished with value: 7.568299296417898 and parameters: {'n_estimators': 309, 'max_depth': 4, 'learning_rate': 0.021472461183491023, 'min_child_weight': 7.0513053742312275, 'subsample': 0.6169949765605032, 'colsample_bytree': 0.5661703237692369, 'gamma': 2.2663676821427723, 'reg_alpha': 1.5546441261238122e-06, 'reg_lambda': 1.0514486214984966}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:45:12,795] Trial 34 finished with value: 7.574623853402924 and parameters: {'n_estimators': 269, 'max_depth': 4, 'learning_rate': 0.020565976879811994, 'min_child_weight': 7.469752153604802, 'subsample': 0.6078495692607643, 'colsample_bytree': 0.6454023540506905, 'gamma': 2.3737162564346797, 'reg_alpha': 1.0224671820589925e-05, 'reg_lambda': 1.0416448480822549}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:45:13,843] Trial 35 finished with value: 7.99815706145856 and parameters: {'n_estimators': 303, 'max_depth': 2, 'learning_rate': 0.03250625040916073, 'min_child_weight': 12.047447628036482, 'subsample': 0.5563801503869616, 'colsample_bytree': 0.5691986641997921, 'gamma': 1.0637590734219189, 'reg_alpha': 2.5420526507485438e-05, 'reg_lambda': 0.16314686626286495}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:45:16,662] Trial 36 finished with value: 7.804836682232381 and parameters: {'n_estimators': 489, 'max_depth': 5, 'learning_rate': 0.022260921413551477, 'min_child_weight': 5.769333467450566, 'subsample': 0.5910622282431419, 'colsample_bytree': 0.5118222212690977, 'gamma': 2.586796293843259, 'reg_alpha': 4.98747798960656e-07, 'reg_lambda': 1.0533401685521748}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:45:18,708] Trial 37 finished with value: 7.655148508299991 and parameters: {'n_estimators': 460, 'max_depth': 4, 'learning_rate': 0.016692010575108822, 'min_child_weight': 8.702183300047283, 'subsample': 0.7257565764695296, 'colsample_bytree': 0.56797568302968, 'gamma': 1.8138623923634725, 'reg_alpha': 0.6759193998482651, 'reg_lambda': 0.02357044639259633}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:45:20,811] Trial 38 finished with value: 7.915252833398769 and parameters: {'n_estimators': 308, 'max_depth': 6, 'learning_rate': 0.03740461718761297, 'min_child_weight': 10.271103712344468, 'subsample': 0.6389527952793327, 'colsample_bytree': 0.6442151886562446, 'gamma': 0.5363694715612566, 'reg_alpha': 1.0724260240424127e-06, 'reg_lambda': 0.35918184183310103}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:45:22,485] Trial 39 finished with value: 7.92285968108211 and parameters: {'n_estimators': 620, 'max_depth': 2, 'learning_rate': 0.05816064119334506, 'min_child_weight': 5.670184615029647, 'subsample': 0.5970495235232309, 'colsample_bytree': 0.5007590990665841, 'gamma': 1.562912656035334, 'reg_alpha': 6.845320095050072e-08, 'reg_lambda': 2.4139665033582145}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:45:24,675] Trial 40 finished with value: 8.032840650222386 and parameters: {'n_estimators': 445, 'max_depth': 4, 'learning_rate': 0.01325529105920384, 'min_child_weight': 19.22004055267775, 'subsample': 0.5397820813937683, 'colsample_bytree': 0.5953043204746159, 'gamma': 2.052075089917387, 'reg_alpha': 0.0003849991959951674, 'reg_lambda': 7.144830451012866}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:45:26,031] Trial 41 finished with value: 7.589699785096298 and parameters: {'n_estimators': 268, 'max_depth': 4, 'learning_rate': 0.019520379784141888, 'min_child_weight': 7.910854849973757, 'subsample': 0.6100325029239667, 'colsample_bytree': 0.6523106580872283, 'gamma': 2.3787003708121617, 'reg_alpha': 8.704770182774199e-06, 'reg_lambda': 0.9872671975096277}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:45:27,392] Trial 42 finished with value: 7.635802353469099 and parameters: {'n_estimators': 275, 'max_depth': 4, 'learning_rate': 0.02685147778103415, 'min_child_weight': 5.77673080965132, 'subsample': 0.5774435336498794, 'colsample_bytree': 0.5555517375745375, 'gamma': 2.561406049594082, 'reg_alpha': 8.307414470112102e-07, 'reg_lambda': 1.0165218757063537}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:45:29,633] Trial 43 finished with value: 7.716474303844063 and parameters: {'n_estimators': 609, 'max_depth': 3, 'learning_rate': 0.01795651871910328, 'min_child_weight': 3.883805619900721, 'subsample': 0.6088435881640019, 'colsample_bytree': 0.6766643899084799, 'gamma': 2.0891258410082143, 'reg_alpha': 6.8698987812628765e-06, 'reg_lambda': 0.13646951909773475}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:45:31,822] Trial 44 finished with value: 7.9345076424994145 and parameters: {'n_estimators': 332, 'max_depth': 5, 'learning_rate': 0.010044662137056013, 'min_child_weight': 10.489785155357172, 'subsample': 0.678026173393103, 'colsample_bytree': 0.6267059902392522, 'gamma': 3.0030460294480967, 'reg_alpha': 2.1550590507233918e-06, 'reg_lambda': 0.4493967007301031}. Best is trial 9 with value: 7.516914197387735.
[I 2026-07-01 19:45:34,127] Trial 45 finished with value: 8.89743423524839 and parameters: {'n_estimators': 529, 'max_depth': 4, 'learning_rate': 0.13232888780739155, 'min_child_weight': 13.190213468428578, 'subsample': 0.6428588266448736, 'colsample_bytree': 0.6954645856905681, 'gamma': 2.5937817962710668, 'reg_alpha': 3.7545410829191384e-08, 'reg_lambda': 0.03864783670643327}. Best is trial 9 with value: 7.516914197387735.

[I 2026-07-01 19:47:06,991] A new study created in RDB with name: xgboost_optuna_full_ta_fold_4

  0%|          | 0/75 [00:00<?, ?it/s]

[I 2026-07-01 19:47:11,119] Trial 0 finished with value: 8.195446368868721 and parameters: {'n_estimators': 574, 'max_depth': 10, 'learning_rate': 0.1001303991139125, 'min_child_weight': 4.550475813202184, 'subsample': 0.5780093202212182, 'colsample_bytree': 0.5779972601681014, 'gamma': 0.2904180608409973, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 1.0129197956845732}. Best is trial 0 with value: 8.195446368868721.
[I 2026-07-01 19:47:13,096] Trial 1 finished with value: 8.844600079550393 and parameters: {'n_estimators': 908, 'max_depth': 2, 'learning_rate': 0.2652261985899886, 'min_child_weight': 10.779361932748845, 'subsample': 0.6061695553391381, 'colsample_bytree': 0.5909124836035503, 'gamma': 0.9170225492671691, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.4205156450913872}. Best is trial 0 with value: 8.195446368868721.
[I 2026-07-01 19:47:15,693] Trial 2 finished with value: 7.394399144712565 and parameters: {'n_estimators': 632, 'max_depth': 4, 'learning_rate': 0.061226156060280326, 'min_child_weight': 0.8364645453054501, 'subsample': 0.6460723242676091, 'colsample_bytree': 0.6831809216468459, 'gamma': 2.28034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 0.009962513222055111}. Best is trial 2 with value: 7.394399144712565.
[I 2026-07-01 19:47:20,103] Trial 3 finished with value: 7.762639001097382 and parameters: {'n_estimators': 714, 'max_depth': 7, 'learning_rate': 0.006047360568422396, 'min_child_weight': 4.702115628087815, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.5325257964926398, 'gamma': 4.7444276862666666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 11.015056790269638}. Best is trial 2 with value: 7.394399144712565.
[I 2026-07-01 19:47:21,373] Trial 4 finished with value: 7.115524177102632 and parameters: {'n_estimators': 504, 'max_depth': 2, 'learning_rate': 0.08234548958371457, 'min_child_weight': 2.5358333235759627, 'subsample': 0.5610191174223894, 'colsample_bytree': 0.7475884550556351, 'gamma': 0.17194260557609198, 'reg_alpha': 1.527156759251193, 'reg_lambda': 0.01967432802530612}. Best is trial 4 with value: 7.115524177102632.
[I 2026-07-01 19:47:25,286] Trial 5 finished with value: 7.177343566346008 and parameters: {'n_estimators': 863, 'max_depth': 4, 'learning_rate': 0.04204647637909148, 'min_child_weight': 3.7569262495760847, 'subsample': 0.5924272277627636, 'colsample_bytree': 0.9847923138822793, 'gamma': 3.8756641168055728, 'reg_alpha': 2.854239907497756, 'reg_lambda': 29.79454462591363}. Best is trial 4 with value: 7.115524177102632.
[I 2026-07-01 19:47:36,299] Trial 6 finished with value: 8.225777502554651 and parameters: {'n_estimators': 798, 'max_depth': 10, 'learning_rate': 0.007183284336890004, 'min_child_weight': 1.0302587393796305, 'subsample': 0.522613644455269, 'colsample_bytree': 0.6626651653816322, 'gamma': 1.9433864484474102, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 13.921548533046511}. Best is trial 4 with value: 7.115524177102632.
[I 2026-07-01 19:47:38,411] Trial 7 finished with value: 7.205366030231258 and parameters: {'n_estimators': 557, 'max_depth': 4, 'learning_rate': 0.04612811663739071, 'min_child_weight': 0.8408897660399112, 'subsample': 0.9010984903770198, 'colsample_bytree': 0.5372753218398854, 'gamma': 4.9344346830025865, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 0.009853225172032555}. Best is trial 4 with value: 7.115524177102632.
[I 2026-07-01 19:47:40,344] Trial 8 finished with value: 8.048639689679435 and parameters: {'n_estimators': 205, 'max_depth': 9, 'learning_rate': 0.09033775094656361, 'min_child_weight': 7.360091638366141, 'subsample': 0.8856351733429728, 'colsample_bytree': 0.5370223258670452, 'gamma': 1.7923286427213632, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 20.67840939783948}. Best is trial 4 with value: 7.115524177102632.
[I 2026-07-01 19:47:43,464] Trial 9 finished with value: 7.0335821786082295 and parameters: {'n_estimators': 823, 'max_depth': 4, 'learning_rate': 0.006486140685631152, 'min_child_weight': 1.5746438450976663, 'subsample': 0.6625916610133735, 'colsample_bytree': 0.864803089169032, 'gamma': 3.1877873567760657, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.22965432344634354}. Best is trial 9 with value: 7.0335821786082295.
[I 2026-07-01 19:47:51,129] Trial 10 finished with value: 7.29679281429417 and parameters: {'n_estimators': 1164, 'max_depth': 7, 'learning_rate': 0.015830790224020345, 'min_child_weight': 15.579555455108666, 'subsample': 0.7512656088373982, 'colsample_bytree': 0.9538323976412588, 'gamma': 3.2718826138537653, 'reg_alpha': 0.0024423918600740835, 'reg_lambda': 0.1656695387324379}. Best is trial 9 with value: 7.0335821786082295.
[I 2026-07-01 19:47:52,072] Trial 11 finished with value: 7.213101241631981 and parameters: {'n_estimators': 333, 'max_depth': 2, 'learning_rate': 0.016988390752417776, 'min_child_weight': 1.9345641373017766, 'subsample': 0.7171781358782057, 'colsample_bytree': 0.865042426595599, 'gamma': 3.0976697156679958, 'reg_alpha': 0.0029151336209232823, 'reg_lambda': 0.0014318787415474796}. Best is trial 9 with value: 7.0335821786082295.
[I 2026-07-01 19:47:55,571] Trial 12 finished with value: 9.084491650142862 and parameters: {'n_estimators': 1083, 'max_depth': 3, 'learning_rate': 0.24609952545253133, 'min_child_weight': 1.7897489769933772, 'subsample': 0.7085862143808441, 'colsample_bytree': 0.8029060479129773, 'gamma': 0.331783207687125, 'reg_alpha': 0.005259187287243993, 'reg_lambda': 0.049222414140461655}. Best is trial 9 with value: 7.0335821786082295.
[I 2026-07-01 19:47:58,559] Trial 13 finished with value: 7.1698144700324145 and parameters: {'n_estimators': 427, 'max_depth': 6, 'learning_rate': 0.020412529691970792, 'min_child_weight': 2.079509274751508, 'subsample': 0.5048457916745841, 'colsample_bytree': 0.7916135769831637, 'gamma': 1.2077746649016994, 'reg_alpha': 9.270665989993134, 'reg_lambda': 1.9939973559342086}. Best is trial 9 with value: 7.0335821786082295.
[I 2026-07-01 19:48:03,237] Trial 14 finished with value: 7.2968179326203755 and parameters: {'n_estimators': 990, 'max_depth': 5, 'learning_rate': 0.010675539740206795, 'min_child_weight': 0.5116200618263806, 'subsample': 0.8155421717694825, 'colsample_bytree': 0.8758067124078944, 'gamma': 2.7939929152165717, 'reg_alpha': 0.02074121276327187, 'reg_lambda': 0.04020229935490061}. Best is trial 9 with value: 7.0335821786082295.
[I 2026-07-01 19:48:04,503] Trial 15 finished with value: 7.128390116379199 and parameters: {'n_estimators': 448, 'max_depth': 2, 'learning_rate': 0.031021068077262945, 'min_child_weight': 2.6809801186089133, 'subsample': 0.6599652767012881, 'colsample_bytree': 0.7449619156310756, 'gamma': 3.9860471738533216, 'reg_alpha': 0.35109824431470316, 'reg_lambda': 0.0019543640632528787}. Best is trial 9 with value: 7.0335821786082295.
[I 2026-07-01 19:48:06,984] Trial 16 finished with value: 7.987354112361509 and parameters: {'n_estimators': 713, 'max_depth': 3, 'learning_rate': 0.15552413914219654, 'min_child_weight': 1.31229244021801, 'subsample': 0.7812564285126707, 'colsample_bytree': 0.8754986180062628, 'gamma': 1.0903928528795857, 'reg_alpha': 3.154443500139828e-05, 'reg_lambda': 0.07396252743414343}. Best is trial 9 with value: 7.0335821786082295.
[I 2026-07-01 19:48:08,439] Trial 17 finished with value: 7.103180521248514 and parameters: {'n_estimators': 215, 'max_depth': 5, 'learning_rate': 0.029119809769165082, 'min_child_weight': 3.1975469447334177, 'subsample': 0.6610493336318682, 'colsample_bytree': 0.71804991678614, 'gamma': 4.0699685278891575, 'reg_alpha': 0.0005068082867108995, 'reg_lambda': 0.012768804397753008}. Best is trial 9 with value: 7.0335821786082295.
[I 2026-07-01 19:48:09,705] Trial 18 finished with value: 17.53513067457762 and parameters: {'n_estimators': 220, 'max_depth': 5, 'learning_rate': 0.009299147534336302, 'min_child_weight': 7.737863054055104, 'subsample': 0.6842752547579092, 'colsample_bytree': 0.67455198366465, 'gamma': 4.076917740388504, 'reg_alpha': 0.00022163473160045528, 'reg_lambda': 3.1572281696344}. Best is trial 9 with value: 7.0335821786082295.
[I 2026-07-01 19:48:16,527] Trial 19 finished with value: 7.855553516159483 and parameters: {'n_estimators': 998, 'max_depth': 7, 'learning_rate': 0.025819547167175626, 'min_child_weight': 0.586381630792708, 'subsample': 0.8386999498787029, 'colsample_bytree': 0.9394993688998952, 'gamma': 3.4100932050317856, 'reg_alpha': 9.082615315752126e-08, 'reg_lambda': 0.2685964113261066}. Best is trial 9 with value: 7.0335821786082295.
[I 2026-07-01 19:48:18,721] Trial 20 finished with value: 9.860165257116444 and parameters: {'n_estimators': 354, 'max_depth': 6, 'learning_rate': 0.011865229422384438, 'min_child_weight': 1.348100615522791, 'subsample': 0.9744327790037297, 'colsample_bytree': 0.8199212859905153, 'gamma': 4.330402796023959, 'reg_alpha': 0.0003529331338091357, 'reg_lambda': 93.15666345772182}. Best is trial 9 with value: 7.0335821786082295.
[I 2026-07-01 19:48:20,357] Trial 21 finished with value: 11.528595874825461 and parameters: {'n_estimators': 498, 'max_depth': 3, 'learning_rate': 0.005279632156609195, 'min_child_weight': 3.0419985255903548, 'subsample': 0.6299200133723348, 'colsample_bytree': 0.7489403392560089, 'gamma': 2.586440907951696, 'reg_alpha': 0.7024764367452779, 'reg_lambda': 0.012966124942462328}. Best is trial 9 with value: 7.0335821786082295.
[I 2026-07-01 19:48:22,081] Trial 22 finished with value: 8.051092363520102 and parameters: {'n_estimators': 315, 'max_depth': 5, 'learning_rate': 0.08635428516730403, 'min_child_weight': 3.1049054004623327, 'subsample': 0.5488201932052762, 'colsample_bytree': 0.716482159955777, 'gamma': 3.5031122233487473, 'reg_alpha': 0.02896980871584369, 'reg_lambda': 0.0045797459343696525}. Best is trial 9 with value: 7.0335821786082295.
[I 2026-07-01 19:48:24,181] Trial 23 finished with value: 7.815417930615766 and parameters: {'n_estimators': 691, 'max_depth': 3, 'learning_rate': 0.14815985392626935, 'min_child_weight': 5.814556626218352, 'subsample': 0.6705045437468625, 'colsample_bytree': 0.6351857952311887, 'gamma': 4.537723671591701, 'reg_alpha': 1.347551223319092e-08, 'reg_lambda': 0.02880598953827103}. Best is trial 9 with value: 7.0335821786082295.
[I 2026-07-01 19:48:25,583] Trial 24 finished with value: 7.018231200455038 and parameters: {'n_estimators': 278, 'max_depth': 4, 'learning_rate': 0.03546295783983467, 'min_child_weight': 2.526020460559234, 'subsample': 0.5555607844215953, 'colsample_bytree': 0.7541782700100692, 'gamma': 1.6711144661380948, 'reg_alpha': 1.5303154838985191, 'reg_lambda': 0.08701279440039189}. Best is trial 24 with value: 7.018231200455038.
[I 2026-07-01 19:48:27,323] Trial 25 finished with value: 7.241734585997712 and parameters: {'n_estimators': 262, 'max_depth': 5, 'learning_rate': 0.03324286646892189, 'min_child_weight': 1.516791720393329, 'subsample': 0.7359145089433057, 'colsample_bytree': 0.8367834601554789, 'gamma': 1.6145815102181853, 'reg_alpha': 0.00034562043028321974, 'reg_lambda': 0.1133285883103041}. Best is trial 24 with value: 7.018231200455038.
[I 2026-07-01 19:48:29,983] Trial 26 finished with value: 7.348532488650895 and parameters: {'n_estimators': 388, 'max_depth': 6, 'learning_rate': 0.051886582435529696, 'min_child_weight': 2.3570230526057743, 'subsample': 0.6252402909061714, 'colsample_bytree': 0.7787588257864038, 'gamma': 3.723424825122406, 'reg_alpha': 0.1465637136081893, 'reg_lambda': 0.574145264717879}. Best is trial 24 with value: 7.018231200455038.
[I 2026-07-01 19:48:31,178] Trial 27 finished with value: 7.008465321522413 and parameters: {'n_estimators': 277, 'max_depth': 4, 'learning_rate': 0.02421393261473757, 'min_child_weight': 3.9752754619642086, 'subsample': 0.6860776522846479, 'colsample_bytree': 0.7083050344726476, 'gamma': 2.8945659712959366, 'reg_alpha': 0.024437968253268202, 'reg_lambda': 0.004741482901937035}. Best is trial 27 with value: 7.008465321522413.
[I 2026-07-01 19:48:35,634] Trial 28 finished with value: 7.054722322162468 and parameters: {'n_estimators': 1186, 'max_depth': 4, 'learning_rate': 0.013993594532535245, 'min_child_weight': 4.556877352142795, 'subsample': 0.7578511180329484, 'colsample_bytree': 0.9232142374281717, 'gamma': 2.3178707820356927, 'reg_alpha': 0.02174380157676721, 'reg_lambda': 0.003004519024501129}. Best is trial 27 with value: 7.008465321522413.
[I 2026-07-01 19:48:37,996] Trial 29 finished with value: 6.902458635718016 and parameters: {'n_estimators': 539, 'max_depth': 4, 'learning_rate': 0.023070787483340877, 'min_child_weight': 3.771143873699412, 'subsample': 0.5540473668246815, 'colsample_bytree': 0.6124601099894081, 'gamma': 2.912493416550591, 'reg_alpha': 0.8045785191462241, 'reg_lambda': 1.0027803698862348}. Best is trial 29 with value: 6.902458635718016.
[I 2026-07-01 19:48:39,189] Trial 30 finished with value: 6.984960677861243 and parameters: {'n_estimators': 287, 'max_depth': 3, 'learning_rate': 0.02137540106854642, 'min_child_weight': 5.4783091640336945, 'subsample': 0.5403730674643185, 'colsample_bytree': 0.6140331328403313, 'gamma': 2.811284478232833, 'reg_alpha': 0.352896313444283, 'reg_lambda': 4.479032749107452}. Best is trial 29 with value: 6.902458635718016.
[I 2026-07-01 19:48:40,488] Trial 31 finished with value: 6.982783564182474 and parameters: {'n_estimators': 296, 'max_depth': 3, 'learning_rate': 0.019692550501078016, 'min_child_weight': 5.919953175406302, 'subsample': 0.5376933612917804, 'colsample_bytree': 0.6048015988570616, 'gamma': 2.810066546389542, 'reg_alpha': 0.46701873302377467, 'reg_lambda': 4.391101384218202}. Best is trial 29 with value: 6.902458635718016.
[I 2026-07-01 19:48:41,983] Trial 32 finished with value: 7.032004972414386 and parameters: {'n_estimators': 390, 'max_depth': 3, 'learning_rate': 0.021132592271781218, 'min_child_weight': 6.285993488021373, 'subsample': 0.5206094413254246, 'colsample_bytree': 0.5959496235234774, 'gamma': 2.8383304308005832, 'reg_alpha': 0.2758538766924873, 'reg_lambda': 3.1025299025891457}. Best is trial 29 with value: 6.902458635718016.
[I 2026-07-01 19:48:44,073] Trial 33 finished with value: 6.92591577319518 and parameters: {'n_estimators': 583, 'max_depth': 3, 'learning_rate': 0.02099166274690054, 'min_child_weight': 9.966043270980915, 'subsample': 0.5407269930228931, 'colsample_bytree': 0.6197503081571892, 'gamma': 2.2663676821427723, 'reg_alpha': 0.026740035955770517, 'reg_lambda': 1.0613924225507305}. Best is trial 29 with value: 6.902458635718016.
[I 2026-07-01 19:48:45,896] Trial 34 finished with value: 7.096509118965379 and parameters: {'n_estimators': 604, 'max_depth': 2, 'learning_rate': 0.018995900090441095, 'min_child_weight': 11.044993553588178, 'subsample': 0.6078495692607643, 'colsample_bytree': 0.6169923285430585, 'gamma': 2.3292349188456183, 'reg_alpha': 0.0732887556410021, 'reg_lambda': 1.0511903179110818}. Best is trial 29 with value: 6.902458635718016.
[I 2026-07-01 19:48:47,850] Trial 35 finished with value: 7.0223497114834945 and parameters: {'n_estimators': 528, 'max_depth': 3, 'learning_rate': 0.012149003097894394, 'min_child_weight': 10.215275877070326, 'subsample': 0.5407570841495385, 'colsample_bytree': 0.5691986641997921, 'gamma': 2.130511714173724, 'reg_alpha': 0.35382709158916503, 'reg_lambda': 6.518557115149653}. Best is trial 29 with value: 6.902458635718016.
[I 2026-07-01 19:48:49,762] Trial 36 finished with value: 7.4570258209007125 and parameters: {'n_estimators': 665, 'max_depth': 2, 'learning_rate': 0.008073202324602754, 'min_child_weight': 16.96317021033395, 'subsample': 0.5943521789646162, 'colsample_bytree': 0.6361340343391603, 'gamma': 2.6557095782590294, 'reg_alpha': 4.0492718493214115, 'reg_lambda': 1.0533401685521748}. Best is trial 29 with value: 6.902458635718016.
[I 2026-07-01 19:48:51,513] Trial 37 finished with value: 7.03620410940257 and parameters: {'n_estimators': 470, 'max_depth': 3, 'learning_rate': 0.040044026372822124, 'min_child_weight': 12.246855361074008, 'subsample': 0.5741271958890903, 'colsample_bytree': 0.56797568302968, 'gamma': 1.4118320914290947, 'reg_alpha': 1.2827766342110867, 'reg_lambda': 6.617627844700634}. Best is trial 29 with value: 6.902458635718016.
[I 2026-07-01 19:48:53,312] Trial 38 finished with value: 7.385008882433544 and parameters: {'n_estimators': 625, 'max_depth': 2, 'learning_rate': 0.06089900642026366, 'min_child_weight': 8.908323901271222, 'subsample': 0.5013330669467831, 'colsample_bytree': 0.5995042263066441, 'gamma': 2.524390092693877, 'reg_alpha': 0.006100459824998286, 'reg_lambda': 0.6098796200157848}. Best is trial 29 with value: 6.902458635718016.
[I 2026-07-01 19:48:58,637] Trial 39 finished with value: 7.2065549314772595 and parameters: {'n_estimators': 554, 'max_depth': 9, 'learning_rate': 0.014346273090285347, 'min_child_weight': 5.446687410768458, 'subsample': 0.5320821969949637, 'colsample_bytree': 0.5012190430813388, 'gamma': 1.9439063052923111, 'reg_alpha': 0.1631168191084241, 'reg_lambda': 1.8176991437744552}. Best is trial 29 with value: 6.902458635718016.
[I 2026-07-01 19:49:00,763] Trial 40 finished with value: 6.953105567124069 and parameters: {'n_estimators': 593, 'max_depth': 4, 'learning_rate': 0.01998163455619063, 'min_child_weight': 13.984557619063875, 'subsample': 0.5733376625671109, 'colsample_bytree': 0.6389357165196757, 'gamma': 3.018761698278461, 'reg_alpha': 3.250916967702957, 'reg_lambda': 6.448227909808319}. Best is trial 29 with value: 6.902458635718016.
[I 2026-07-01 19:49:03,623] Trial 41 finished with value: 7.012710622346372 and parameters: {'n_estimators': 788, 'max_depth': 4, 'learning_rate': 0.023388461398411862, 'min_child_weight': 13.299910606163921, 'subsample': 0.5650858024389095, 'colsample_bytree': 0.6429280413484691, 'gamma': 3.1181882725531525, 'reg_alpha': 3.1963161529301627, 'reg_lambda': 6.028380281745234}. Best is trial 29 with value: 6.902458635718016.
[I 2026-07-01 19:49:06,481] Trial 42 finished with value: 7.0934163288118395 and parameters: {'n_estimators': 765, 'max_depth': 3, 'learning_rate': 0.017195384233843796, 'min_child_weight': 7.754065882996021, 'subsample': 0.5876707327145563, 'colsample_bytree': 0.65904969699434, 'gamma': 3.6480300439441877, 'reg_alpha': 7.777199223177891, 'reg_lambda': 41.21032039177217}. Best is trial 29 with value: 6.902458635718016.
[I 2026-07-01 19:49:08,345] Trial 43 finished with value: 7.002228597640358 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.025725611534274145, 'min_child_weight': 14.701992688617679, 'subsample': 0.6088435881640019, 'colsample_bytree': 0.5599390280706729, 'gamma': 2.9732648227170912, 'reg_alpha': 0.043976857602336286, 'reg_lambda': 10.553106532697912}. Best is trial 29 with value: 6.902458635718016.
[I 2026-07-01 19:49:10,244] Trial 44 finished with value: 6.94993947464758 and parameters: {'n_estimators': 591, 'max_depth': 3, 'learning_rate': 0.01952259625419035, 'min_child_weight': 9.861387322290009, 'subsample': 0.5705960365775301, 'colsample_bytree': 0.6100110402976266, 'gamma': 2.1720467131674264, 'reg_alpha': 0.599653780443507, 'reg_lambda': 2.9233080962448272}. Best is trial 29 with value: 6.902458635718016.
[I 2026-07-01 19:49:12,760] Trial 45 finished with value: 6.943617963663955 and parameters: {'n_estimators': 589, 'max_depth': 4, 'learning_rate': 0.015003367365494583, 'min_child_weight': 19.62193201256898, 'subsample': 0.571545124979584, 'colsample_bytree': 0.6890775162036136, 'gamma': 2.0749878347339967, 'reg_alpha': 2.1612527123050786, 'reg_lambda': 1.9291048500167087}. Best is trial 29 with value: 6.902458635718016.

,fold,train_start_year,train_end_year,test_year,n_train,n_test,rmse,mae,mape,r2,direction_accuracy
0,fold_1,2012,2021,2022,2359,241,7.016455,5.492655,0.557547,0.900614,0.518672
1,fold_2,2012,2022,2023,2600,243,7.831251,6.001803,0.650402,0.969022,0.514403
2,fold_3,2012,2023,2024,2843,244,7.033582,5.272463,0.609621,0.974489,0.545082
3,fold_4,2012,2024,2025,3087,234,24.705970,17.230855,2.286194,0.764374,0.564103

## LightGBM Optuna Tuning

75 trials per fold. GPU is attempted first with a CPU fallback when the installed LightGBM build has no GPU support.

In [7]:
from models.tuned_strong_models import run_lightgbm_optuna

lightgbm_tuned_metrics = run_lightgbm_optuna()
lightgbm_tuned_metrics

lightgbm_optuna_full_ta:   0%|          | 0/4 [00:00<?, ?fold/s]

[I 2026-07-01 19:51:02,500] A new study created in RDB with name: lightgbm_optuna_full_ta_fold_1

  0%|          | 0/75 [00:00<?, ?it/s]

[I 2026-07-01 19:51:13,013] Trial 0 finished with value: 10.17972278713186 and parameters: {'n_estimators': 574, 'learning_rate': 0.1667521176194013, 'num_leaves': 191, 'max_depth': 11, 'min_child_samples': 19, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.5290418060840998, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 1.0129197956845732}. Best is trial 0 with value: 10.17972278713186.
[I 2026-07-01 19:51:36,137] Trial 1 finished with value: 9.105881179401539 and parameters: {'n_estimators': 908, 'learning_rate': 0.005394455304087533, 'num_leaves': 248, 'max_depth': 14, 'min_child_samples': 25, 'subsample': 0.5909124836035503, 'colsample_bytree': 0.5917022549267169, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.4205156450913872}. Best is trial 1 with value: 9.105881179401539.
[I 2026-07-01 19:51:38,833] Trial 2 finished with value: 9.015945712170497 and parameters: {'n_estimators': 632, 'learning_rate': 0.014639847680621753, 'num_leaves': 162, 'max_depth': 4, 'min_child_samples': 33, 'subsample': 0.6831809216468459, 'colsample_bytree': 0.728034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 0.009962513222055111}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:51:45,852] Trial 3 finished with value: 9.608224238098838 and parameters: {'n_estimators': 714, 'learning_rate': 0.04446862319918233, 'num_leaves': 26, 'max_depth': 11, 'min_child_samples': 21, 'subsample': 0.5325257964926398, 'colsample_bytree': 0.9744427686266666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 11.015056790269638}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:52:01,531] Trial 4 finished with value: 9.129600780045804 and parameters: {'n_estimators': 504, 'learning_rate': 0.0071688020821370525, 'num_leaves': 179, 'max_depth': 9, 'min_child_samples': 16, 'subsample': 0.7475884550556351, 'colsample_bytree': 0.5171942605576092, 'reg_alpha': 1.527156759251193, 'reg_lambda': 0.01967432802530612}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:52:11,931] Trial 5 finished with value: 9.383409777996553 and parameters: {'n_estimators': 863, 'learning_rate': 0.015788826347222458, 'num_leaves': 140, 'max_depth': 10, 'min_child_samples': 22, 'subsample': 0.9847923138822793, 'colsample_bytree': 0.8875664116805573, 'reg_alpha': 2.854239907497756, 'reg_lambda': 29.79454462591363}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:52:17,651] Trial 6 finished with value: 9.611397076962966 and parameters: {'n_estimators': 798, 'learning_rate': 0.14992285132527539, 'num_leaves': 36, 'max_depth': 5, 'min_child_samples': 9, 'subsample': 0.6626651653816322, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 13.921548533046511}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:52:19,815] Trial 7 finished with value: 9.752979342595813 and parameters: {'n_estimators': 557, 'learning_rate': 0.014094313993387368, 'num_leaves': 145, 'max_depth': 4, 'min_child_samples': 82, 'subsample': 0.5372753218398854, 'colsample_bytree': 0.9934434683002586, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 0.009853225172032555}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:52:21,756] Trial 8 finished with value: 10.250404871715828 and parameters: {'n_estimators': 205, 'learning_rate': 0.10124839170683374, 'num_leaves': 185, 'max_depth': 13, 'min_child_samples': 79, 'subsample': 0.5370223258670452, 'colsample_bytree': 0.6792328642721364, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 20.67840939783948}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:52:27,292] Trial 9 finished with value: 9.312546531341535 and parameters: {'n_estimators': 823, 'learning_rate': 0.01694683071232564, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 36, 'subsample': 0.864803089169032, 'colsample_bytree': 0.8187787356776066, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.22965432344634354}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:52:38,878] Trial 10 finished with value: 10.490018654659393 and parameters: {'n_estimators': 1153, 'learning_rate': 0.04299365180018696, 'num_leaves': 86, 'max_depth': 16, 'min_child_samples': 55, 'subsample': 0.7876040334076363, 'colsample_bytree': 0.7736339155599743, 'reg_alpha': 0.00220909817911224, 'reg_lambda': 0.0018198804016875277}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:52:53,639] Trial 11 finished with value: 9.276794893946835 and parameters: {'n_estimators': 1105, 'learning_rate': 0.005501959837780936, 'num_leaves': 242, 'max_depth': 15, 'min_child_samples': 45, 'subsample': 0.6528046433212806, 'colsample_bytree': 0.6200332915693268, 'reg_alpha': 6.982496886163948e-05, 'reg_lambda': 0.190068205583464}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:52:56,013] Trial 12 finished with value: 9.569837113756133 and parameters: {'n_estimators': 992, 'learning_rate': 0.008892830832236694, 'num_leaves': 250, 'max_depth': 3, 'min_child_samples': 57, 'subsample': 0.6448134750292263, 'colsample_bytree': 0.5969508443974081, 'reg_alpha': 2.0057322817130592e-08, 'reg_lambda': 1.0246915956375329}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:52:59,102] Trial 13 finished with value: 9.469239212972688 and parameters: {'n_estimators': 315, 'learning_rate': 0.03332621380182769, 'num_leaves': 221, 'max_depth': 7, 'min_child_samples': 36, 'subsample': 0.7442880882714747, 'colsample_bytree': 0.7426648644713287, 'reg_alpha': 0.00826139949066347, 'reg_lambda': 0.03549654923230345}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:53:05,610] Trial 14 finished with value: 9.66212809451381 and parameters: {'n_estimators': 930, 'learning_rate': 0.010995890162062469, 'num_leaves': 104, 'max_depth': 13, 'min_child_samples': 97, 'subsample': 0.6173983977980622, 'colsample_bytree': 0.6241701198264097, 'reg_alpha': 8.902710870276845e-05, 'reg_lambda': 0.0029422666821505767}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:53:11,337] Trial 15 finished with value: 9.491919625878557 and parameters: {'n_estimators': 716, 'learning_rate': 0.026079065797234003, 'num_leaves': 206, 'max_depth': 7, 'min_child_samples': 33, 'subsample': 0.7092044799470059, 'colsample_bytree': 0.834322860783648, 'reg_alpha': 2.4588190642176817e-06, 'reg_lambda': 0.11704593902253532}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:54:19,046] Trial 16 finished with value: 9.199406887765322 and parameters: {'n_estimators': 1034, 'learning_rate': 0.005098650025410552, 'num_leaves': 149, 'max_depth': 14, 'min_child_samples': 5, 'subsample': 0.8400174937302998, 'colsample_bytree': 0.5640868131022199, 'reg_alpha': 0.0010877849299928224, 'reg_lambda': 2.1511871576784976}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:54:20,768] Trial 17 finished with value: 9.635785664083649 and parameters: {'n_estimators': 413, 'learning_rate': 0.023744327507183752, 'num_leaves': 112, 'max_depth': 5, 'min_child_samples': 53, 'subsample': 0.5915394636106673, 'colsample_bytree': 0.6930341292347695, 'reg_alpha': 0.034957357959551204, 'reg_lambda': 90.2727781039211}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:54:31,942] Trial 18 finished with value: 9.404166997131911 and parameters: {'n_estimators': 626, 'learning_rate': 0.008516153375798636, 'num_leaves': 64, 'max_depth': 9, 'min_child_samples': 28, 'subsample': 0.67455198366465, 'colsample_bytree': 0.9093784190410645, 'reg_alpha': 0.00010111183489223375, 'reg_lambda': 0.0066371814091063}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:54:37,432] Trial 19 finished with value: 10.204877465297319 and parameters: {'n_estimators': 725, 'learning_rate': 0.08864632654230686, 'num_leaves': 225, 'max_depth': 12, 'min_child_samples': 68, 'subsample': 0.5039865168923732, 'colsample_bytree': 0.7491025122658856, 'reg_alpha': 5.272060713405901e-06, 'reg_lambda': 0.06649081268777032}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:54:42,444] Trial 20 finished with value: 9.301427887662847 and parameters: {'n_estimators': 456, 'learning_rate': 0.012817301551030131, 'num_leaves': 170, 'max_depth': 16, 'min_child_samples': 45, 'subsample': 0.9517544509454043, 'colsample_bytree': 0.659727331174519, 'reg_alpha': 1.2722974438529106e-08, 'reg_lambda': 3.5260211336160903}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:54:57,749] Trial 21 finished with value: 9.09062626547888 and parameters: {'n_estimators': 449, 'learning_rate': 0.007047651577949431, 'num_leaves': 170, 'max_depth': 9, 'min_child_samples': 14, 'subsample': 0.7436308691346516, 'colsample_bytree': 0.501732689428295, 'reg_alpha': 0.06821716859422744, 'reg_lambda': 0.02282274167019826}. Best is trial 2 with value: 9.015945712170497.
[I 2026-07-01 19:55:06,184] Trial 22 finished with value: 8.996955936160532 and parameters: {'n_estimators': 359, 'learning_rate': 0.007013884385418362, 'num_leaves': 162, 'max_depth': 8, 'min_child_samples': 13, 'subsample': 0.7103074427792923, 'colsample_bytree': 0.5065031862297116, 'reg_alpha': 0.14974967082765664, 'reg_lambda': 0.3461867931174528}. Best is trial 22 with value: 8.996955936160532.
[I 2026-07-01 19:55:17,778] Trial 23 finished with value: 9.067754227865718 and parameters: {'n_estimators': 344, 'learning_rate': 0.007464432451953269, 'num_leaves': 163, 'max_depth': 8, 'min_child_samples': 12, 'subsample': 0.7954885873286524, 'colsample_bytree': 0.5019647588244238, 'reg_alpha': 0.129944093129258, 'reg_lambda': 0.025463640569082797}. Best is trial 22 with value: 8.996955936160532.
[I 2026-07-01 19:55:25,291] Trial 24 finished with value: 9.457372693085443 and parameters: {'n_estimators': 328, 'learning_rate': 0.020289154204527798, 'num_leaves': 123, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.8211338116630438, 'colsample_bytree': 0.546881252472317, 'reg_alpha': 0.47335079736661767, 'reg_lambda': 0.008925077866434398}. Best is trial 22 with value: 8.996955936160532.
[I 2026-07-01 19:55:28,443] Trial 25 finished with value: 8.911599636850305 and parameters: {'n_estimators': 214, 'learning_rate': 0.010377556206590918, 'num_leaves': 162, 'max_depth': 6, 'min_child_samples': 29, 'subsample': 0.9145942595193252, 'colsample_bytree': 0.6463567920534523, 'reg_alpha': 0.0105136967265325, 'reg_lambda': 0.001292109297400037}. Best is trial 25 with value: 8.911599636850305.
[I 2026-07-01 19:55:30,584] Trial 26 finished with value: 8.942110790516066 and parameters: {'n_estimators': 201, 'learning_rate': 0.010252810684674225, 'num_leaves': 131, 'max_depth': 5, 'min_child_samples': 44, 'subsample': 0.9208393876434613, 'colsample_bytree': 0.7224761157861123, 'reg_alpha': 0.009715356002937712, 'reg_lambda': 0.0016916915444271355}. Best is trial 25 with value: 8.911599636850305.
[I 2026-07-01 19:55:33,182] Trial 27 finished with value: 8.877028713853615 and parameters: {'n_estimators': 206, 'learning_rate': 0.010084847784976429, 'num_leaves': 123, 'max_depth': 6, 'min_child_samples': 42, 'subsample': 0.896387427715505, 'colsample_bytree': 0.7965761513737943, 'reg_alpha': 0.013035851346516292, 'reg_lambda': 0.0011961593322350973}. Best is trial 27 with value: 8.877028713853615.
[I 2026-07-01 19:55:35,740] Trial 28 finished with value: 8.7517924386244 and parameters: {'n_estimators': 205, 'learning_rate': 0.010575122940328677, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 45, 'subsample': 0.9003541955370041, 'colsample_bytree': 0.8071954313450789, 'reg_alpha': 0.011213011685009057, 'reg_lambda': 0.0012563423102157237}. Best is trial 28 with value: 8.7517924386244.
[I 2026-07-01 19:55:38,232] Trial 29 finished with value: 8.64683297073943 and parameters: {'n_estimators': 257, 'learning_rate': 0.012257669661257171, 'num_leaves': 78, 'max_depth': 6, 'min_child_samples': 63, 'subsample': 0.9095967806800318, 'colsample_bytree': 0.7971007296326255, 'reg_alpha': 0.0006916262788278913, 'reg_lambda': 0.0010480030769005136}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:55:40,335] Trial 30 finished with value: 9.089122465301726 and parameters: {'n_estimators': 278, 'learning_rate': 0.021092552123872232, 'num_leaves': 70, 'max_depth': 6, 'min_child_samples': 63, 'subsample': 0.8860201351157382, 'colsample_bytree': 0.7963669531490197, 'reg_alpha': 0.0006077265681593901, 'reg_lambda': 0.003456387383294201}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:55:42,744] Trial 31 finished with value: 8.76152997781545 and parameters: {'n_estimators': 263, 'learning_rate': 0.010729108431369646, 'num_leaves': 89, 'max_depth': 6, 'min_child_samples': 68, 'subsample': 0.9189614272786696, 'colsample_bytree': 0.8556397379073748, 'reg_alpha': 0.007494975554170273, 'reg_lambda': 0.001013905489620327}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:55:45,119] Trial 32 finished with value: 9.024022958152775 and parameters: {'n_estimators': 273, 'learning_rate': 0.011822110363515511, 'num_leaves': 89, 'max_depth': 6, 'min_child_samples': 72, 'subsample': 0.9986564848494895, 'colsample_bytree': 0.8611472869134347, 'reg_alpha': 0.0003793740318805293, 'reg_lambda': 0.0010081320721280172}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:55:46,328] Trial 33 finished with value: 9.51063779475332 and parameters: {'n_estimators': 251, 'learning_rate': 0.01744026422161892, 'num_leaves': 52, 'max_depth': 3, 'min_child_samples': 61, 'subsample': 0.943375270877315, 'colsample_bytree': 0.9318115971345287, 'reg_alpha': 0.0034226488239136824, 'reg_lambda': 0.003834275027476336}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:55:48,141] Trial 34 finished with value: 9.12311459657393 and parameters: {'n_estimators': 387, 'learning_rate': 0.013441424733949518, 'num_leaves': 92, 'max_depth': 4, 'min_child_samples': 50, 'subsample': 0.8805029672081808, 'colsample_bytree': 0.8472250512830367, 'reg_alpha': 0.024838474263771334, 'reg_lambda': 0.002842624683547297}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:55:50,381] Trial 35 finished with value: 8.649529723498345 and parameters: {'n_estimators': 278, 'learning_rate': 0.008788853678685645, 'num_leaves': 72, 'max_depth': 6, 'min_child_samples': 77, 'subsample': 0.9072867709512494, 'colsample_bytree': 0.7935197920612945, 'reg_alpha': 1.697316781696097e-05, 'reg_lambda': 0.0010618479975926663}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:55:52,100] Trial 36 finished with value: 9.668653477690482 and parameters: {'n_estimators': 288, 'learning_rate': 0.005948164110788799, 'num_leaves': 73, 'max_depth': 4, 'min_child_samples': 86, 'subsample': 0.9612005106598478, 'colsample_bytree': 0.8813314561976813, 'reg_alpha': 1.630330926122681e-05, 'reg_lambda': 0.005612895213166731}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:55:55,971] Trial 37 finished with value: 9.749923317408825 and parameters: {'n_estimators': 503, 'learning_rate': 0.008726196863698328, 'num_leaves': 48, 'max_depth': 7, 'min_child_samples': 73, 'subsample': 0.8555379094254881, 'colsample_bytree': 0.9365438991905826, 'reg_alpha': 1.8493467449504076e-05, 'reg_lambda': 0.0020652260527722027}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:55:58,192] Trial 38 finished with value: 9.168496223324306 and parameters: {'n_estimators': 404, 'learning_rate': 0.015775837475877904, 'num_leaves': 52, 'max_depth': 5, 'min_child_samples': 92, 'subsample': 0.9175345914605859, 'colsample_bytree': 0.785124803408521, 'reg_alpha': 0.0002740885029247851, 'reg_lambda': 0.0010029725615081327}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:56:00,422] Trial 39 finished with value: 9.210015977728816 and parameters: {'n_estimators': 273, 'learning_rate': 0.028983988090552693, 'num_leaves': 18, 'max_depth': 10, 'min_child_samples': 66, 'subsample': 0.8330370770963773, 'colsample_bytree': 0.8118166806303826, 'reg_alpha': 0.002150268155346818, 'reg_lambda': 0.013161558948458905}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:56:02,937] Trial 40 finished with value: 8.76598574944221 and parameters: {'n_estimators': 352, 'learning_rate': 0.00629467691839836, 'num_leaves': 101, 'max_depth': 6, 'min_child_samples': 76, 'subsample': 0.9780500821990438, 'colsample_bytree': 0.7683549047798817, 'reg_alpha': 1.6440734673351568e-06, 'reg_lambda': 0.0052634463809723255}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:56:05,671] Trial 41 finished with value: 8.803140742340254 and parameters: {'n_estimators': 347, 'learning_rate': 0.006283618259397624, 'num_leaves': 102, 'max_depth': 6, 'min_child_samples': 77, 'subsample': 0.9744091684616449, 'colsample_bytree': 0.7588540285209215, 'reg_alpha': 1.6963653868586393e-07, 'reg_lambda': 0.005079626668894586}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:56:07,448] Trial 42 finished with value: 9.099885406609555 and parameters: {'n_estimators': 248, 'learning_rate': 0.008064505537061336, 'num_leaves': 81, 'max_depth': 5, 'min_child_samples': 88, 'subsample': 0.936201411012247, 'colsample_bytree': 0.8265411927527299, 'reg_alpha': 1.4369231984403636e-06, 'reg_lambda': 0.00256760050082035}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:56:11,273] Trial 43 finished with value: 8.883675594106345 and parameters: {'n_estimators': 468, 'learning_rate': 0.006375402187596529, 'num_leaves': 64, 'max_depth': 7, 'min_child_samples': 73, 'subsample': 0.8997790674575734, 'colsample_bytree': 0.7200608562229878, 'reg_alpha': 5.392267745505152e-07, 'reg_lambda': 0.01298160560182374}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:56:13,171] Trial 44 finished with value: 8.935558182212349 and parameters: {'n_estimators': 388, 'learning_rate': 0.012582449892149553, 'num_leaves': 98, 'max_depth': 4, 'min_child_samples': 83, 'subsample': 0.9705602050083594, 'colsample_bytree': 0.866675349297636, 'reg_alpha': 1.4564596247275313e-05, 'reg_lambda': 0.0019282897815158405}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:56:15,810] Trial 45 finished with value: 8.881902300761192 and parameters: {'n_estimators': 308, 'learning_rate': 0.009596692406946727, 'num_leaves': 79, 'max_depth': 8, 'min_child_samples': 77, 'subsample': 0.9325810096764241, 'colsample_bytree': 0.7675785062846358, 'reg_alpha': 6.209241703110545e-07, 'reg_lambda': 0.004769648743587711}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:56:18,170] Trial 46 finished with value: 10.266225051485844 and parameters: {'n_estimators': 254, 'learning_rate': 0.017891685029359325, 'num_leaves': 112, 'max_depth': 6, 'min_child_samples': 59, 'subsample': 0.8649891536411013, 'colsample_bytree': 0.8047821913399332, 'reg_alpha': 3.7683836464090495e-05, 'reg_lambda': 0.008111844578862654}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:56:21,754] Trial 47 finished with value: 9.23515139127497 and parameters: {'n_estimators': 510, 'learning_rate': 0.013799150410001295, 'num_leaves': 45, 'max_depth': 7, 'min_child_samples': 66, 'subsample': 0.9983901830237665, 'colsample_bytree': 0.8905219418470623, 'reg_alpha': 0.3335241926254416, 'reg_lambda': 0.0016685836606765525}. Best is trial 29 with value: 8.64683297073943.
[I 2026-07-01 19:56:23,078] Trial 48 finished with value: 8.581406648891175 and parameters: {'n_estimators': 350, 'learning_rate': 0.0079068689567303, 'num_leaves': 60, 'max_depth': 3, 'min_child_samples': 70, 'subsample': 0.8069360107171596, 'colsample_bytree': 0.8451002058332729, 'reg_alpha': 0.00018657067434583048, 'reg_lambda': 0.0031930802091338947}. Best is trial 48 with value: 8.581406648891175.

[I 2026-07-01 19:57:17,490] A new study created in RDB with name: lightgbm_optuna_full_ta_fold_2

  0%|          | 0/75 [00:00<?, ?it/s]

[I 2026-07-01 19:57:25,641] Trial 0 finished with value: 7.689280715488762 and parameters: {'n_estimators': 574, 'learning_rate': 0.1667521176194013, 'num_leaves': 191, 'max_depth': 11, 'min_child_samples': 19, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.5290418060840998, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 1.0129197956845732}. Best is trial 0 with value: 7.689280715488762.
[I 2026-07-01 19:57:52,927] Trial 1 finished with value: 7.350865522478873 and parameters: {'n_estimators': 908, 'learning_rate': 0.005394455304087533, 'num_leaves': 248, 'max_depth': 14, 'min_child_samples': 25, 'subsample': 0.5909124836035503, 'colsample_bytree': 0.5917022549267169, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.4205156450913872}. Best is trial 1 with value: 7.350865522478873.
[I 2026-07-01 19:57:55,569] Trial 2 finished with value: 6.869233028955439 and parameters: {'n_estimators': 632, 'learning_rate': 0.014639847680621753, 'num_leaves': 162, 'max_depth': 4, 'min_child_samples': 33, 'subsample': 0.6831809216468459, 'colsample_bytree': 0.728034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 0.009962513222055111}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:58:02,894] Trial 3 finished with value: 7.30743087896011 and parameters: {'n_estimators': 714, 'learning_rate': 0.04446862319918233, 'num_leaves': 26, 'max_depth': 11, 'min_child_samples': 21, 'subsample': 0.5325257964926398, 'colsample_bytree': 0.9744427686266666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 11.015056790269638}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:58:19,437] Trial 4 finished with value: 7.3333155003633905 and parameters: {'n_estimators': 504, 'learning_rate': 0.0071688020821370525, 'num_leaves': 179, 'max_depth': 9, 'min_child_samples': 16, 'subsample': 0.7475884550556351, 'colsample_bytree': 0.5171942605576092, 'reg_alpha': 1.527156759251193, 'reg_lambda': 0.01967432802530612}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:58:29,690] Trial 5 finished with value: 7.056390741796892 and parameters: {'n_estimators': 863, 'learning_rate': 0.015788826347222458, 'num_leaves': 140, 'max_depth': 10, 'min_child_samples': 22, 'subsample': 0.9847923138822793, 'colsample_bytree': 0.8875664116805573, 'reg_alpha': 2.854239907497756, 'reg_lambda': 29.79454462591363}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:58:35,493] Trial 6 finished with value: 7.14960342864178 and parameters: {'n_estimators': 798, 'learning_rate': 0.14992285132527539, 'num_leaves': 36, 'max_depth': 5, 'min_child_samples': 9, 'subsample': 0.6626651653816322, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 13.921548533046511}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:58:37,757] Trial 7 finished with value: 7.105258718252964 and parameters: {'n_estimators': 557, 'learning_rate': 0.014094313993387368, 'num_leaves': 145, 'max_depth': 4, 'min_child_samples': 82, 'subsample': 0.5372753218398854, 'colsample_bytree': 0.9934434683002586, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 0.009853225172032555}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:58:39,623] Trial 8 finished with value: 7.3927901351814755 and parameters: {'n_estimators': 205, 'learning_rate': 0.10124839170683374, 'num_leaves': 185, 'max_depth': 13, 'min_child_samples': 79, 'subsample': 0.5370223258670452, 'colsample_bytree': 0.6792328642721364, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 20.67840939783948}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:58:45,475] Trial 9 finished with value: 7.257668213561044 and parameters: {'n_estimators': 823, 'learning_rate': 0.01694683071232564, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 36, 'subsample': 0.864803089169032, 'colsample_bytree': 0.8187787356776066, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.22965432344634354}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:58:56,368] Trial 10 finished with value: 7.579467396471809 and parameters: {'n_estimators': 1153, 'learning_rate': 0.04299365180018696, 'num_leaves': 86, 'max_depth': 16, 'min_child_samples': 55, 'subsample': 0.7876040334076363, 'colsample_bytree': 0.7736339155599743, 'reg_alpha': 0.00220909817911224, 'reg_lambda': 0.0018198804016875277}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:58:58,639] Trial 11 finished with value: 6.877871420776149 and parameters: {'n_estimators': 1050, 'learning_rate': 0.016680413748136693, 'num_leaves': 121, 'max_depth': 3, 'min_child_samples': 46, 'subsample': 0.9924374812760125, 'colsample_bytree': 0.8770952470886595, 'reg_alpha': 0.0029151336209232823, 'reg_lambda': 97.11833180641256}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:59:01,277] Trial 12 finished with value: 6.972645502781091 and parameters: {'n_estimators': 1131, 'learning_rate': 0.028789293195729152, 'num_leaves': 103, 'max_depth': 3, 'min_child_samples': 49, 'subsample': 0.9531798190089887, 'colsample_bytree': 0.8641192336754783, 'reg_alpha': 0.0021839487437881415, 'reg_lambda': 1.7149714600658907}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:59:02,971] Trial 13 finished with value: 7.182258309970607 and parameters: {'n_estimators': 318, 'learning_rate': 0.00940262077240925, 'num_leaves': 96, 'max_depth': 6, 'min_child_samples': 60, 'subsample': 0.8805804760459623, 'colsample_bytree': 0.7217113164363262, 'reg_alpha': 0.00403560632721464, 'reg_lambda': 97.03579146657232}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:59:05,436] Trial 14 finished with value: 6.935214181725557 and parameters: {'n_estimators': 975, 'learning_rate': 0.026450946391297397, 'num_leaves': 235, 'max_depth': 3, 'min_child_samples': 40, 'subsample': 0.6946662206422697, 'colsample_bytree': 0.9057988992739082, 'reg_alpha': 0.00011497396497841208, 'reg_lambda': 0.04020229935490061}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:59:11,499] Trial 15 finished with value: 6.944134783409674 and parameters: {'n_estimators': 1052, 'learning_rate': 0.01019808517575127, 'num_leaves': 139, 'max_depth': 7, 'min_child_samples': 66, 'subsample': 0.8365412179880075, 'colsample_bytree': 0.6258606036143923, 'reg_alpha': 0.043752134724692165, 'reg_lambda': 0.002106510568768161}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:59:14,946] Trial 16 finished with value: 7.1817428813627435 and parameters: {'n_estimators': 681, 'learning_rate': 0.0258541737629666, 'num_leaves': 69, 'max_depth': 5, 'min_child_samples': 39, 'subsample': 0.9220827337308685, 'colsample_bytree': 0.7823524752965281, 'reg_alpha': 0.0002995097039140433, 'reg_lambda': 0.08445033886967068}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:59:17,484] Trial 17 finished with value: 7.131356689212691 and parameters: {'n_estimators': 413, 'learning_rate': 0.054470154313498824, 'num_leaves': 122, 'max_depth': 8, 'min_child_samples': 71, 'subsample': 0.6637452938214105, 'colsample_bytree': 0.831503427236989, 'reg_alpha': 0.04873295753731013, 'reg_lambda': 3.1739592485097496}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:59:20,516] Trial 18 finished with value: 6.917805189627584 and parameters: {'n_estimators': 1199, 'learning_rate': 0.019188871032151104, 'num_leaves': 215, 'max_depth': 3, 'min_child_samples': 31, 'subsample': 0.7957588354978627, 'colsample_bytree': 0.7379025290360708, 'reg_alpha': 0.00014021547203370562, 'reg_lambda': 0.0064542044282975925}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:59:26,954] Trial 19 finished with value: 7.2370664190435265 and parameters: {'n_estimators': 998, 'learning_rate': 0.010598086483459803, 'num_leaves': 63, 'max_depth': 6, 'min_child_samples': 48, 'subsample': 0.9967068292061625, 'colsample_bytree': 0.9325726849209974, 'reg_alpha': 0.010797619250327597, 'reg_lambda': 0.1341200327654067}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:59:29,384] Trial 20 finished with value: 7.314439953252987 and parameters: {'n_estimators': 684, 'learning_rate': 0.07638043305735345, 'num_leaves': 165, 'max_depth': 5, 'min_child_samples': 98, 'subsample': 0.7334353763731788, 'colsample_bytree': 0.6299871150842886, 'reg_alpha': 1.2722974438529106e-08, 'reg_lambda': 93.15666345772182}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:59:32,058] Trial 21 finished with value: 6.929042413020423 and parameters: {'n_estimators': 1118, 'learning_rate': 0.020301325600803506, 'num_leaves': 212, 'max_depth': 3, 'min_child_samples': 32, 'subsample': 0.8206193892898175, 'colsample_bytree': 0.7523571380476008, 'reg_alpha': 0.00013084466370348973, 'reg_lambda': 0.005333908858175269}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:59:36,255] Trial 22 finished with value: 6.938001695659883 and parameters: {'n_estimators': 1187, 'learning_rate': 0.013225868562629521, 'num_leaves': 227, 'max_depth': 4, 'min_child_samples': 31, 'subsample': 0.6247169050806954, 'colsample_bytree': 0.7327122497128112, 'reg_alpha': 1.1121494338132051e-05, 'reg_lambda': 0.0045797459343696525}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:59:39,797] Trial 23 finished with value: 7.1874288750647475 and parameters: {'n_estimators': 1030, 'learning_rate': 0.021847222319854323, 'num_leaves': 207, 'max_depth': 4, 'min_child_samples': 47, 'subsample': 0.7697153915827771, 'colsample_bytree': 0.811216036449652, 'reg_alpha': 0.00033714761656287686, 'reg_lambda': 0.03821374490649833}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:59:42,286] Trial 24 finished with value: 7.081464499700093 and parameters: {'n_estimators': 946, 'learning_rate': 0.035096251190216796, 'num_leaves': 162, 'max_depth': 3, 'min_child_samples': 11, 'subsample': 0.9009332093491278, 'colsample_bytree': 0.6721148329848075, 'reg_alpha': 0.1667038547347587, 'reg_lambda': 0.014257584868597467}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:59:52,461] Trial 25 finished with value: 7.118466234009987 and parameters: {'n_estimators': 1072, 'learning_rate': 0.007141100599440933, 'num_leaves': 125, 'max_depth': 6, 'min_child_samples': 28, 'subsample': 0.7057485576745243, 'colsample_bytree': 0.8522061542007372, 'reg_alpha': 0.0105136967265325, 'reg_lambda': 0.001075105328645676}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 19:59:55,479] Trial 26 finished with value: 7.115010584593865 and parameters: {'n_estimators': 764, 'learning_rate': 0.018782808401212853, 'num_leaves': 162, 'max_depth': 4, 'min_child_samples': 44, 'subsample': 0.8110486543490842, 'colsample_bytree': 0.9502863575592493, 'reg_alpha': 4.548198812585788e-05, 'reg_lambda': 4.498684155633987}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 20:00:00,796] Trial 27 finished with value: 7.2263268389426365 and parameters: {'n_estimators': 1176, 'learning_rate': 0.012425329415788553, 'num_leaves': 205, 'max_depth': 5, 'min_child_samples': 57, 'subsample': 0.9371956112384685, 'colsample_bytree': 0.7802254733715157, 'reg_alpha': 7.837759630045276e-07, 'reg_lambda': 0.670676154762254}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 20:00:03,113] Trial 28 finished with value: 6.906045155976315 and parameters: {'n_estimators': 912, 'learning_rate': 0.007849652670375839, 'num_leaves': 114, 'max_depth': 3, 'min_child_samples': 35, 'subsample': 0.6323585999023397, 'colsample_bytree': 0.5747980929200232, 'reg_alpha': 0.000788192304161748, 'reg_lambda': 0.004656245822158048}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 20:00:18,553] Trial 29 finished with value: 7.310791679287339 and parameters: {'n_estimators': 602, 'learning_rate': 0.005231473213264303, 'num_leaves': 113, 'max_depth': 7, 'min_child_samples': 16, 'subsample': 0.5016315351919987, 'colsample_bytree': 0.5809434385415813, 'reg_alpha': 0.361864605016622, 'reg_lambda': 0.026398896738809886}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 20:00:22,412] Trial 30 finished with value: 6.930033238060756 and parameters: {'n_estimators': 870, 'learning_rate': 0.0075329605327964025, 'num_leaves': 71, 'max_depth': 4, 'min_child_samples': 5, 'subsample': 0.6046804857262391, 'colsample_bytree': 0.5532240994396691, 'reg_alpha': 0.0009800857167340713, 'reg_lambda': 0.002637584754521915}. Best is trial 2 with value: 6.869233028955439.
[I 2026-07-01 20:00:25,117] Trial 31 finished with value: 6.842195396172317 and parameters: {'n_estimators': 1086, 'learning_rate': 0.009420919398139615, 'num_leaves': 147, 'max_depth': 3, 'min_child_samples': 35, 'subsample': 0.6381617787413916, 'colsample_bytree': 0.6478799380008154, 'reg_alpha': 2.7661375044153016e-05, 'reg_lambda': 0.007131537885093295}. Best is trial 31 with value: 6.842195396172317.
[I 2026-07-01 20:00:27,472] Trial 32 finished with value: 6.861343277615718 and parameters: {'n_estimators': 949, 'learning_rate': 0.008401590566504942, 'num_leaves': 150, 'max_depth': 3, 'min_child_samples': 41, 'subsample': 0.6456728810360722, 'colsample_bytree': 0.6335587970510052, 'reg_alpha': 3.1031008171599114e-05, 'reg_lambda': 0.07489032468280318}. Best is trial 31 with value: 6.842195396172317.
[I 2026-07-01 20:00:32,636] Trial 33 finished with value: 7.114531376430302 and parameters: {'n_estimators': 1078, 'learning_rate': 0.00935310084710751, 'num_leaves': 150, 'max_depth': 5, 'min_child_samples': 42, 'subsample': 0.5716482409380493, 'colsample_bytree': 0.6258753948109979, 'reg_alpha': 1.5923010092897902e-05, 'reg_lambda': 0.075066304913557}. Best is trial 31 with value: 6.842195396172317.
[I 2026-07-01 20:00:35,971] Trial 34 finished with value: 7.01359374222223 and parameters: {'n_estimators': 952, 'learning_rate': 0.012837850814038529, 'num_leaves': 174, 'max_depth': 4, 'min_child_samples': 53, 'subsample': 0.6571463968212766, 'colsample_bytree': 0.6470084776982421, 'reg_alpha': 1.2412290940965426e-06, 'reg_lambda': 0.3033304607199967}. Best is trial 31 with value: 6.842195396172317.
[I 2026-07-01 20:00:48,635] Trial 35 finished with value: 7.154339014134718 and parameters: {'n_estimators': 1025, 'learning_rate': 0.006320629543980935, 'num_leaves': 131, 'max_depth': 6, 'min_child_samples': 20, 'subsample': 0.5691986641997921, 'colsample_bytree': 0.7001485622422047, 'reg_alpha': 0.015171093494834411, 'reg_lambda': 0.010064220494442357}. Best is trial 31 with value: 6.842195396172317.
[I 2026-07-01 20:00:50,377] Trial 36 finished with value: 7.106682886641514 and parameters: {'n_estimators': 489, 'learning_rate': 0.005977776225331353, 'num_leaves': 194, 'max_depth': 3, 'min_child_samples': 25, 'subsample': 0.6875921623161011, 'colsample_bytree': 0.5021345958158536, 'reg_alpha': 1.6880075604821412e-05, 'reg_lambda': 1.053340168552173}. Best is trial 31 with value: 6.842195396172317.
[I 2026-07-01 20:00:52,902] Trial 37 finished with value: 7.163254533247457 and parameters: {'n_estimators': 750, 'learning_rate': 0.011544781798439142, 'num_leaves': 158, 'max_depth': 4, 'min_child_samples': 61, 'subsample': 0.7424854810677135, 'colsample_bytree': 0.6003376480862453, 'reg_alpha': 6.865727594660676, 'reg_lambda': 36.62667989219878}. Best is trial 31 with value: 6.842195396172317.
[I 2026-07-01 20:01:02,816] Trial 38 finished with value: 7.210965377270114 and parameters: {'n_estimators': 614, 'learning_rate': 0.008300462298322084, 'num_leaves': 137, 'max_depth': 12, 'min_child_samples': 25, 'subsample': 0.5983728621747745, 'colsample_bytree': 0.5508909305144659, 'reg_alpha': 3.6477946482083838e-06, 'reg_lambda': 6.382377522356842}. Best is trial 31 with value: 6.842195396172317.
[I 2026-07-01 20:01:07,346] Trial 39 finished with value: 7.127300557029189 and parameters: {'n_estimators': 886, 'learning_rate': 0.016273769631328143, 'num_leaves': 177, 'max_depth': 5, 'min_child_samples': 37, 'subsample': 0.7233725812165923, 'colsample_bytree': 0.6701120513607601, 'reg_alpha': 1.045987239438301e-07, 'reg_lambda': 0.023127270664760544}. Best is trial 31 with value: 6.842195396172317.
[I 2026-07-01 20:01:13,779] Trial 40 finished with value: 7.0907440110168345 and parameters: {'n_estimators': 826, 'learning_rate': 0.01478321643933655, 'num_leaves': 255, 'max_depth': 9, 'min_child_samples': 52, 'subsample': 0.6389357165196757, 'colsample_bytree': 0.6507309786948278, 'reg_alpha': 1.5587591459367083, 'reg_lambda': 0.0011243441128901597}. Best is trial 31 with value: 6.842195396172317.
[I 2026-07-01 20:01:16,345] Trial 41 finished with value: 6.8751568267094125 and parameters: {'n_estimators': 942, 'learning_rate': 0.008286317869844472, 'num_leaves': 114, 'max_depth': 3, 'min_child_samples': 35, 'subsample': 0.6219477073928982, 'colsample_bytree': 0.5794177568532055, 'reg_alpha': 0.0006104194844269174, 'reg_lambda': 0.003532133622334315}. Best is trial 31 with value: 6.842195396172317.
[I 2026-07-01 20:01:19,030] Trial 42 finished with value: 6.85907067478552 and parameters: {'n_estimators': 1111, 'learning_rate': 0.009001902476424219, 'num_leaves': 153, 'max_depth': 3, 'min_child_samples': 42, 'subsample': 0.559077763464981, 'colsample_bytree': 0.6086074572594399, 'reg_alpha': 2.915262321134165e-05, 'reg_lambda': 0.0030810016669353783}. Best is trial 31 with value: 6.842195396172317.
[I 2026-07-01 20:01:23,481] Trial 43 finished with value: 6.959101876376281 and parameters: {'n_estimators': 1106, 'learning_rate': 0.006402237924703334, 'num_leaves': 150, 'max_depth': 4, 'min_child_samples': 35, 'subsample': 0.5769682590438323, 'colsample_bytree': 0.5965165898698354, 'reg_alpha': 3.159648085831502e-05, 'reg_lambda': 0.008675231429644652}. Best is trial 31 with value: 6.842195396172317.
[I 2026-07-01 20:01:25,752] Trial 44 finished with value: 6.845109309392196 and parameters: {'n_estimators': 923, 'learning_rate': 0.009148233110060184, 'num_leaves': 173, 'max_depth': 3, 'min_child_samples': 42, 'subsample': 0.6714158482654105, 'colsample_bytree': 0.532252531442539, 'reg_alpha': 1.0550724964291425e-06, 'reg_lambda': 0.0031208388264462}. Best is trial 31 with value: 6.842195396172317.
[I 2026-07-01 20:01:27,723] Trial 45 finished with value: 6.910034316378216 and parameters: {'n_estimators': 366, 'learning_rate': 0.009549270983487151, 'num_leaves': 191, 'max_depth': 4, 'min_child_samples': 41, 'subsample': 0.6889005324997, 'colsample_bytree': 0.5405045629681273, 'reg_alpha': 3.0827310628600214e-07, 'reg_lambda': 0.01285332139204672}. Best is trial 31 with value: 6.842195396172317.
[I 2026-07-01 20:01:30,354] Trial 46 finished with value: 6.912117272118471 and parameters: {'n_estimators': 998, 'learning_rate': 0.011195208029570346, 'num_leaves': 171, 'max_depth': 3, 'min_child_samples': 28, 'subsample': 0.5506379111350973, 'colsample_bytree': 0.5179435152842031, 'reg_alpha': 6.8446121568464274e-06, 'reg_lambda': 0.001767014139567717}. Best is trial 31 with value: 6.842195396172317.
[I 2026-07-01 20:01:34,211] Trial 47 finished with value: 8.922619120201096 and parameters: {'n_estimators': 248, 'learning_rate': 0.005254442506670192, 'num_leaves': 183, 'max_depth': 16, 'min_child_samples': 43, 'subsample': 0.6576153467028093, 'colsample_bytree': 0.7136173232159836, 'reg_alpha': 1.8496556130977464e-06, 'reg_lambda': 0.05718411063203925}. Best is trial 31 with value: 6.842195396172317.
[I 2026-07-01 20:01:39,855] Trial 48 finished with value: 7.09499469389601 and parameters: {'n_estimators': 1139, 'learning_rate': 0.008806793954081482, 'num_leaves': 152, 'max_depth': 5, 'min_child_samples': 49, 'subsample': 0.6745670090325318, 'colsample_bytree': 0.6148182435146298, 'reg_alpha': 4.268367582455954e-07, 'reg_lambda': 0.019334178588328407}. Best is trial 31 with value: 6.842195396172317.

[I 2026-07-01 20:03:26,050] A new study created in RDB with name: lightgbm_optuna_full_ta_fold_3

  0%|          | 0/75 [00:00<?, ?it/s]

[I 2026-07-01 20:03:36,469] Trial 0 finished with value: 8.465642987288536 and parameters: {'n_estimators': 574, 'learning_rate': 0.1667521176194013, 'num_leaves': 191, 'max_depth': 11, 'min_child_samples': 19, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.5290418060840998, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 1.0129197956845732}. Best is trial 0 with value: 8.465642987288536.
[I 2026-07-01 20:04:04,889] Trial 1 finished with value: 8.050976803537145 and parameters: {'n_estimators': 908, 'learning_rate': 0.005394455304087533, 'num_leaves': 248, 'max_depth': 14, 'min_child_samples': 25, 'subsample': 0.5909124836035503, 'colsample_bytree': 0.5917022549267169, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.4205156450913872}. Best is trial 1 with value: 8.050976803537145.
[I 2026-07-01 20:04:07,577] Trial 2 finished with value: 7.842383851931658 and parameters: {'n_estimators': 632, 'learning_rate': 0.014639847680621753, 'num_leaves': 162, 'max_depth': 4, 'min_child_samples': 33, 'subsample': 0.6831809216468459, 'colsample_bytree': 0.728034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 0.009962513222055111}. Best is trial 2 with value: 7.842383851931658.
[I 2026-07-01 20:04:15,477] Trial 3 finished with value: 8.450353443127835 and parameters: {'n_estimators': 714, 'learning_rate': 0.04446862319918233, 'num_leaves': 26, 'max_depth': 11, 'min_child_samples': 21, 'subsample': 0.5325257964926398, 'colsample_bytree': 0.9744427686266666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 11.015056790269638}. Best is trial 2 with value: 7.842383851931658.
[I 2026-07-01 20:04:36,248] Trial 4 finished with value: 8.18088329526272 and parameters: {'n_estimators': 504, 'learning_rate': 0.0071688020821370525, 'num_leaves': 179, 'max_depth': 9, 'min_child_samples': 16, 'subsample': 0.7475884550556351, 'colsample_bytree': 0.5171942605576092, 'reg_alpha': 1.527156759251193, 'reg_lambda': 0.01967432802530612}. Best is trial 2 with value: 7.842383851931658.
[I 2026-07-01 20:04:48,525] Trial 5 finished with value: 8.234729031734846 and parameters: {'n_estimators': 863, 'learning_rate': 0.015788826347222458, 'num_leaves': 140, 'max_depth': 10, 'min_child_samples': 22, 'subsample': 0.9847923138822793, 'colsample_bytree': 0.8875664116805573, 'reg_alpha': 2.854239907497756, 'reg_lambda': 29.79454462591363}. Best is trial 2 with value: 7.842383851931658.
[I 2026-07-01 20:04:54,461] Trial 6 finished with value: 8.787191724119339 and parameters: {'n_estimators': 798, 'learning_rate': 0.14992285132527539, 'num_leaves': 36, 'max_depth': 5, 'min_child_samples': 9, 'subsample': 0.6626651653816322, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 13.921548533046511}. Best is trial 2 with value: 7.842383851931658.
[I 2026-07-01 20:04:56,870] Trial 7 finished with value: 7.876711577012333 and parameters: {'n_estimators': 557, 'learning_rate': 0.014094313993387368, 'num_leaves': 145, 'max_depth': 4, 'min_child_samples': 82, 'subsample': 0.5372753218398854, 'colsample_bytree': 0.9934434683002586, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 0.009853225172032555}. Best is trial 2 with value: 7.842383851931658.
[I 2026-07-01 20:04:59,017] Trial 8 finished with value: 7.983246069187926 and parameters: {'n_estimators': 205, 'learning_rate': 0.10124839170683374, 'num_leaves': 185, 'max_depth': 13, 'min_child_samples': 79, 'subsample': 0.5370223258670452, 'colsample_bytree': 0.6792328642721364, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 20.67840939783948}. Best is trial 2 with value: 7.842383851931658.
[I 2026-07-01 20:05:05,763] Trial 9 finished with value: 8.074198640061182 and parameters: {'n_estimators': 823, 'learning_rate': 0.01694683071232564, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 36, 'subsample': 0.864803089169032, 'colsample_bytree': 0.8187787356776066, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.22965432344634354}. Best is trial 2 with value: 7.842383851931658.
[I 2026-07-01 20:05:21,169] Trial 10 finished with value: 9.032240184729707 and parameters: {'n_estimators': 1153, 'learning_rate': 0.04299365180018696, 'num_leaves': 86, 'max_depth': 16, 'min_child_samples': 55, 'subsample': 0.7876040334076363, 'colsample_bytree': 0.7736339155599743, 'reg_alpha': 0.00220909817911224, 'reg_lambda': 0.0018198804016875277}. Best is trial 2 with value: 7.842383851931658.
[I 2026-07-01 20:05:22,758] Trial 11 finished with value: 7.952523312697014 and parameters: {'n_estimators': 376, 'learning_rate': 0.014085293347378213, 'num_leaves': 121, 'max_depth': 3, 'min_child_samples': 98, 'subsample': 0.6712579968688783, 'colsample_bytree': 0.9702054152325887, 'reg_alpha': 0.016181314918515946, 'reg_lambda': 0.006033175476678092}. Best is trial 2 with value: 7.842383851931658.
[I 2026-07-01 20:05:24,612] Trial 12 finished with value: 7.900692412441786 and parameters: {'n_estimators': 595, 'learning_rate': 0.028789293195729152, 'num_leaves': 134, 'max_depth': 3, 'min_child_samples': 57, 'subsample': 0.6766980691634803, 'colsample_bytree': 0.8859620061900355, 'reg_alpha': 0.006107112426231116, 'reg_lambda': 0.032150251882459464}. Best is trial 2 with value: 7.842383851931658.
[I 2026-07-01 20:05:29,917] Trial 13 finished with value: 8.00734288715125 and parameters: {'n_estimators': 396, 'learning_rate': 0.009552943812361233, 'num_leaves': 238, 'max_depth': 6, 'min_child_samples': 51, 'subsample': 0.7831567810007137, 'colsample_bytree': 0.6765827643791059, 'reg_alpha': 0.03857451418503985, 'reg_lambda': 0.051416348100684454}. Best is trial 2 with value: 7.842383851931658.
[I 2026-07-01 20:05:34,187] Trial 14 finished with value: 8.187516910438053 and parameters: {'n_estimators': 1035, 'learning_rate': 0.027883906090056008, 'num_leaves': 88, 'max_depth': 5, 'min_child_samples': 74, 'subsample': 0.6210266926101133, 'colsample_bytree': 0.7793992915216571, 'reg_alpha': 0.00022592639353618765, 'reg_lambda': 0.001778970555749303}. Best is trial 2 with value: 7.842383851931658.
[I 2026-07-01 20:05:39,326] Trial 15 finished with value: 8.134510223340328 and parameters: {'n_estimators': 678, 'learning_rate': 0.01019808517575127, 'num_leaves': 160, 'max_depth': 8, 'min_child_samples': 94, 'subsample': 0.867766728461256, 'colsample_bytree': 0.8772765405988207, 'reg_alpha': 0.07072098012950181, 'reg_lambda': 0.007709541099851858}. Best is trial 2 with value: 7.842383851931658.
[I 2026-07-01 20:05:41,273] Trial 16 finished with value: 7.9937837253518005 and parameters: {'n_estimators': 421, 'learning_rate': 0.023283733882760654, 'num_leaves': 217, 'max_depth': 4, 'min_child_samples': 39, 'subsample': 0.5081132980771453, 'colsample_bytree': 0.5990999356117862, 'reg_alpha': 0.00028939767092574215, 'reg_lambda': 0.09960442615235712}. Best is trial 2 with value: 7.842383851931658.
[I 2026-07-01 20:05:42,941] Trial 17 finished with value: 8.181629288294683 and parameters: {'n_estimators': 235, 'learning_rate': 0.054470154313498824, 'num_leaves': 112, 'max_depth': 6, 'min_child_samples': 71, 'subsample': 0.71804991678614, 'colsample_bytree': 0.9394492838257307, 'reg_alpha': 0.16308659257208638, 'reg_lambda': 2.270831117310301}. Best is trial 2 with value: 7.842383851931658.
[I 2026-07-01 20:05:44,740] Trial 18 finished with value: 7.747366774140868 and parameters: {'n_estimators': 691, 'learning_rate': 0.011158052919183079, 'num_leaves': 72, 'max_depth': 3, 'min_child_samples': 84, 'subsample': 0.6156788333044946, 'colsample_bytree': 0.7265016782070561, 'reg_alpha': 0.0008133459398299407, 'reg_lambda': 0.0066371814091063}. Best is trial 18 with value: 7.747366774140868.
[I 2026-07-01 20:05:47,333] Trial 19 finished with value: 7.686010520420643 and parameters: {'n_estimators': 998, 'learning_rate': 0.005231240900344098, 'num_leaves': 62, 'max_depth': 3, 'min_child_samples': 63, 'subsample': 0.6198775028451312, 'colsample_bytree': 0.7396765886951213, 'reg_alpha': 0.0003477833560794966, 'reg_lambda': 0.003329220792856232}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:05:49,848] Trial 20 finished with value: 7.843375890386567 and parameters: {'n_estimators': 992, 'learning_rate': 0.005057073552105661, 'num_leaves': 64, 'max_depth': 3, 'min_child_samples': 65, 'subsample': 0.6200392464368687, 'colsample_bytree': 0.6190358660703527, 'reg_alpha': 2.5615586146289703e-05, 'reg_lambda': 0.0012009439669088036}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:05:53,580] Trial 21 finished with value: 7.856991170446109 and parameters: {'n_estimators': 732, 'learning_rate': 0.00851347048980725, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 88, 'subsample': 0.7030049237863609, 'colsample_bytree': 0.7406732145896625, 'reg_alpha': 0.0009847079116665203, 'reg_lambda': 0.003931852189546593}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:05:57,871] Trial 22 finished with value: 8.128661684327714 and parameters: {'n_estimators': 1165, 'learning_rate': 0.006806799419475297, 'num_leaves': 97, 'max_depth': 4, 'min_child_samples': 42, 'subsample': 0.6247169050806954, 'colsample_bytree': 0.7256090634696454, 'reg_alpha': 4.45410673231838e-05, 'reg_lambda': 0.017415184924734355}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:06:04,072] Trial 23 finished with value: 8.097922397358591 and parameters: {'n_estimators': 985, 'learning_rate': 0.010978118184021182, 'num_leaves': 63, 'max_depth': 7, 'min_child_samples': 65, 'subsample': 0.6440759369487032, 'colsample_bytree': 0.8323902240628859, 'reg_alpha': 2.579708256605178e-07, 'reg_lambda': 0.003513841528698337}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:06:06,012] Trial 24 finished with value: 7.866003184001925 and parameters: {'n_estimators': 657, 'learning_rate': 0.02064046213493468, 'num_leaves': 42, 'max_depth': 3, 'min_child_samples': 31, 'subsample': 0.5797737138482848, 'colsample_bytree': 0.6500003657035215, 'reg_alpha': 0.00048118583163177687, 'reg_lambda': 0.07992224834469146}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:06:14,358] Trial 25 finished with value: 7.992647243256712 and parameters: {'n_estimators': 1073, 'learning_rate': 0.00671667534876619, 'num_leaves': 76, 'max_depth': 6, 'min_child_samples': 47, 'subsample': 0.7390135402481219, 'colsample_bytree': 0.7390310897251647, 'reg_alpha': 1.5450244271507118e-08, 'reg_lambda': 0.01267999800289144}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:06:17,573] Trial 26 finished with value: 7.687567737329135 and parameters: {'n_estimators': 931, 'learning_rate': 0.012092254463997799, 'num_leaves': 108, 'max_depth': 4, 'min_child_samples': 60, 'subsample': 0.783931306822473, 'colsample_bytree': 0.7720554264222628, 'reg_alpha': 6.0781119499799e-05, 'reg_lambda': 0.0032061719593890823}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:06:21,974] Trial 27 finished with value: 7.987857382297498 and parameters: {'n_estimators': 925, 'learning_rate': 0.011246432087243442, 'num_leaves': 117, 'max_depth': 5, 'min_child_samples': 63, 'subsample': 0.8655491247166887, 'colsample_bytree': 0.796588931653368, 'reg_alpha': 7.23228944497731e-05, 'reg_lambda': 0.0028782366895585636}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:06:24,056] Trial 28 finished with value: 7.823827788131426 and parameters: {'n_estimators': 787, 'learning_rate': 0.0080536810809948, 'num_leaves': 15, 'max_depth': 3, 'min_child_samples': 85, 'subsample': 0.9700814976474571, 'colsample_bytree': 0.8454360871894209, 'reg_alpha': 1.735663049756736e-06, 'reg_lambda': 0.0013438454392432876}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:06:31,741] Trial 29 finished with value: 8.094270738036792 and parameters: {'n_estimators': 1088, 'learning_rate': 0.006126401521746261, 'num_leaves': 101, 'max_depth': 7, 'min_child_samples': 74, 'subsample': 0.9199850400681084, 'colsample_bytree': 0.5523046305025091, 'reg_alpha': 0.007034860515370488, 'reg_lambda': 0.026398896738809886}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:06:34,703] Trial 30 finished with value: 8.175382857956567 and parameters: {'n_estimators': 892, 'learning_rate': 0.011361229754235551, 'num_leaves': 49, 'max_depth': 4, 'min_child_samples': 92, 'subsample': 0.8112648212165776, 'colsample_bytree': 0.7642436571379843, 'reg_alpha': 1.2538103235557468e-05, 'reg_lambda': 0.00375831832201291}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:06:36,747] Trial 31 finished with value: 7.859211000740935 and parameters: {'n_estimators': 769, 'learning_rate': 0.008139662518677617, 'num_leaves': 21, 'max_depth': 3, 'min_child_samples': 80, 'subsample': 0.9991417930830014, 'colsample_bytree': 0.8218348895696732, 'reg_alpha': 1.581640601480256e-06, 'reg_lambda': 0.0010154911603219442}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:06:39,315] Trial 32 finished with value: 7.891240543751026 and parameters: {'n_estimators': 958, 'learning_rate': 0.005410168856162279, 'num_leaves': 17, 'max_depth': 3, 'min_child_samples': 88, 'subsample': 0.9540357494774397, 'colsample_bytree': 0.8495232380682556, 'reg_alpha': 0.00011241371731224955, 'reg_lambda': 0.002128618350407443}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:06:43,263] Trial 33 finished with value: 8.193060262410482 and parameters: {'n_estimators': 829, 'learning_rate': 0.012478030747961237, 'num_leaves': 79, 'max_depth': 5, 'min_child_samples': 59, 'subsample': 0.9135257487041484, 'colsample_bytree': 0.7023590112008926, 'reg_alpha': 6.145326970254058e-07, 'reg_lambda': 0.006092121818266069}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:06:46,400] Trial 34 finished with value: 7.960288044563297 and parameters: {'n_estimators': 880, 'learning_rate': 0.00839557441008612, 'num_leaves': 53, 'max_depth': 4, 'min_child_samples': 71, 'subsample': 0.5761365608661431, 'colsample_bytree': 0.6464604075815301, 'reg_alpha': 1.2226010431677968e-05, 'reg_lambda': 0.0010383945398724425}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:06:48,395] Trial 35 finished with value: 7.744452534764828 and parameters: {'n_estimators': 737, 'learning_rate': 0.020387467119572393, 'num_leaves': 70, 'max_depth': 3, 'min_child_samples': 83, 'subsample': 0.8347388145987309, 'colsample_bytree': 0.9182740299886173, 'reg_alpha': 0.002218369497429595, 'reg_lambda': 0.005140810841037339}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:06:51,618] Trial 36 finished with value: 8.005910980241913 and parameters: {'n_estimators': 719, 'learning_rate': 0.019195717578327047, 'num_leaves': 71, 'max_depth': 6, 'min_child_samples': 100, 'subsample': 0.8411535480052922, 'colsample_bytree': 0.9268381767504691, 'reg_alpha': 0.0010848012020903536, 'reg_lambda': 98.44749337245364}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:06:53,586] Trial 37 finished with value: 7.968269642641681 and parameters: {'n_estimators': 508, 'learning_rate': 0.032565387547299825, 'num_leaves': 101, 'max_depth': 4, 'min_child_samples': 47, 'subsample': 0.7588493440749176, 'colsample_bytree': 0.5532819126765207, 'reg_alpha': 0.0035084843352066646, 'reg_lambda': 0.0428115278251952}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:06:56,418] Trial 38 finished with value: 7.916871945334967 and parameters: {'n_estimators': 627, 'learning_rate': 0.017471436140637408, 'num_leaves': 127, 'max_depth': 5, 'min_child_samples': 77, 'subsample': 0.8108613768118565, 'colsample_bytree': 0.7145430417187912, 'reg_alpha': 0.001253214344022287, 'reg_lambda': 0.014478460065002068}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:07:04,909] Trial 39 finished with value: 8.452558890765047 and parameters: {'n_estimators': 1041, 'learning_rate': 0.02412950788008877, 'num_leaves': 89, 'max_depth': 13, 'min_child_samples': 70, 'subsample': 0.5613295458256262, 'colsample_bytree': 0.7518503492046048, 'reg_alpha': 0.02024404924344982, 'reg_lambda': 0.006937530878330262}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:07:08,515] Trial 40 finished with value: 8.488831571386962 and parameters: {'n_estimators': 1119, 'learning_rate': 0.03661177228589116, 'num_leaves': 42, 'max_depth': 4, 'min_child_samples': 61, 'subsample': 0.699130396379537, 'colsample_bytree': 0.800845258903015, 'reg_alpha': 0.00016829752679377, 'reg_lambda': 0.19858280719929225}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:07:10,624] Trial 41 finished with value: 7.865606575854305 and parameters: {'n_estimators': 762, 'learning_rate': 0.007687980607873237, 'num_leaves': 33, 'max_depth': 3, 'min_child_samples': 85, 'subsample': 0.9207763813825234, 'colsample_bytree': 0.9153482020022553, 'reg_alpha': 5.2597744368503085e-06, 'reg_lambda': 0.004370792396420372}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:07:12,616] Trial 42 finished with value: 7.71935935123676 and parameters: {'n_estimators': 840, 'learning_rate': 0.012723156231019722, 'num_leaves': 53, 'max_depth': 3, 'min_child_samples': 83, 'subsample': 0.939614097042831, 'colsample_bytree': 0.8581890943073306, 'reg_alpha': 0.0004939136235851479, 'reg_lambda': 0.0025256665000698638}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:07:15,130] Trial 43 finished with value: 8.682039577008418 and parameters: {'n_estimators': 846, 'learning_rate': 0.0626843124359161, 'num_leaves': 52, 'max_depth': 4, 'min_child_samples': 93, 'subsample': 0.9008882195154833, 'colsample_bytree': 0.8631968007084434, 'reg_alpha': 0.000585949918731403, 'reg_lambda': 0.01202302846601749}. Best is trial 19 with value: 7.686010520420643.
[I 2026-07-01 20:07:17,391] Trial 44 finished with value: 7.673102176191243 and parameters: {'n_estimators': 930, 'learning_rate': 0.014425322621494348, 'num_leaves': 71, 'max_depth': 3, 'min_child_samples': 83, 'subsample': 0.9381603691000177, 'colsample_bytree': 0.9068694684318649, 'reg_alpha': 0.0023116411919291997, 'reg_lambda': 0.002229930625665973}. Best is trial 44 with value: 7.673102176191243.
[I 2026-07-01 20:07:22,025] Trial 45 finished with value: 7.849750984958695 and parameters: {'n_estimators': 936, 'learning_rate': 0.014676675243184225, 'num_leaves': 106, 'max_depth': 5, 'min_child_samples': 52, 'subsample': 0.9482800759553682, 'colsample_bytree': 0.9091773626199149, 'reg_alpha': 0.3895985415331265, 'reg_lambda': 0.0024593379945156424}. Best is trial 44 with value: 7.673102176191243.
[I 2026-07-01 20:07:25,483] Trial 46 finished with value: 7.76563877373887 and parameters: {'n_estimators': 1016, 'learning_rate': 0.013355507994762402, 'num_leaves': 81, 'max_depth': 4, 'min_child_samples': 77, 'subsample': 0.8888164957908475, 'colsample_bytree': 0.9521735991020426, 'reg_alpha': 0.006303428622103183, 'reg_lambda': 0.0019176621658361756}. Best is trial 44 with value: 7.673102176191243.
[I 2026-07-01 20:07:32,429] Trial 47 finished with value: 8.254890896958251 and parameters: {'n_estimators': 886, 'learning_rate': 0.016998404250475982, 'num_leaves': 92, 'max_depth': 11, 'min_child_samples': 69, 'subsample': 0.8399077083670626, 'colsample_bytree': 0.8986730159859495, 'reg_alpha': 0.002693308038207875, 'reg_lambda': 0.024432599417244107}. Best is trial 44 with value: 7.673102176191243.
[I 2026-07-01 20:07:34,785] Trial 48 finished with value: 7.763742409001458 and parameters: {'n_estimators': 951, 'learning_rate': 0.021586980138328937, 'num_leaves': 161, 'max_depth': 3, 'min_child_samples': 81, 'subsample': 0.9457640404844331, 'colsample_bytree': 0.9769419430139826, 'reg_alpha': 2.168149503498431e-05, 'reg_lambda': 0.009635227157387693}. Best is trial 44 with value: 7.673102176191243.

[I 2026-07-01 20:09:17,081] A new study created in RDB with name: lightgbm_optuna_full_ta_fold_4

  0%|          | 0/75 [00:00<?, ?it/s]

[I 2026-07-01 20:09:28,853] Trial 0 finished with value: 8.197950592775422 and parameters: {'n_estimators': 574, 'learning_rate': 0.1667521176194013, 'num_leaves': 191, 'max_depth': 11, 'min_child_samples': 19, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.5290418060840998, 'reg_alpha': 0.6245760287469893, 'reg_lambda': 1.0129197956845732}. Best is trial 0 with value: 8.197950592775422.
[I 2026-07-01 20:10:02,720] Trial 1 finished with value: 7.589208745661318 and parameters: {'n_estimators': 908, 'learning_rate': 0.005394455304087533, 'num_leaves': 248, 'max_depth': 14, 'min_child_samples': 25, 'subsample': 0.5909124836035503, 'colsample_bytree': 0.5917022549267169, 'reg_alpha': 5.472429642032198e-06, 'reg_lambda': 0.4205156450913872}. Best is trial 1 with value: 7.589208745661318.
[I 2026-07-01 20:10:05,709] Trial 2 finished with value: 7.075667737225977 and parameters: {'n_estimators': 632, 'learning_rate': 0.014639847680621753, 'num_leaves': 162, 'max_depth': 4, 'min_child_samples': 33, 'subsample': 0.6831809216468459, 'colsample_bytree': 0.728034992108518, 'reg_alpha': 0.1165691561324743, 'reg_lambda': 0.009962513222055111}. Best is trial 2 with value: 7.075667737225977.
[I 2026-07-01 20:10:14,260] Trial 3 finished with value: 7.409724113016639 and parameters: {'n_estimators': 714, 'learning_rate': 0.04446862319918233, 'num_leaves': 26, 'max_depth': 11, 'min_child_samples': 21, 'subsample': 0.5325257964926398, 'colsample_bytree': 0.9744427686266666, 'reg_alpha': 4.905556676028774, 'reg_lambda': 11.015056790269638}. Best is trial 2 with value: 7.075667737225977.
[I 2026-07-01 20:10:36,578] Trial 4 finished with value: 8.288618643900435 and parameters: {'n_estimators': 504, 'learning_rate': 0.0071688020821370525, 'num_leaves': 179, 'max_depth': 9, 'min_child_samples': 16, 'subsample': 0.7475884550556351, 'colsample_bytree': 0.5171942605576092, 'reg_alpha': 1.527156759251193, 'reg_lambda': 0.01967432802530612}. Best is trial 2 with value: 7.075667737225977.
[I 2026-07-01 20:10:49,724] Trial 5 finished with value: 7.712125306590878 and parameters: {'n_estimators': 863, 'learning_rate': 0.015788826347222458, 'num_leaves': 140, 'max_depth': 10, 'min_child_samples': 22, 'subsample': 0.9847923138822793, 'colsample_bytree': 0.8875664116805573, 'reg_alpha': 2.854239907497756, 'reg_lambda': 29.79454462591363}. Best is trial 2 with value: 7.075667737225977.
[I 2026-07-01 20:10:56,072] Trial 6 finished with value: 8.248334353067063 and parameters: {'n_estimators': 798, 'learning_rate': 0.14992285132527539, 'num_leaves': 36, 'max_depth': 5, 'min_child_samples': 9, 'subsample': 0.6626651653816322, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 13.921548533046511}. Best is trial 2 with value: 7.075667737225977.
[I 2026-07-01 20:10:58,487] Trial 7 finished with value: 7.753233761780348 and parameters: {'n_estimators': 557, 'learning_rate': 0.014094313993387368, 'num_leaves': 145, 'max_depth': 4, 'min_child_samples': 82, 'subsample': 0.5372753218398854, 'colsample_bytree': 0.9934434683002586, 'reg_alpha': 0.08916674715636537, 'reg_lambda': 0.009853225172032555}. Best is trial 2 with value: 7.075667737225977.
[I 2026-07-01 20:11:00,637] Trial 8 finished with value: 7.7228732404081555 and parameters: {'n_estimators': 205, 'learning_rate': 0.10124839170683374, 'num_leaves': 185, 'max_depth': 13, 'min_child_samples': 79, 'subsample': 0.5370223258670452, 'colsample_bytree': 0.6792328642721364, 'reg_alpha': 1.1036250149900698e-07, 'reg_lambda': 20.67840939783948}. Best is trial 2 with value: 7.075667737225977.
[I 2026-07-01 20:11:07,270] Trial 9 finished with value: 7.359624001429067 and parameters: {'n_estimators': 823, 'learning_rate': 0.01694683071232564, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 36, 'subsample': 0.864803089169032, 'colsample_bytree': 0.8187787356776066, 'reg_alpha': 0.9658611176861268, 'reg_lambda': 0.22965432344634354}. Best is trial 2 with value: 7.075667737225977.
[I 2026-07-01 20:11:21,162] Trial 10 finished with value: 7.967377056699307 and parameters: {'n_estimators': 1153, 'learning_rate': 0.04299365180018696, 'num_leaves': 86, 'max_depth': 16, 'min_child_samples': 55, 'subsample': 0.7876040334076363, 'colsample_bytree': 0.7736339155599743, 'reg_alpha': 0.00220909817911224, 'reg_lambda': 0.0018198804016875277}. Best is trial 2 with value: 7.075667737225977.
[I 2026-07-01 20:11:29,806] Trial 11 finished with value: 7.698930182455491 and parameters: {'n_estimators': 1050, 'learning_rate': 0.01759632190694596, 'num_leaves': 82, 'max_depth': 7, 'min_child_samples': 45, 'subsample': 0.9070634180020075, 'colsample_bytree': 0.8177541966531531, 'reg_alpha': 0.0029151336209232823, 'reg_lambda': 0.15776966061665512}. Best is trial 2 with value: 7.075667737225977.
[I 2026-07-01 20:11:31,159] Trial 12 finished with value: 7.068703772232129 and parameters: {'n_estimators': 356, 'learning_rate': 0.028789293195729152, 'num_leaves': 243, 'max_depth': 3, 'min_child_samples': 45, 'subsample': 0.8263406001124904, 'colsample_bytree': 0.7677472580741365, 'reg_alpha': 0.010414348488089444, 'reg_lambda': 0.0543643206248657}. Best is trial 12 with value: 7.068703772232129.
[I 2026-07-01 20:11:32,333] Trial 13 finished with value: 7.1671030250927465 and parameters: {'n_estimators': 306, 'learning_rate': 0.03332621380182769, 'num_leaves': 251, 'max_depth': 3, 'min_child_samples': 59, 'subsample': 0.713130793782095, 'colsample_bytree': 0.7206795810929609, 'reg_alpha': 0.008531827244426292, 'reg_lambda': 0.022799495708384795}. Best is trial 12 with value: 7.068703772232129.
[I 2026-07-01 20:11:34,657] Trial 14 finished with value: 8.7709953007149 and parameters: {'n_estimators': 393, 'learning_rate': 0.03185178154816806, 'num_leaves': 220, 'max_depth': 6, 'min_child_samples': 99, 'subsample': 0.8256139655211495, 'colsample_bytree': 0.6241927218500484, 'reg_alpha': 0.0001027126585086437, 'reg_lambda': 0.001778970555749303}. Best is trial 12 with value: 7.068703772232129.
[I 2026-07-01 20:11:36,556] Trial 15 finished with value: 7.139548208139529 and parameters: {'n_estimators': 675, 'learning_rate': 0.009801456458154847, 'num_leaves': 145, 'max_depth': 3, 'min_child_samples': 38, 'subsample': 0.663566191134094, 'colsample_bytree': 0.8875822299021946, 'reg_alpha': 0.05781585999721204, 'reg_lambda': 0.05168639575729877}. Best is trial 12 with value: 7.068703772232129.
[I 2026-07-01 20:11:38,887] Trial 16 finished with value: 7.243939036980173 and parameters: {'n_estimators': 412, 'learning_rate': 0.023283733882760654, 'num_leaves': 217, 'max_depth': 5, 'min_child_samples': 59, 'subsample': 0.9298249375977756, 'colsample_bytree': 0.7377718343784985, 'reg_alpha': 4.9671982886700604e-05, 'reg_lambda': 2.1511871576784976}. Best is trial 12 with value: 7.068703772232129.
[I 2026-07-01 20:11:41,326] Trial 17 finished with value: 7.441246203985315 and parameters: {'n_estimators': 230, 'learning_rate': 0.054470154313498824, 'num_leaves': 110, 'max_depth': 8, 'min_child_samples': 47, 'subsample': 0.687401502788238, 'colsample_bytree': 0.6391686706406166, 'reg_alpha': 0.04217603378728736, 'reg_lambda': 0.004538987841810493}. Best is trial 12 with value: 7.068703772232129.
[I 2026-07-01 20:11:42,644] Trial 18 finished with value: 7.108000736952872 and parameters: {'n_estimators': 419, 'learning_rate': 0.06259144416257827, 'num_leaves': 217, 'max_depth': 3, 'min_child_samples': 69, 'subsample': 0.7663857173908305, 'colsample_bytree': 0.7883475172837372, 'reg_alpha': 0.0004917690183780097, 'reg_lambda': 0.07323648917987068}. Best is trial 12 with value: 7.068703772232129.
[I 2026-07-01 20:11:49,080] Trial 19 finished with value: 7.604249225765293 and parameters: {'n_estimators': 675, 'learning_rate': 0.010512821368041273, 'num_leaves': 165, 'max_depth': 6, 'min_child_samples': 34, 'subsample': 0.6185673180365131, 'colsample_bytree': 0.8848283709261942, 'reg_alpha': 0.15614170146395748, 'reg_lambda': 0.005935052446528072}. Best is trial 12 with value: 7.068703772232129.
[I 2026-07-01 20:11:54,879] Trial 20 finished with value: 7.336741446193128 and parameters: {'n_estimators': 992, 'learning_rate': 0.02514690131435127, 'num_leaves': 123, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.8199212859905153, 'colsample_bytree': 0.8490483200027006, 'reg_alpha': 1.2722974438529106e-08, 'reg_lambda': 93.15666345772182}. Best is trial 12 with value: 7.068703772232129.
[I 2026-07-01 20:11:56,179] Trial 21 finished with value: 7.341003958027497 and parameters: {'n_estimators': 434, 'learning_rate': 0.07439518967059887, 'num_leaves': 220, 'max_depth': 3, 'min_child_samples': 72, 'subsample': 0.7463466848594026, 'colsample_bytree': 0.7689026146834644, 'reg_alpha': 0.0005419372305062861, 'reg_lambda': 0.05264928143493084}. Best is trial 12 with value: 7.068703772232129.
[I 2026-07-01 20:11:57,497] Trial 22 finished with value: 7.617732998719929 and parameters: {'n_estimators': 299, 'learning_rate': 0.1113569561187104, 'num_leaves': 210, 'max_depth': 4, 'min_child_samples': 68, 'subsample': 0.7695850126488888, 'colsample_bytree': 0.7715814021974424, 'reg_alpha': 0.01216456926221523, 'reg_lambda': 0.06704397696849347}. Best is trial 12 with value: 7.068703772232129.
[I 2026-07-01 20:11:59,251] Trial 23 finished with value: 8.800387424000265 and parameters: {'n_estimators': 488, 'learning_rate': 0.06594828267298708, 'num_leaves': 233, 'max_depth': 4, 'min_child_samples': 89, 'subsample': 0.8483485375016309, 'colsample_bytree': 0.6722525797708641, 'reg_alpha': 0.00033714761656287686, 'reg_lambda': 0.016502512029630417}. Best is trial 12 with value: 7.068703772232129.
[I 2026-07-01 20:12:00,529] Trial 24 finished with value: 7.075066173788476 and parameters: {'n_estimators': 323, 'learning_rate': 0.025490396784053015, 'num_leaves': 199, 'max_depth': 3, 'min_child_samples': 47, 'subsample': 0.706126381006446, 'colsample_bytree': 0.8113647618120301, 'reg_alpha': 1.4241485522323919e-05, 'reg_lambda': 0.09897244631772241}. Best is trial 12 with value: 7.068703772232129.
[I 2026-07-01 20:12:03,357] Trial 25 finished with value: 7.261545890108317 and parameters: {'n_estimators': 319, 'learning_rate': 0.023437631692761935, 'num_leaves': 196, 'max_depth': 6, 'min_child_samples': 48, 'subsample': 0.7013934786255549, 'colsample_bytree': 0.7209792926549343, 'reg_alpha': 3.4883831316707584e-06, 'reg_lambda': 0.7476572233039573}. Best is trial 12 with value: 7.068703772232129.
[I 2026-07-01 20:12:06,138] Trial 26 finished with value: 7.157423220047256 and parameters: {'n_estimators': 597, 'learning_rate': 0.010760217452468898, 'num_leaves': 171, 'max_depth': 4, 'min_child_samples': 33, 'subsample': 0.6306462289563238, 'colsample_bytree': 0.9282868341036222, 'reg_alpha': 1.8102318956258816e-07, 'reg_lambda': 0.18943312544339486}. Best is trial 12 with value: 7.068703772232129.
[I 2026-07-01 20:12:08,702] Trial 27 finished with value: 7.287558603972671 and parameters: {'n_estimators': 349, 'learning_rate': 0.027455748618032978, 'num_leaves': 162, 'max_depth': 5, 'min_child_samples': 28, 'subsample': 0.7249213664881258, 'colsample_bytree': 0.8316538322481921, 'reg_alpha': 4.4301703935691904e-05, 'reg_lambda': 0.004517394837795082}. Best is trial 12 with value: 7.068703772232129.
[I 2026-07-01 20:12:09,771] Trial 28 finished with value: 6.850010779235322 and parameters: {'n_estimators': 260, 'learning_rate': 0.04217893498224162, 'num_leaves': 236, 'max_depth': 3, 'min_child_samples': 43, 'subsample': 0.8018563602616556, 'colsample_bytree': 0.7390822046883281, 'reg_alpha': 0.34802592328439524, 'reg_lambda': 1.8862069393659242}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:12:10,979] Trial 29 finished with value: 7.223640459753725 and parameters: {'n_estimators': 248, 'learning_rate': 0.038408705040696316, 'num_leaves': 237, 'max_depth': 3, 'min_child_samples': 52, 'subsample': 0.9053257119593641, 'colsample_bytree': 0.8588508158300605, 'reg_alpha': 0.361864605016622, 'reg_lambda': 2.7890148488319024}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:12:14,536] Trial 30 finished with value: 7.847845978030119 and parameters: {'n_estimators': 482, 'learning_rate': 0.0854684970724203, 'num_leaves': 199, 'max_depth': 7, 'min_child_samples': 41, 'subsample': 0.8020063510956706, 'colsample_bytree': 0.5615546708760338, 'reg_alpha': 0.01820281380456528, 'reg_lambda': 3.4020886286678844}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:12:16,892] Trial 31 finished with value: 7.041312599034306 and parameters: {'n_estimators': 585, 'learning_rate': 0.020834352766379544, 'num_leaves': 235, 'max_depth': 4, 'min_child_samples': 43, 'subsample': 0.8656091560055121, 'colsample_bytree': 0.748029869452118, 'reg_alpha': 0.3732919348329788, 'reg_lambda': 1.086537673185858}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:12:18,244] Trial 32 finished with value: 6.961835397605988 and parameters: {'n_estimators': 361, 'learning_rate': 0.020384060565954345, 'num_leaves': 239, 'max_depth': 3, 'min_child_samples': 42, 'subsample': 0.8659520219550015, 'colsample_bytree': 0.8009098327851869, 'reg_alpha': 0.36346628427166644, 'reg_lambda': 1.0103971632719966}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:12:21,410] Trial 33 finished with value: 7.157147420049614 and parameters: {'n_estimators': 522, 'learning_rate': 0.021098858898207704, 'num_leaves': 254, 'max_depth': 5, 'min_child_samples': 41, 'subsample': 0.866689406747586, 'colsample_bytree': 0.7483426873558249, 'reg_alpha': 9.767962082369106, 'reg_lambda': 0.8834369392082966}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:12:22,749] Trial 34 finished with value: 7.214864359718682 and parameters: {'n_estimators': 269, 'learning_rate': 0.04986189792176524, 'num_leaves': 236, 'max_depth': 4, 'min_child_samples': 61, 'subsample': 0.9500120520031, 'colsample_bytree': 0.6955157205563561, 'reg_alpha': 0.38246240912535084, 'reg_lambda': 5.931791586297452}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:12:24,106] Trial 35 finished with value: 7.084507254386951 and parameters: {'n_estimators': 368, 'learning_rate': 0.03377558600065515, 'num_leaves': 237, 'max_depth': 3, 'min_child_samples': 27, 'subsample': 0.8837915656808787, 'colsample_bytree': 0.7892249508723267, 'reg_alpha': 0.3437834520365537, 'reg_lambda': 1.363246192252603}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:12:29,049] Trial 36 finished with value: 7.467570458701564 and parameters: {'n_estimators': 458, 'learning_rate': 0.019231075514739696, 'num_leaves': 230, 'max_depth': 6, 'min_child_samples': 15, 'subsample': 0.8360046442679454, 'colsample_bytree': 0.6428094717216615, 'reg_alpha': 1.5670012705730991, 'reg_lambda': 0.37970981171396845}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:12:31,975] Trial 37 finished with value: 7.148143457084864 and parameters: {'n_estimators': 738, 'learning_rate': 0.013807258454787762, 'num_leaves': 255, 'max_depth': 4, 'min_child_samples': 52, 'subsample': 0.9895459227837458, 'colsample_bytree': 0.7547581281477235, 'reg_alpha': 0.0028626377681631172, 'reg_lambda': 0.5745910893271609}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:12:35,084] Trial 38 finished with value: 7.210601121525237 and parameters: {'n_estimators': 550, 'learning_rate': 0.029057531903446475, 'num_leaves': 208, 'max_depth': 5, 'min_child_samples': 29, 'subsample': 0.9569782812941294, 'colsample_bytree': 0.7109089490119713, 'reg_alpha': 0.03278309157416213, 'reg_lambda': 7.014906789027841}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:12:47,212] Trial 39 finished with value: 7.615631427072562 and parameters: {'n_estimators': 599, 'learning_rate': 0.007221506421225635, 'num_leaves': 244, 'max_depth': 13, 'min_child_samples': 41, 'subsample': 0.7970361377522954, 'colsample_bytree': 0.661906688096511, 'reg_alpha': 3.2434935233292004, 'reg_lambda': 0.3607197596539209}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:12:48,697] Trial 40 finished with value: 11.235748644034809 and parameters: {'n_estimators': 203, 'learning_rate': 0.013128544043383908, 'num_leaves': 180, 'max_depth': 4, 'min_child_samples': 21, 'subsample': 0.8955911781258501, 'colsample_bytree': 0.7931431942057703, 'reg_alpha': 0.16885237768461114, 'reg_lambda': 1.3940716028708866}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:12:49,919] Trial 41 finished with value: 7.037132223268939 and parameters: {'n_estimators': 349, 'learning_rate': 0.038348196024825865, 'num_leaves': 201, 'max_depth': 3, 'min_child_samples': 45, 'subsample': 0.8579171210322628, 'colsample_bytree': 0.8108639340151321, 'reg_alpha': 1.0191612039916975e-05, 'reg_lambda': 0.11154121789690373}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:12:51,162] Trial 42 finished with value: 7.213196957151971 and parameters: {'n_estimators': 368, 'learning_rate': 0.04307136786651209, 'num_leaves': 227, 'max_depth': 3, 'min_child_samples': 53, 'subsample': 0.8572109344457194, 'colsample_bytree': 0.8490137770795801, 'reg_alpha': 6.036786505194712e-07, 'reg_lambda': 4.1561795467591205}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:12:52,426] Trial 43 finished with value: 7.107287809049484 and parameters: {'n_estimators': 260, 'learning_rate': 0.03623931461914648, 'num_leaves': 244, 'max_depth': 4, 'min_child_samples': 44, 'subsample': 0.8800805034378211, 'colsample_bytree': 0.7454925249752862, 'reg_alpha': 0.8801636891943773, 'reg_lambda': 0.26664219396855543}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:12:53,583] Trial 44 finished with value: 7.122444799359915 and parameters: {'n_estimators': 283, 'learning_rate': 0.05019956759655262, 'num_leaves': 209, 'max_depth': 3, 'min_child_samples': 36, 'subsample': 0.8134523780428222, 'colsample_bytree': 0.9301194397249982, 'reg_alpha': 5.520168428162705, 'reg_lambda': 0.03098931397501546}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:12:55,900] Trial 45 finished with value: 7.259311991814641 and parameters: {'n_estimators': 362, 'learning_rate': 0.018825872227465484, 'num_leaves': 225, 'max_depth': 5, 'min_child_samples': 62, 'subsample': 0.9260400193875254, 'colsample_bytree': 0.8007174564409899, 'reg_alpha': 0.00597029049503443, 'reg_lambda': 0.11085640649833216}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:12:57,866] Trial 46 finished with value: 7.135716832969247 and parameters: {'n_estimators': 452, 'learning_rate': 0.015584957403235329, 'num_leaves': 188, 'max_depth': 4, 'min_child_samples': 50, 'subsample': 0.8415902569403833, 'colsample_bytree': 0.6989851157289454, 'reg_alpha': 0.12044362764258289, 'reg_lambda': 1.3575730439509035}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:13:06,818] Trial 47 finished with value: 7.348322305229373 and parameters: {'n_estimators': 903, 'learning_rate': 0.02106066053692246, 'num_leaves': 244, 'max_depth': 11, 'min_child_samples': 39, 'subsample': 0.8733100753454851, 'colsample_bytree': 0.8268730978400535, 'reg_alpha': 9.641855431955306e-07, 'reg_lambda': 13.373486248724692}. Best is trial 28 with value: 6.850010779235322.
[I 2026-07-01 20:13:08,309] Trial 48 finished with value: 7.073443680501357 and parameters: {'n_estimators': 516, 'learning_rate': 0.02890819449502006, 'num_leaves': 200, 'max_depth': 3, 'min_child_samples': 56, 'subsample': 0.7763345663561164, 'colsample_bytree': 0.7680609215943228, 'reg_alpha': 1.0125176773187954, 'reg_lambda': 0.549594931691714}. Best is trial 28 with value: 6.850010779235322.

,fold,train_start_year,train_end_year,test_year,n_train,n_test,rmse,mae,mape,r2,direction_accuracy
0,fold_1,2012,2021,2022,2359,241,6.865507,5.357007,0.544195,0.904844,0.485477
1,fold_2,2012,2022,2023,2600,243,7.911162,6.034733,0.653094,0.968387,0.456790
2,fold_3,2012,2023,2024,2843,244,7.523443,5.738599,0.666132,0.970812,0.545082
3,fold_4,2012,2024,2025,3087,234,25.347479,17.175653,2.282998,0.751979,0.542735

## LSTM Optuna Tuning

40 trials per fold with early stopping. CUDA-enabled TensorFlow is used when available.

In [9]:
from models.tuned_strong_models import run_lstm_optuna

lstm_tuned_metrics = run_lstm_optuna()
lstm_tuned_metrics

lstm_optuna_full_ta:   0%|          | 0/4 [00:00<?, ?fold/s]

[I 2026-07-01 20:14:46,342] A new study created in RDB with name: lstm_optuna_full_ta_fold_1

  0%|          | 0/40 [00:00<?, ?it/s]

WARNING:tensorflow:From d:\conda_envs\my_env\Lib\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
[I 2026-07-01 20:15:12,556] Trial 0 finished with value: 0.023902741066000426 and parameters: {'sequence_length': 10, 'batch_size': 64, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.15212112147976886, 'learning_rate': 0.00037520558551242813}. Best is trial 0 with value: 0.023902741066000426.
[I 2026-07-01 20:15:22,027] Trial 1 finished with value: 0.1285945223670442 and parameters: {'sequence_length': 20, 'batch_size': 64, 'lstm_units': 64, 'dense_units': 64, 'dropout': 0.4828160165372797, 'learning_rate': 0.002661901888489057}. Best is trial 0 with value: 0.023902741066000426.
WARNING:tensorflow:5 out of the last 17 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000029B81C00E00> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
[I 2026-07-01 20:15:29,879] Trial 2 finished with value: 0.03647591859568368 and parameters: {'sequence_length': 20, 'batch_size': 64, 'lstm_units': 32, 'dense_units': 32, 'dropout': 0.46974947078209456, 'learning_rate': 0.004835952776465951}. Best is trial 0 with value: 0.023902741066000426.
WARNING:tensorflow:5 out of the last 17 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000029B846C7420> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
[I 2026-07-01 20:15:39,266] Trial 3 finished with value: 0.09552916790385059 and parameters: {'sequence_length': 10, 'batch_size': 32, 'lstm_units': 16, 'dense_units': 64, 'dropout': 0.3861223846483287, 'learning_rate': 3.9459088110999965e-05}. Best is trial 0 with value: 0.023902741066000426.
[I 2026-07-01 20:15:47,795] Trial 4 finished with value: 0.07579069430955562 and parameters: {'sequence_length': 10, 'batch_size': 32, 'lstm_units': 16, 'dense_units': 32, 'dropout': 0.44360637128816327, 'learning_rate': 0.00026100256506134784}. Best is trial 0 with value: 0.023902741066000426.
[I 2026-07-01 20:17:05,788] Trial 5 finished with value: 0.020438470306182673 and parameters: {'sequence_length': 60, 'batch_size': 32, 'lstm_units': 128, 'dense_units': 32, 'dropout': 0.20519146151781487, 'learning_rate': 0.0018477934173519257}. Best is trial 5 with value: 0.020438470306182673.
[I 2026-07-01 20:18:09,313] Trial 6 finished with value: 0.025366519128356562 and parameters: {'sequence_length': 60, 'batch_size': 64, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.11396758127097084, 'learning_rate': 0.00019112758217777883}. Best is trial 5 with value: 0.020438470306182673.
[I 2026-07-01 20:18:19,125] Trial 7 finished with value: 0.05326762942474984 and parameters: {'sequence_length': 10, 'batch_size': 64, 'lstm_units': 16, 'dense_units': 16, 'dropout': 0.24862425294619273, 'learning_rate': 7.991621920384351e-05}. Best is trial 5 with value: 0.020438470306182673.
[I 2026-07-01 20:18:40,744] Trial 8 finished with value: 0.0263733068052179 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.1838915663596266, 'learning_rate': 0.0007887102624766477}. Best is trial 5 with value: 0.020438470306182673.
[I 2026-07-01 20:19:10,748] Trial 9 finished with value: 0.13612803524458011 and parameters: {'sequence_length': 40, 'batch_size': 64, 'lstm_units': 16, 'dense_units': 32, 'dropout': 0.46836499436836726, 'learning_rate': 2.5856088907313374e-05}. Best is trial 5 with value: 0.020438470306182673.
[I 2026-07-01 20:24:27,720] Trial 10 finished with value: 0.024482295931273285 and parameters: {'sequence_length': 60, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.013481498198846309, 'learning_rate': 1.3066991237906997e-05}. Best is trial 5 with value: 0.020438470306182673.
[I 2026-07-01 20:24:46,261] Trial 11 finished with value: 0.020523698135592502 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.2711708762680812, 'learning_rate': 0.0012344334884639753}. Best is trial 5 with value: 0.020438470306182673.
[I 2026-07-01 20:25:05,631] Trial 12 finished with value: 0.019828271233541746 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.3003389316951688, 'learning_rate': 0.0012464402007299144}. Best is trial 12 with value: 0.019828271233541746.
[I 2026-07-01 20:25:25,685] Trial 13 finished with value: 0.020671572484570445 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.32475812872358506, 'learning_rate': 0.001647016384757289}. Best is trial 12 with value: 0.019828271233541746.
[I 2026-07-01 20:25:40,564] Trial 14 finished with value: 0.022959436634187917 and parameters: {'sequence_length': 5, 'batch_size': 32, 'lstm_units': 128, 'dense_units': 32, 'dropout': 0.3255079015857973, 'learning_rate': 0.009265673572687943}. Best is trial 12 with value: 0.019828271233541746.
[I 2026-07-01 20:26:43,328] Trial 15 finished with value: 0.027511516739941528 and parameters: {'sequence_length': 60, 'batch_size': 16, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.21627597785927438, 'learning_rate': 0.0007725268420504905}. Best is trial 12 with value: 0.019828271233541746.
[I 2026-07-01 20:27:10,228] Trial 16 finished with value: 0.03056444995786385 and parameters: {'sequence_length': 40, 'batch_size': 32, 'lstm_units': 128, 'dense_units': 32, 'dropout': 0.08172217993811001, 'learning_rate': 0.00325355887793862}. Best is trial 12 with value: 0.019828271233541746.
[I 2026-07-01 20:28:48,726] Trial 17 finished with value: 0.028648167792274828 and parameters: {'sequence_length': 60, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 64, 'dropout': 0.29927600439333824, 'learning_rate': 0.008087411777442793}. Best is trial 12 with value: 0.019828271233541746.
[I 2026-07-01 20:29:05,730] Trial 18 finished with value: 0.03341712057795795 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 32, 'dropout': 0.3805304594988682, 'learning_rate': 0.0005591555587645802}. Best is trial 12 with value: 0.019828271233541746.
[I 2026-07-01 20:29:22,862] Trial 19 finished with value: 0.027477870040773504 and parameters: {'sequence_length': 5, 'batch_size': 32, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.3818736974574263, 'learning_rate': 0.0017905716664152994}. Best is trial 12 with value: 0.019828271233541746.
[I 2026-07-01 20:30:43,348] Trial 20 finished with value: 0.025412533169952185 and parameters: {'sequence_length': 60, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 32, 'dropout': 0.2181030855185175, 'learning_rate': 0.00013058124159519505}. Best is trial 12 with value: 0.019828271233541746.
[I 2026-07-01 20:31:03,856] Trial 21 finished with value: 0.019702096908379256 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.284407931449867, 'learning_rate': 0.001271337172931067}. Best is trial 21 with value: 0.019702096908379256.
[I 2026-07-01 20:31:23,985] Trial 22 finished with value: 0.02034930269114537 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.2819118180218124, 'learning_rate': 0.0010290423859501763}. Best is trial 21 with value: 0.019702096908379256.
[I 2026-07-01 20:31:53,942] Trial 23 finished with value: 0.019567334884949092 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.2722422913821032, 'learning_rate': 0.0004758236058818598}. Best is trial 23 with value: 0.019567334884949092.
[I 2026-07-01 20:32:18,649] Trial 24 finished with value: 0.01934808194439046 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.3213827272429557, 'learning_rate': 0.00037068535458240423}. Best is trial 24 with value: 0.01934808194439046.
[I 2026-07-01 20:32:43,487] Trial 25 finished with value: 0.019290764053834928 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.3529617349136183, 'learning_rate': 0.0003837965157109993}. Best is trial 25 with value: 0.019290764053834928.
[I 2026-07-01 20:33:11,838] Trial 26 finished with value: 0.020716124181051926 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.3522061623439474, 'learning_rate': 8.321577076965547e-05}. Best is trial 25 with value: 0.019290764053834928.
[I 2026-07-01 20:33:35,705] Trial 27 finished with value: 0.023961438359890317 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 64, 'dense_units': 8, 'dropout': 0.4384086847209203, 'learning_rate': 0.0004338532155113108}. Best is trial 25 with value: 0.019290764053834928.
[I 2026-07-01 20:33:49,689] Trial 28 finished with value: 0.030601190104179245 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.35019970146027324, 'learning_rate': 0.00023907978266569284}. Best is trial 25 with value: 0.019290764053834928.
[I 2026-07-01 20:35:00,617] Trial 29 finished with value: 0.020390922876157718 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.14699726152679624, 'learning_rate': 0.00031610236674430297}. Best is trial 25 with value: 0.019290764053834928.
[I 2026-07-01 20:35:18,340] Trial 30 finished with value: 0.023191365736927576 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.4074136202529426, 'learning_rate': 0.00013669088340905142}. Best is trial 25 with value: 0.019290764053834928.
[I 2026-07-01 20:35:44,170] Trial 31 finished with value: 0.0194859373763123 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.25196510579859643, 'learning_rate': 0.0004369303143011154}. Best is trial 25 with value: 0.019290764053834928.
[I 2026-07-01 20:36:09,026] Trial 32 finished with value: 0.019340212064308665 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.25525714621134277, 'learning_rate': 0.0004895980498866062}. Best is trial 25 with value: 0.019290764053834928.
[I 2026-07-01 20:36:36,060] Trial 33 finished with value: 0.038219537835915245 and parameters: {'sequence_length': 20, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 64, 'dropout': 0.22943366809973745, 'learning_rate': 0.0005837306809710916}. Best is trial 25 with value: 0.019290764053834928.
[I 2026-07-01 20:36:53,748] Trial 34 finished with value: 0.02151753868051062 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.17011262102649838, 'learning_rate': 0.00034284886751824776}. Best is trial 25 with value: 0.019290764053834928.
[I 2026-07-01 20:37:12,366] Trial 35 finished with value: 0.028928809556397275 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 64, 'dense_units': 8, 'dropout': 0.24834459531144082, 'learning_rate': 0.00018706743538270473}. Best is trial 25 with value: 0.019290764053834928.
[I 2026-07-01 20:37:19,888] Trial 36 finished with value: 0.07790997628363557 and parameters: {'sequence_length': 10, 'batch_size': 64, 'lstm_units': 16, 'dense_units': 64, 'dropout': 0.33359087552267136, 'learning_rate': 8.09439232281447e-05}. Best is trial 25 with value: 0.019290764053834928.
[I 2026-07-01 20:38:29,962] Trial 37 finished with value: 0.02312938013423294 and parameters: {'sequence_length': 20, 'batch_size': 16, 'lstm_units': 32, 'dense_units': 16, 'dropout': 0.40715548079680763, 'learning_rate': 0.00013138483574979032}. Best is trial 25 with value: 0.019290764053834928.
[I 2026-07-01 20:38:47,505] Trial 38 finished with value: 0.021898005436398988 and parameters: {'sequence_length': 5, 'batch_size': 64, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.24292033723475165, 'learning_rate': 0.0007858605927052307}. Best is trial 25 with value: 0.019290764053834928.
[I 2026-07-01 20:39:17,178] Trial 39 finished with value: 0.023639074674642498 and parameters: {'sequence_length': 10, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.3547202417819114, 'learning_rate': 0.0030848831991867175}. Best is trial 25 with value: 0.019290764053834928.

[I 2026-07-01 20:39:34,788] A new study created in RDB with name: lstm_optuna_full_ta_fold_2

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-07-01 20:39:53,512] Trial 0 finished with value: 0.02180827746975274 and parameters: {'sequence_length': 10, 'batch_size': 64, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.15212112147976886, 'learning_rate': 0.00037520558551242813}. Best is trial 0 with value: 0.02180827746975274.
[I 2026-07-01 20:40:06,057] Trial 1 finished with value: 0.17589115804296848 and parameters: {'sequence_length': 20, 'batch_size': 64, 'lstm_units': 64, 'dense_units': 64, 'dropout': 0.4828160165372797, 'learning_rate': 0.002661901888489057}. Best is trial 0 with value: 0.02180827746975274.
[I 2026-07-01 20:40:17,360] Trial 2 finished with value: 0.14887226051331048 and parameters: {'sequence_length': 20, 'batch_size': 64, 'lstm_units': 32, 'dense_units': 32, 'dropout': 0.46974947078209456, 'learning_rate': 0.004835952776465951}. Best is trial 0 with value: 0.02180827746975274.
[I 2026-07-01 20:40:33,049] Trial 3 finished with value: 0.10108551877450264 and parameters: {'sequence_length': 10, 'batch_size': 32, 'lstm_units': 16, 'dense_units': 64, 'dropout': 0.3861223846483287, 'learning_rate': 3.9459088110999965e-05}. Best is trial 0 with value: 0.02180827746975274.
[I 2026-07-01 20:40:42,235] Trial 4 finished with value: 0.11139230970993991 and parameters: {'sequence_length': 10, 'batch_size': 32, 'lstm_units': 16, 'dense_units': 32, 'dropout': 0.44360637128816327, 'learning_rate': 0.00026100256506134784}. Best is trial 0 with value: 0.02180827746975274.
[I 2026-07-01 20:41:36,909] Trial 5 finished with value: 0.01798435621411446 and parameters: {'sequence_length': 60, 'batch_size': 32, 'lstm_units': 128, 'dense_units': 32, 'dropout': 0.20519146151781487, 'learning_rate': 0.0018477934173519257}. Best is trial 5 with value: 0.01798435621411446.
[I 2026-07-01 20:42:35,089] Trial 6 finished with value: 0.02090253677507713 and parameters: {'sequence_length': 60, 'batch_size': 64, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.11396758127097084, 'learning_rate': 0.00019112758217777883}. Best is trial 5 with value: 0.01798435621411446.
[I 2026-07-01 20:42:50,171] Trial 7 finished with value: 0.03966382120502499 and parameters: {'sequence_length': 10, 'batch_size': 64, 'lstm_units': 16, 'dense_units': 16, 'dropout': 0.24862425294619273, 'learning_rate': 7.991621920384351e-05}. Best is trial 5 with value: 0.01798435621411446.
[I 2026-07-01 20:43:12,880] Trial 8 finished with value: 0.020470717284725402 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.1838915663596266, 'learning_rate': 0.0007887102624766477}. Best is trial 5 with value: 0.01798435621411446.
[I 2026-07-01 20:43:53,368] Trial 9 finished with value: 0.09651238204877552 and parameters: {'sequence_length': 40, 'batch_size': 64, 'lstm_units': 16, 'dense_units': 32, 'dropout': 0.46836499436836726, 'learning_rate': 2.5856088907313374e-05}. Best is trial 5 with value: 0.01798435621411446.
[I 2026-07-01 20:49:13,526] Trial 10 finished with value: 0.016762601124148086 and parameters: {'sequence_length': 60, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.013481498198846309, 'learning_rate': 1.3066991237906997e-05}. Best is trial 10 with value: 0.016762601124148086.
[I 2026-07-01 20:52:38,161] Trial 11 finished with value: 0.019092130064507235 and parameters: {'sequence_length': 60, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.006629411010525577, 'learning_rate': 1.162945111233365e-05}. Best is trial 10 with value: 0.016762601124148086.
[I 2026-07-01 20:53:29,167] Trial 12 finished with value: 0.05745651793984646 and parameters: {'sequence_length': 60, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.011884215729813852, 'learning_rate': 0.009599039930558028}. Best is trial 10 with value: 0.016762601124148086.
[I 2026-07-01 20:54:00,378] Trial 13 finished with value: 0.018856348181168287 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.2982272487498798, 'learning_rate': 0.0013797582287223714}. Best is trial 10 with value: 0.016762601124148086.
[I 2026-07-01 20:54:45,667] Trial 14 finished with value: 0.0360694918662681 and parameters: {'sequence_length': 60, 'batch_size': 32, 'lstm_units': 128, 'dense_units': 32, 'dropout': 0.08560194923880426, 'learning_rate': 1.0531752168620763e-05}. Best is trial 10 with value: 0.016762601124148086.
[I 2026-07-01 20:55:27,218] Trial 15 finished with value: 0.04132710445083679 and parameters: {'sequence_length': 60, 'batch_size': 16, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.24854269680542623, 'learning_rate': 8.513569413752787e-05}. Best is trial 10 with value: 0.016762601124148086.
[I 2026-07-01 20:55:45,973] Trial 16 finished with value: 0.025179640834448746 and parameters: {'sequence_length': 5, 'batch_size': 32, 'lstm_units': 128, 'dense_units': 32, 'dropout': 0.3479480324927363, 'learning_rate': 0.0008988429017913118}. Best is trial 10 with value: 0.016762601124148086.
[I 2026-07-01 20:57:19,433] Trial 17 finished with value: 0.01678438136952778 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 64, 'dropout': 0.05515237704562756, 'learning_rate': 0.00011760689490040737}. Best is trial 10 with value: 0.016762601124148086.
[I 2026-07-01 20:58:55,584] Trial 18 finished with value: 0.018115017371361362 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 64, 'dropout': 0.07079212082617564, 'learning_rate': 2.999426287672026e-05}. Best is trial 10 with value: 0.016762601124148086.
[I 2026-07-01 20:59:22,116] Trial 19 finished with value: 0.03163335843676007 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 32, 'dense_units': 64, 'dropout': 0.05066515165687713, 'learning_rate': 0.00010914076415020937}. Best is trial 10 with value: 0.016762601124148086.
[I 2026-07-01 21:00:25,580] Trial 20 finished with value: 0.023922482898496456 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 64, 'dropout': 0.13314450068024186, 'learning_rate': 4.910650006542589e-05}. Best is trial 10 with value: 0.016762601124148086.
[I 2026-07-01 21:01:27,477] Trial 21 finished with value: 0.028024674331329078 and parameters: {'sequence_length': 60, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 64, 'dropout': 0.17337560956690612, 'learning_rate': 0.000494963063638513}. Best is trial 10 with value: 0.016762601124148086.
[I 2026-07-01 21:03:07,649] Trial 22 finished with value: 0.03165764742204939 and parameters: {'sequence_length': 60, 'batch_size': 32, 'lstm_units': 128, 'dense_units': 32, 'dropout': 0.2123596923139639, 'learning_rate': 1.752936013651441e-05}. Best is trial 10 with value: 0.016762601124148086.
[I 2026-07-01 21:04:17,529] Trial 23 finished with value: 0.017529043475442423 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.03669054391858073, 'learning_rate': 0.00015955069964515277}. Best is trial 10 with value: 0.016762601124148086.
[I 2026-07-01 21:06:19,334] Trial 24 finished with value: 0.01589367356709787 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.05006717654415576, 'learning_rate': 0.00014713163820062985}. Best is trial 24 with value: 0.01589367356709787.
[I 2026-07-01 21:07:33,803] Trial 25 finished with value: 0.02078075199160692 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.10254758445175913, 'learning_rate': 5.3213982579797176e-05}. Best is trial 24 with value: 0.01589367356709787.
[I 2026-07-01 21:11:38,019] Trial 26 finished with value: 0.014507467534627425 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.04652585475560228, 'learning_rate': 2.0535129450052764e-05}. Best is trial 26 with value: 0.014507467534627425.
[I 2026-07-01 21:13:51,792] Trial 27 finished with value: 0.017660689875964607 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.008679201752884419, 'learning_rate': 1.8916472289275966e-05}. Best is trial 26 with value: 0.014507467534627425.
[I 2026-07-01 21:14:50,365] Trial 28 finished with value: 0.021645290426272168 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 64, 'dense_units': 8, 'dropout': 0.08623132607534031, 'learning_rate': 1.6150437373608145e-05}. Best is trial 26 with value: 0.014507467534627425.
[I 2026-07-01 21:15:48,494] Trial 29 finished with value: 0.01644350350874891 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.04093781047720314, 'learning_rate': 0.00035751373396584465}. Best is trial 26 with value: 0.014507467534627425.
[I 2026-07-01 21:17:14,533] Trial 30 finished with value: 0.017588919765812328 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.12786936531633533, 'learning_rate': 0.0004992545112864195}. Best is trial 26 with value: 0.014507467534627425.
[I 2026-07-01 21:18:25,386] Trial 31 finished with value: 0.01792632683064719 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.04161417658830166, 'learning_rate': 0.00029965847656455617}. Best is trial 26 with value: 0.014507467534627425.
[I 2026-07-01 21:20:23,818] Trial 32 finished with value: 0.01872814116412604 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.0010154609459638517, 'learning_rate': 2.700277383348252e-05}. Best is trial 26 with value: 0.014507467534627425.
[I 2026-07-01 21:21:06,323] Trial 33 finished with value: 0.019173302384212425 and parameters: {'sequence_length': 20, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.03830694635555079, 'learning_rate': 0.00019234719173395987}. Best is trial 26 with value: 0.014507467534627425.
[I 2026-07-01 21:22:27,388] Trial 34 finished with value: 0.01746819441774159 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.1558607025531843, 'learning_rate': 0.00041714131269219966}. Best is trial 26 with value: 0.014507467534627425.
[I 2026-07-01 21:22:54,810] Trial 35 finished with value: 0.023647600453210793 and parameters: {'sequence_length': 10, 'batch_size': 16, 'lstm_units': 64, 'dense_units': 8, 'dropout': 0.06600645074463281, 'learning_rate': 5.840786287648196e-05}. Best is trial 26 with value: 0.014507467534627425.
[I 2026-07-01 21:23:05,926] Trial 36 finished with value: 0.024876703045347785 and parameters: {'sequence_length': 20, 'batch_size': 64, 'lstm_units': 16, 'dense_units': 8, 'dropout': 0.08611481870849179, 'learning_rate': 0.004216910458833386}. Best is trial 26 with value: 0.014507467534627425.
[I 2026-07-01 21:24:35,734] Trial 37 finished with value: 0.018257420821258027 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.02478831693921655, 'learning_rate': 3.750229834955588e-05}. Best is trial 26 with value: 0.014507467534627425.
[I 2026-07-01 21:24:55,121] Trial 38 finished with value: 0.018699309994850574 and parameters: {'sequence_length': 10, 'batch_size': 64, 'lstm_units': 128, 'dense_units': 16, 'dropout': 0.11364969016490364, 'learning_rate': 0.0007247396504365901}. Best is trial 26 with value: 0.014507467534627425.
[I 2026-07-01 21:26:07,727] Trial 39 finished with value: 0.017831642311293153 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.071040611120824, 'learning_rate': 0.000283745774189231}. Best is trial 26 with value: 0.014507467534627425.

[I 2026-07-01 21:30:26,590] A new study created in RDB with name: lstm_optuna_full_ta_fold_3

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-07-01 21:30:47,939] Trial 0 finished with value: 0.019447042562758317 and parameters: {'sequence_length': 10, 'batch_size': 64, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.15212112147976886, 'learning_rate': 0.00037520558551242813}. Best is trial 0 with value: 0.019447042562758317.
[I 2026-07-01 21:30:58,476] Trial 1 finished with value: 0.0651931666466105 and parameters: {'sequence_length': 20, 'batch_size': 64, 'lstm_units': 64, 'dense_units': 64, 'dropout': 0.4828160165372797, 'learning_rate': 0.002661901888489057}. Best is trial 0 with value: 0.019447042562758317.
[I 2026-07-01 21:31:10,065] Trial 2 finished with value: 0.1555626120189553 and parameters: {'sequence_length': 20, 'batch_size': 64, 'lstm_units': 32, 'dense_units': 32, 'dropout': 0.46974947078209456, 'learning_rate': 0.004835952776465951}. Best is trial 0 with value: 0.019447042562758317.
[I 2026-07-01 21:31:22,166] Trial 3 finished with value: 0.07560043724240004 and parameters: {'sequence_length': 10, 'batch_size': 32, 'lstm_units': 16, 'dense_units': 64, 'dropout': 0.3861223846483287, 'learning_rate': 3.9459088110999965e-05}. Best is trial 0 with value: 0.019447042562758317.
[I 2026-07-01 21:31:33,000] Trial 4 finished with value: 0.108494979347915 and parameters: {'sequence_length': 10, 'batch_size': 32, 'lstm_units': 16, 'dense_units': 32, 'dropout': 0.44360637128816327, 'learning_rate': 0.00026100256506134784}. Best is trial 0 with value: 0.019447042562758317.
[I 2026-07-01 21:32:39,082] Trial 5 finished with value: 0.02011555343105636 and parameters: {'sequence_length': 60, 'batch_size': 32, 'lstm_units': 128, 'dense_units': 32, 'dropout': 0.20519146151781487, 'learning_rate': 0.0018477934173519257}. Best is trial 0 with value: 0.019447042562758317.
[I 2026-07-01 21:33:35,639] Trial 6 finished with value: 0.025853914020595635 and parameters: {'sequence_length': 60, 'batch_size': 64, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.11396758127097084, 'learning_rate': 0.00019112758217777883}. Best is trial 0 with value: 0.019447042562758317.
[I 2026-07-01 21:33:49,564] Trial 7 finished with value: 0.0384186064486798 and parameters: {'sequence_length': 10, 'batch_size': 64, 'lstm_units': 16, 'dense_units': 16, 'dropout': 0.24862425294619273, 'learning_rate': 7.991621920384351e-05}. Best is trial 0 with value: 0.019447042562758317.
[I 2026-07-01 21:34:31,002] Trial 8 finished with value: 0.016620225216255134 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.1838915663596266, 'learning_rate': 0.0007887102624766477}. Best is trial 8 with value: 0.016620225216255134.
[I 2026-07-01 21:35:07,176] Trial 9 finished with value: 0.07452005508256807 and parameters: {'sequence_length': 40, 'batch_size': 64, 'lstm_units': 16, 'dense_units': 32, 'dropout': 0.46836499436836726, 'learning_rate': 2.5856088907313374e-05}. Best is trial 8 with value: 0.016620225216255134.
[I 2026-07-01 21:36:19,894] Trial 10 finished with value: 0.01877124474540854 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.012655944988151896, 'learning_rate': 1.3066991237906997e-05}. Best is trial 8 with value: 0.016620225216255134.
[I 2026-07-01 21:37:31,938] Trial 11 finished with value: 0.018912269111796578 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.00597683623497901, 'learning_rate': 1.1504969529312768e-05}. Best is trial 8 with value: 0.016620225216255134.
[I 2026-07-01 21:38:09,706] Trial 12 finished with value: 0.016370462098739498 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.011047387056492719, 'learning_rate': 0.0006428109236651996}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:38:49,992] Trial 13 finished with value: 0.028157486168431188 and parameters: {'sequence_length': 20, 'batch_size': 16, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.30453693171687224, 'learning_rate': 0.0008913219027828401}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:39:09,716] Trial 14 finished with value: 0.017175493293494756 and parameters: {'sequence_length': 5, 'batch_size': 32, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.08560194923880415, 'learning_rate': 0.000705317065129345}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:39:41,491] Trial 15 finished with value: 0.09010304851500163 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.31640039234815737, 'learning_rate': 0.00954734885266649}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:40:33,636] Trial 16 finished with value: 0.02036750193376055 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.06238198338313054, 'learning_rate': 0.0009075617791986357}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:40:51,723] Trial 17 finished with value: 0.027001930548026402 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.23398713286637104, 'learning_rate': 0.00014250642953918095}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:41:33,251] Trial 18 finished with value: 0.031937828528214744 and parameters: {'sequence_length': 20, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 64, 'dropout': 0.1531221286499026, 'learning_rate': 0.0004710476287602335}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:41:52,964] Trial 19 finished with value: 0.016781870223898807 and parameters: {'sequence_length': 5, 'batch_size': 32, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.16399266073423108, 'learning_rate': 0.0017905716664152994}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:44:39,310] Trial 20 finished with value: 0.017197973076162342 and parameters: {'sequence_length': 60, 'batch_size': 16, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.05475959843790629, 'learning_rate': 7.490618733452137e-05}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:44:57,587] Trial 21 finished with value: 0.016853875433005358 and parameters: {'sequence_length': 5, 'batch_size': 32, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.1806902038594426, 'learning_rate': 0.0018541854069368236}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:45:07,894] Trial 22 finished with value: 0.03748236344920513 and parameters: {'sequence_length': 5, 'batch_size': 32, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.2895544449115969, 'learning_rate': 0.0013586653276318362}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:45:22,755] Trial 23 finished with value: 0.020902667811560475 and parameters: {'sequence_length': 5, 'batch_size': 32, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.11688650519363973, 'learning_rate': 0.0036486231972757944}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:45:33,798] Trial 24 finished with value: 0.03577156571447496 and parameters: {'sequence_length': 5, 'batch_size': 32, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.35376290572932123, 'learning_rate': 0.0004476051794126485}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:45:59,318] Trial 25 finished with value: 0.02763466516816182 and parameters: {'sequence_length': 40, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.23983053363110995, 'learning_rate': 0.005706623648481579}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:46:19,314] Trial 26 finished with value: 0.03464811873806629 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.17888902686498986, 'learning_rate': 0.0012271830339996958}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:46:49,487] Trial 27 finished with value: 0.025741339648169485 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 64, 'dropout': 0.12231007636409376, 'learning_rate': 0.002401390965621554}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:47:09,816] Trial 28 finished with value: 0.022728473361068598 and parameters: {'sequence_length': 5, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.04378325725526441, 'learning_rate': 0.000719709102697541}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:47:45,025] Trial 29 finished with value: 0.02188210908502397 and parameters: {'sequence_length': 20, 'batch_size': 16, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.15217161385368613, 'learning_rate': 0.0002922208048572486}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:48:06,996] Trial 30 finished with value: 0.028612378942242042 and parameters: {'sequence_length': 40, 'batch_size': 32, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.19814885268312285, 'learning_rate': 0.0004542732765482508}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:48:23,042] Trial 31 finished with value: 0.018633212838172312 and parameters: {'sequence_length': 5, 'batch_size': 32, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.18549197405683204, 'learning_rate': 0.0017995268854751134}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:48:37,032] Trial 32 finished with value: 0.0357954338457478 and parameters: {'sequence_length': 5, 'batch_size': 32, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.26167203736598044, 'learning_rate': 0.0012674119950487831}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:48:56,455] Trial 33 finished with value: 0.016398290268931026 and parameters: {'sequence_length': 5, 'batch_size': 32, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.08733666380782659, 'learning_rate': 0.003206660979914573}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:49:12,894] Trial 34 finished with value: 0.022949714164808423 and parameters: {'sequence_length': 5, 'batch_size': 32, 'lstm_units': 32, 'dense_units': 64, 'dropout': 0.08857770864181151, 'learning_rate': 0.0034920417970899327}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:49:29,334] Trial 35 finished with value: 0.022561751514108087 and parameters: {'sequence_length': 10, 'batch_size': 64, 'lstm_units': 64, 'dense_units': 8, 'dropout': 0.024454215537737328, 'learning_rate': 0.006494893323897845}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:49:48,154] Trial 36 finished with value: 0.039335677996653724 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 16, 'dense_units': 32, 'dropout': 0.10139039836071512, 'learning_rate': 0.0030441677598746528}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:50:31,511] Trial 37 finished with value: 0.021247645133180098 and parameters: {'sequence_length': 60, 'batch_size': 32, 'lstm_units': 32, 'dense_units': 16, 'dropout': 0.13925114521861506, 'learning_rate': 0.008597334089418936}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:50:45,535] Trial 38 finished with value: 0.020462325747240637 and parameters: {'sequence_length': 5, 'batch_size': 64, 'lstm_units': 64, 'dense_units': 32, 'dropout': 0.07224983541543306, 'learning_rate': 0.004244051876946829}. Best is trial 12 with value: 0.016370462098739498.
[I 2026-07-01 21:51:08,503] Trial 39 finished with value: 0.02343872351655837 and parameters: {'sequence_length': 10, 'batch_size': 32, 'lstm_units': 16, 'dense_units': 64, 'dropout': 0.03341918527774374, 'learning_rate': 0.0006320093368078156}. Best is trial 12 with value: 0.016370462098739498.

[I 2026-07-01 21:51:38,568] A new study created in RDB with name: lstm_optuna_full_ta_fold_4

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-07-01 21:51:59,849] Trial 0 finished with value: 0.02229576671364159 and parameters: {'sequence_length': 10, 'batch_size': 64, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.15212112147976886, 'learning_rate': 0.00037520558551242813}. Best is trial 0 with value: 0.02229576671364159.
[I 2026-07-01 21:52:21,183] Trial 1 finished with value: 0.05806094645772018 and parameters: {'sequence_length': 20, 'batch_size': 64, 'lstm_units': 64, 'dense_units': 64, 'dropout': 0.4828160165372797, 'learning_rate': 0.002661901888489057}. Best is trial 0 with value: 0.02229576671364159.
[I 2026-07-01 21:52:32,630] Trial 2 finished with value: 0.0853207967599536 and parameters: {'sequence_length': 20, 'batch_size': 64, 'lstm_units': 32, 'dense_units': 32, 'dropout': 0.46974947078209456, 'learning_rate': 0.004835952776465951}. Best is trial 0 with value: 0.02229576671364159.
[I 2026-07-01 21:52:46,511] Trial 3 finished with value: 0.07314370450823653 and parameters: {'sequence_length': 10, 'batch_size': 32, 'lstm_units': 16, 'dense_units': 64, 'dropout': 0.3861223846483287, 'learning_rate': 3.9459088110999965e-05}. Best is trial 0 with value: 0.02229576671364159.
[I 2026-07-01 21:52:58,102] Trial 4 finished with value: 0.06728545406182815 and parameters: {'sequence_length': 10, 'batch_size': 32, 'lstm_units': 16, 'dense_units': 32, 'dropout': 0.44360637128816327, 'learning_rate': 0.00026100256506134784}. Best is trial 0 with value: 0.02229576671364159.
[I 2026-07-01 21:54:32,976] Trial 5 finished with value: 0.01608558520948272 and parameters: {'sequence_length': 60, 'batch_size': 32, 'lstm_units': 128, 'dense_units': 32, 'dropout': 0.20519146151781487, 'learning_rate': 0.0018477934173519257}. Best is trial 5 with value: 0.01608558520948272.
[I 2026-07-01 21:55:53,088] Trial 6 finished with value: 0.01508950311977784 and parameters: {'sequence_length': 60, 'batch_size': 64, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.11396758127097084, 'learning_rate': 0.00019112758217777883}. Best is trial 6 with value: 0.01508950311977784.
[I 2026-07-01 21:56:08,020] Trial 7 finished with value: 0.040780192186568524 and parameters: {'sequence_length': 10, 'batch_size': 64, 'lstm_units': 16, 'dense_units': 16, 'dropout': 0.24862425294619273, 'learning_rate': 7.991621920384351e-05}. Best is trial 6 with value: 0.01508950311977784.
[I 2026-07-01 21:57:04,483] Trial 8 finished with value: 0.014327793580579949 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.1838915663596266, 'learning_rate': 0.0007887102624766477}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 21:57:45,969] Trial 9 finished with value: 0.059378969026328 and parameters: {'sequence_length': 40, 'batch_size': 64, 'lstm_units': 16, 'dense_units': 32, 'dropout': 0.46836499436836726, 'learning_rate': 2.5856088907313374e-05}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 21:58:24,797] Trial 10 finished with value: 0.021198429211394927 and parameters: {'sequence_length': 5, 'batch_size': 16, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.012655944988151896, 'learning_rate': 1.3066991237906997e-05}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 21:59:13,274] Trial 11 finished with value: 0.023972271841204672 and parameters: {'sequence_length': 60, 'batch_size': 16, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.08289809345055665, 'learning_rate': 0.00047377723860348293}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:00:16,999] Trial 12 finished with value: 0.018538785034594645 and parameters: {'sequence_length': 60, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.2866454888256146, 'learning_rate': 0.0008881452685880727}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:01:22,178] Trial 13 finished with value: 0.019490730979886295 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.11976471519554416, 'learning_rate': 0.00013566969734149202}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:02:10,755] Trial 14 finished with value: 0.019576166513793496 and parameters: {'sequence_length': 40, 'batch_size': 16, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.039231192483390354, 'learning_rate': 0.0010040072096533224}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:02:22,204] Trial 15 finished with value: 0.030725844314177995 and parameters: {'sequence_length': 5, 'batch_size': 64, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.1659201761136143, 'learning_rate': 0.009624035520105533}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:03:30,873] Trial 16 finished with value: 0.015164798051550602 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.31554217176948246, 'learning_rate': 0.00014241765197752483}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:04:13,758] Trial 17 finished with value: 0.016549825153158566 and parameters: {'sequence_length': 60, 'batch_size': 64, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.07475746683927306, 'learning_rate': 0.0007321870723636994}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:04:46,824] Trial 18 finished with value: 0.022423261320421543 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 128, 'dense_units': 64, 'dropout': 0.21242838706552367, 'learning_rate': 0.0002012255315945799}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:07:28,282] Trial 19 finished with value: 0.018851759869829975 and parameters: {'sequence_length': 60, 'batch_size': 16, 'lstm_units': 32, 'dense_units': 8, 'dropout': 0.330299622914229, 'learning_rate': 6.045559407991243e-05}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:07:40,171] Trial 20 finished with value: 0.019244370722825508 and parameters: {'sequence_length': 5, 'batch_size': 64, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.1331445006802418, 'learning_rate': 0.0015909557960219153}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:08:35,984] Trial 21 finished with value: 0.015806762701903662 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.3397801128688077, 'learning_rate': 0.0001279757539213176}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:09:21,697] Trial 22 finished with value: 0.017259151641529948 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.2678739784719391, 'learning_rate': 0.00037317627346628035}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:10:05,573] Trial 23 finished with value: 0.015756091238087112 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.1897302810906769, 'learning_rate': 0.00015955069964515277}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:11:01,278] Trial 24 finished with value: 0.01960832833693928 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.09805729097471005, 'learning_rate': 7.129852748729186e-05}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:11:53,571] Trial 25 finished with value: 0.02022451633326149 and parameters: {'sequence_length': 40, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.4035097890855752, 'learning_rate': 0.0005860788519631716}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:13:36,598] Trial 26 finished with value: 0.016871906009317678 and parameters: {'sequence_length': 60, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.3046025447176717, 'learning_rate': 0.0002575361027088518}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:15:04,545] Trial 27 finished with value: 0.018376918193923626 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.2287086675172635, 'learning_rate': 2.5835043782260548e-05}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:15:24,152] Trial 28 finished with value: 0.04592905169490181 and parameters: {'sequence_length': 20, 'batch_size': 16, 'lstm_units': 32, 'dense_units': 64, 'dropout': 0.37685750075526586, 'learning_rate': 9.45981482833579e-05}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:16:40,804] Trial 29 finished with value: 0.019654267302352157 and parameters: {'sequence_length': 60, 'batch_size': 64, 'lstm_units': 128, 'dense_units': 8, 'dropout': 0.1664693136039274, 'learning_rate': 0.0002875802631282412}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:16:52,375] Trial 30 finished with value: 0.019822737273124502 and parameters: {'sequence_length': 5, 'batch_size': 64, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.03855775142978718, 'learning_rate': 0.0013171133143615333}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:17:46,718] Trial 31 finished with value: 0.015406586553840917 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.20319238100737994, 'learning_rate': 0.0001612241290046286}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:18:55,382] Trial 32 finished with value: 0.015858612999204526 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.13296258845056075, 'learning_rate': 4.549487650915941e-05}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:19:25,769] Trial 33 finished with value: 0.023571928789569326 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.26121673946587814, 'learning_rate': 0.0034051520916194198}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:19:53,574] Trial 34 finished with value: 0.01993192833261572 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 64, 'dense_units': 64, 'dropout': 0.18107957632248534, 'learning_rate': 0.00041714131269219966}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:20:24,028] Trial 35 finished with value: 0.020455879436025514 and parameters: {'sequence_length': 10, 'batch_size': 64, 'lstm_units': 64, 'dense_units': 16, 'dropout': 0.23084756173292895, 'learning_rate': 0.00010955551767292576}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:20:54,194] Trial 36 finished with value: 0.03163999354057795 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 16, 'dense_units': 32, 'dropout': 0.10730145013943673, 'learning_rate': 0.00019934371647827058}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:21:36,876] Trial 37 finished with value: 0.019235970565889753 and parameters: {'sequence_length': 20, 'batch_size': 32, 'lstm_units': 32, 'dense_units': 16, 'dropout': 0.1435189486447328, 'learning_rate': 0.0022717187782691282}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:22:23,443] Trial 38 finished with value: 0.01889216007333248 and parameters: {'sequence_length': 10, 'batch_size': 64, 'lstm_units': 64, 'dense_units': 32, 'dropout': 0.06134944025084077, 'learning_rate': 3.6554825107497615e-05}. Best is trial 8 with value: 0.014327793580579949.
[I 2026-07-01 22:22:40,114] Trial 39 finished with value: 0.08347456215362362 and parameters: {'sequence_length': 40, 'batch_size': 32, 'lstm_units': 16, 'dense_units': 64, 'dropout': 0.4269058490618016, 'learning_rate': 0.0002732963314979759}. Best is trial 8 with value: 0.014327793580579949.
     fold  train_start_year  train_end_year  test_year  n_train  n_test  \
0  fold_1              2012            2021       2022     2359     241
1  fold_2              2012            2022       2023     2600     243
2  fold_3              2012            2023       2024     2843     244
3  fold_4              2012            2024       2025     3087     234

        rmse        mae      mape        r2  direction_accuracy
0  12.143682   9.846038  1.002601  0.702292            0.506224
1   9.918180   8.030185  0.863099  0.950312            0.559671
2  10.504085   8.431535  0.985052  0.943103            0.524590
3  26.845539  20.594316  2.694955  0.721796            0.547009
      train_start_year  train_end_year  test_year  n_train  n_test       rmse  \
mean            2012.0          2022.5     2023.5  2722.25   240.5  14.852871

            mae      mape        r2  direction_accuracy
mean  11.725519  1.386427  0.829376            0.534373

,fold,train_start_year,train_end_year,test_year,n_train,n_test,rmse,mae,mape,r2,direction_accuracy
0,fold_1,2012,2021,2022,2359,241,12.143682,9.846038,1.002601,0.702292,0.506224
1,fold_2,2012,2022,2023,2600,243,9.918180,8.030185,0.863099,0.950312,0.559671
2,fold_3,2012,2023,2024,2843,244,10.504085,8.431535,0.985052,0.943103,0.524590
3,fold_4,2012,2024,2025,3087,234,26.845539,20.594316,2.694955,0.721796,0.547009

## AutoGluon Tabular Strong Setting

`presets="high_quality"`, 300 seconds per fold, Full TA data.

In [ ]:
from models.tuned_strong_models import run_autogluon_tabular_strong

autogluon_tabular_metrics = run_autogluon_tabular_strong()
autogluon_tabular_metrics

autogluon_tabular_high_quality:   0%|          | 0/4 [00:00<?, ?fold/s]

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.15
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          16
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       1.24 GB / 15.19 GB (8.2%)
Disk Space Avail:   79.45 GB / 274.70 GB (28.9%)
===================================================
Presets specified: ['high_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 75s of the 300s of remaining time (25%).
Running DyStack sub-fit ...
Beginning AutoGluon training ... Time limit = 75s
AutoGluon will save models to "D:\SET50_direction_prediction_paper\outputs\tuned_strong_models\autogluon_tabular_high_quality\models\fold_1\ds_sub_fit\sub_fit_ho"
Train Data Rows:    2096
Train Data Columns: 116
Label Column:       Target_Next_Close
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    1331.93 MB
	Train Data (Original)  Memory Usage: 1.86 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 116 | ['Open_D', 'High_D', 'Low_D', 'Close_D', 'Volume_D', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 116 | ['Open_D', 'High_D', 'Low_D', 'Close_D', 'Volume_D', ...]
	0.2s = Fit runtime
	116 features in original data used to generate 116 features in processed data.
	Train Data (Processed) Memory Usage: 1.86 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.18s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 49.86s of the 74.80s of remaining time.
Specified total num_gpus: 1, but only 0 are available. Will use 0 instead
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=3.69%)
d:\conda_envs\my_env\Lib\site-packages\ray\_private\worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
	-10.658	 = Validation score   (-root_mean_squared_error)
	4.49s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 20.28s of the 45.21s of remaining time.
Specified total num_gpus: 1, but only 0 are available. Will use 0 instead
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=3.37%)
	-10.9225	 = Validation score   (-root_mean_squared_error)
	5.29s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 8.01s of the 32.95s of remaining time.
Specified total num_gpus: 1, but only 0 are available. Will use 0 instead
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0, mem=0.0/1.9 GB
	-10.8774	 = Validation score   (-root_mean_squared_error)
	5.53s	 = Training   runtime
	0.29s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 2.03s of the 26.97s of remaining time.
Specified total num_gpus: 1, but only 0 are available. Will use 0 instead
	Memory not enough to fit 8 folds in parallel. Will train 2 folds in parallel instead (Estimated 28.13% memory usage per fold, 56.27%/80.00% total).
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=8, gpus=0, memory=28.13%)
	Time limit exceeded... Skipping CatBoost_BAG_L1.
Fitting model: WeightedEnsemble_L2 ... Training model for up to 74.82s of the 16.16s of remaining time.
Specified total num_gpus: 1, but only 0 are available. Will use 0 instead
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/3.2 GB
	Ensemble Weights: {'LightGBMXT_BAG_L1': 0.583, 'RandomForestMSE_BAG_L1': 0.375, 'LightGBM_BAG_L1': 0.042}
	-10.4545	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting 106 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 16.09s of the 16.05s of remaining time.
Specified total num_gpus: 1, but only 0 are available. Will use 0 instead
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=1.49%)
	-10.8968	 = Validation score   (-root_mean_squared_error)
	5.85s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBM_BAG_L2 ... Training model for up to 6.17s of the 6.13s of remaining time.
Specified total num_gpus: 1, but only 0 are available. Will use 0 instead
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=2.40%)
	-11.1847	 = Validation score   (-root_mean_squared_error)
	5.49s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: WeightedEnsemble_L3 ... Training model for up to 74.82s of the -5.09s of remaining time.
Specified total num_gpus: 1, but only 0 are available. Will use 0 instead
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/1.8 GB
	Ensemble Weights: {'LightGBMXT_BAG_L1': 0.538, 'RandomForestMSE_BAG_L1': 0.385, 'LightGBMXT_BAG_L2': 0.077}
	-10.4516	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 80.14s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 1847.6 rows/s (262 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1_FULL ...
Specified total num_gpus: 1, but only 0 are available. Will use 0 instead
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/1.8 GB
	3.02s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1_FULL ...
Specified total num_gpus: 1, but only 0 are available. Will use 0 instead
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/3.1 GB
	3.08s	 = Training   runtime
Fitting model: RandomForestMSE_BAG_L1_FULL | Skipping fit via cloning parent ...
	5.53s	 = Training   runtime
	0.29s	 = Validation runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBMXT_BAG_L1': 0.583, 'RandomForestMSE_BAG_L1': 0.375, 'LightGBM_BAG_L1': 0.042}
	0.01s	 = Training   runtime
Fitting 1 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L2_FULL ...
Specified total num_gpus: 1, but only 0 are available. Will use 0 instead
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/3.0 GB
	3.93s	 = Training   runtime
Fitting 1 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L2_FULL ...
Specified total num_gpus: 1, but only 0 are available. Will use 0 instead
	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/3.0 GB
	3.04s	 = Training   runtime
Fitting model: WeightedEnsemble_L3_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBMXT_BAG_L1': 0.538, 'RandomForestMSE_BAG_L1': 0.385, 'LightGBMXT_BAG_L2': 0.077}
	0.01s	 = Training   runtime
Updated best model to "WeightedEnsemble_L3_FULL" (Previously "WeightedEnsemble_L3"). AutoGluon will default to using "WeightedEnsemble_L3_FULL" for predict() and predict_proba().
Refit complete, total runtime = 15.08s ... Best model: "WeightedEnsemble_L3_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("D:\SET50_direction_prediction_paper\outputs\tuned_strong_models\autogluon_tabular_high_quality\models\fold_1\ds_sub_fit\sub_fit_ho")
Deleting DyStack predictor artifacts (clean_up_fits=True) ...
Leaderboard on holdout data (DyStack):
                         model  score_holdout  score_val              eval_metric  pred_time_test  pred_time_val   fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0         LightGBM_BAG_L1_FULL      -9.423311 -10.922475  root_mean_squared_error        0.047132            NaN   3.079989                 0.047132                     NaN           3.079989            1       True          2
1     WeightedEnsemble_L3_FULL      -9.576776 -10.451595  root_mean_squared_error        0.416926            NaN  15.582240                 0.030125                     NaN           0.011332            3       True          7
2     WeightedEnsemble_L2_FULL      -9.587510 -10.454496  root_mean_squared_error        0.322179            NaN  11.648765                 0.034512                     NaN           0.012179            2       True          4
3       LightGBMXT_BAG_L2_FULL      -9.631888 -10.896836  root_mean_squared_error        0.386800            NaN  15.570908                 0.099134                     NaN           3.934323            2       True          5
4         LightGBM_BAG_L2_FULL      -9.758553 -11.184675  root_mean_squared_error        0.357016            NaN  14.678043                 0.069350                     NaN           3.041458            2       True          6
5       LightGBMXT_BAG_L1_FULL      -9.834802 -10.658050  root_mean_squared_error        0.072646            NaN   3.021821                 0.072646                     NaN           3.021821            1       True          1
6  RandomForestMSE_BAG_L1_FULL      -9.957129 -10.877376  root_mean_squared_error        0.167889       0.292208   5.534775                 0.167889                0.292208           5.534775            1       True          3
	1	 = Optimal   num_stack_levels (Stacked Overfitting Occurred: False)
	98s	 = DyStack   runtime |	202s	 = Remaining runtime
Starting main fit with num_stack_levels=1.
	For future fit calls on this dataset, you can skip DyStack to save time: `predictor.fit(..., dynamic_stacking=False, num_stack_levels=1)`
Beginning AutoGluon training ... Time limit = 202s
AutoGluon will save models to "D:\SET50_direction_prediction_paper\outputs\tuned_strong_models\autogluon_tabular_high_quality\models\fold_1"
Train Data Rows:    2359
Train Data Columns: 116
Label Column:       Target_Next_Close
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    3142.53 MB
	Train Data (Original)  Memory Usage: 2.09 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 116 | ['Open_D', 'High_D', 'Low_D', 'Close_D', 'Volume_D', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 116 | ['Open_D', 'High_D', 'Low_D', 'Close_D', 'Volume_D', ...]
	0.2s = Fit runtime
	116 features in original data used to generate 116 features in processed data.
	Train Data (Processed) Memory Usage: 2.09 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.18s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],

## AutoGluon TimeSeries Upper Bound

`presets="high_quality"`, 600 seconds per fold, one-step walk-forward forecasting.

In [ ]:
from models.tuned_strong_models import run_autogluon_timeseries_strong

autogluon_timeseries_metrics = run_autogluon_timeseries_strong()
autogluon_timeseries_metrics

autogluon_timeseries_high_quality:   0%|          | 0/4 [00:00<?, ?fold/s]

TypeError: TimeSeriesPredictor.fit() got an unexpected keyword argument 'num_gpus'

## Chronos-2 Small 28M

Zero-shot one-step walk-forward inference with historical Full TA covariates.

In [5]:
from models.tuned_strong_models import run_chronos2_small_zero_shot

chronos2_small_metrics = run_chronos2_small_zero_shot()
chronos2_small_metrics

config.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

d:\conda_envs\my_env\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\narak\.cache\huggingface\hub\models--autogluon--chronos-2-small. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

model.safetensors:   0%|          | 0.00/112M [00:00<?, ?B/s]

chronos2_small_zero_shot:   0%|          | 0/4 [00:00<?, ?fold/s]

chronos2_small_zero_shot_fold_1:   0%|          | 0/241 [00:00<?, ?day/s]

chronos2_small_zero_shot_fold_2:   0%|          | 0/243 [00:00<?, ?day/s]

chronos2_small_zero_shot_fold_3:   0%|          | 0/244 [00:00<?, ?day/s]

chronos2_small_zero_shot_fold_4:   0%|          | 0/234 [00:00<?, ?day/s]

     fold  train_start_year  train_end_year  test_year  n_train  n_test  \
0  fold_1              2012            2021       2022     2359     241
1  fold_2              2012            2022       2023     2600     243
2  fold_3              2012            2023       2024     2843     244
3  fold_4              2012            2024       2025     3087     234

        rmse       mae      mape        r2  direction_accuracy
0   7.212138  5.540372  0.563936  0.894993            0.535270
1   8.100963  6.223983  0.673532  0.966852            0.506173
2   7.679984  5.835273  0.672818  0.969585            0.422131
3  11.576557  8.619663  1.100249  0.948266            0.529915
      train_start_year  train_end_year  test_year  n_train  n_test     rmse  \
mean            2012.0          2022.5     2023.5  2722.25   240.5  8.64241

           mae      mape        r2  direction_accuracy
mean  6.554823  0.752634  0.944924            0.498372

,fold,train_start_year,train_end_year,test_year,n_train,n_test,rmse,mae,mape,r2,direction_accuracy
0,fold_1,2012,2021,2022,2359,241,7.212138,5.540372,0.563936,0.894993,0.535270
1,fold_2,2012,2022,2023,2600,243,8.100963,6.223983,0.673532,0.966852,0.506173
2,fold_3,2012,2023,2024,2843,244,7.679984,5.835273,0.672818,0.969585,0.422131
3,fold_4,2012,2024,2025,3087,234,11.576557,8.619663,1.100249,0.948266,0.529915

## Chronos-2 Base 120M

Main foundation result using zero-shot one-step walk-forward inference with historical Full TA covariates.

In [1]:
from models.tuned_strong_models import run_chronos2_base_zero_shot

chronos2_base_metrics = run_chronos2_base_zero_shot()
chronos2_base_metrics--

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/478M [00:00<?, ?B/s]

chronos2_base_120m_zero_shot:   0%|          | 0/4 [00:00<?, ?fold/s]

chronos2_base_120m_zero_shot_fold_1:   0%|          | 0/241 [00:00<?, ?day/s]

chronos2_base_120m_zero_shot_fold_2:   0%|          | 0/243 [00:00<?, ?day/s]

chronos2_base_120m_zero_shot_fold_3:   0%|          | 0/244 [00:00<?, ?day/s]

chronos2_base_120m_zero_shot_fold_4:   0%|          | 0/234 [00:00<?, ?day/s]

     fold  train_start_year  train_end_year  test_year  n_train  n_test  \
0  fold_1              2012            2021       2022     2359     241
1  fold_2              2012            2022       2023     2600     243
2  fold_3              2012            2023       2024     2843     244
3  fold_4              2012            2024       2025     3087     234

        rmse       mae      mape        r2  direction_accuracy
0   6.980502  5.242073  0.533633  0.901630            0.535270
1   7.451673  5.655328  0.610673  0.971952            0.551440
2   6.972119  5.246571  0.605483  0.974933            0.495902
3  10.358756  8.065858  1.022964  0.958578            0.405983
      train_start_year  train_end_year  test_year  n_train  n_test      rmse  \
mean            2012.0          2022.5     2023.5  2722.25   240.5  7.940762

           mae      mape        r2  direction_accuracy
mean  6.052458  0.693188  0.951773            0.497149

,fold,train_start_year,train_end_year,test_year,n_train,n_test,rmse,mae,mape,r2,direction_accuracy
0,fold_1,2012,2021,2022,2359,241,6.980502,5.242073,0.533633,0.901630,0.535270
1,fold_2,2012,2022,2023,2600,243,7.451673,5.655328,0.610673,0.971952,0.551440
2,fold_3,2012,2023,2024,2843,244,6.972119,5.246571,0.605483,0.974933,0.495902
3,fold_4,2012,2024,2025,3087,234,10.358756,8.065858,1.022964,0.958578,0.405983

## Chronos-2 Official Strong Ensemble

AutoGluon `chronos2_ensemble` combines Chronos-2 Base zero-shot with a fine-tuned Chronos-2 Small model. Training remains inside each outer training fold.

In [ ]:
from models.tuned_strong_models import run_chronos2_ensemble_strong

chronos2_ensemble_metrics = run_chronos2_ensemble_strong()
chronos2_ensemble_metrics

## Load Completed Results

In [ ]:
import pandas as pd

output_root = project_root / "outputs" / "tuned_strong_models"
saved_metrics = {
    path.parent.name: pd.read_csv(path)
    for path in sorted(output_root.glob("*/metrics_by_fold.csv"))
}
saved_metrics